//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GMSWeb.SysCorporateServices {
    
    public partial class banner {
        protected System.Web.UI.HtmlControls.HtmlHead Head1;
        protected GMSWeb.SiteHeader MySiteHeader;
        protected System.Web.UI.HtmlControls.HtmlForm form1;
        protected System.Web.UI.WebControls.Label lblCountry;
        protected System.Web.UI.WebControls.DropDownList ddlCountry;
        protected System.Web.UI.WebControls.Label lblDivision;
        protected System.Web.UI.WebControls.DropDownList ddlDivision;
        protected System.Web.UI.WebControls.Label lblCompany;
        protected System.Web.UI.WebControls.DropDownList ddlCompany;
        protected System.Web.UI.HtmlControls.HtmlGenericControl linkTag;
    }
}
