//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//	   DO NOT MODIFY contents of this file. Changes to this
//	   file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using Wilson.ORMapper;
using GMSCore;

namespace GMSCore.Entity
{
	///<summary>Database mapping to table tbCompanyManagementUser</summary>
	[DataObject(true)]
    public partial class BrandCategory : PersistBase<BrandCategory>, IObjectHelper
	{
		#region Properties
	
		private short _categoryID;
		///<summary>Database mapping to column tbCompanyManagementUser.CoyID</summary>
		[DataObjectField(true, false)]
		public short CategoryID
		{
			get { return _categoryID; }
			set
			{
				if (_categoryID != value)
				{
                    _categoryID = value;
					OnPropertyChanged("CategoryID");
				}
			}
		}
			
		private string _categoryName;
		///<summary>Database mapping to column tbCompanyManagementUser.MGUserID</summary>
		public string CategoryName
		{
			get { return _categoryName; }
			set
			{
				if (_categoryName != value)
				{
                    _categoryName = value;
					OnPropertyChanged("CategoryName");
				}
			}
		}

        private string _shortName;
        ///<summary>Database mapping to column tbCompanyManagementUser.MGUserID</summary>
        public string ShortName
        {
            get { return _shortName; }
            set
            {
                if (_shortName != value)
                {
                    _shortName = value;
                    OnPropertyChanged("ShortName");
                }
            }
        }

        private short _sequence;
        ///<summary>Database mapping to column tbCompanyManagementUser.MGUserID</summary>
        public short Sequence
        {
            get { return _sequence; }
            set
            {
                if (_sequence != value)
                {
                    _sequence = value;
                    OnPropertyChanged("Sequence");
                }
            }
        }

        #endregion

        ///<summary>Initializes a new instance of this class</summary>
        public BrandCategory() : base()
		{
			// Default Constructor
		}
		
		///<summary>Retrieve an instance of this class using its ID from the persistence store</summary>
		[DataObjectMethod(DataObjectMethodType.Select)]
        public static BrandCategory RetrieveByKey(short categoryID)
		{
			DBManager db = DBManager.GetInstance();
			QueryHelper helper = db.Engine.QueryHelper;
			string where = helper.GetExpression("BrandCategory.CategoryID", categoryID);
			//where += " and ";
			//where += helper.GetExpression("BrandCategory.MGUserID", mGUserID);

			return RetrieveFirst(where);			
		}

		#region IObjectHelper
		/// <summary>Indexer to update local member variables</summary>	
		/// <remarks>This indexer is used by the Wilson ORMapper</remarks>
		object IObjectHelper.this[string memberName]
		{
			get {
				switch (memberName) {
					case "_categoryID": return _categoryID;
					case "_categoryName": return _categoryName;
                    case "_shortName": return _shortName;
                    case "_sequence": return _sequence;
                    default: throw new Exception(string.Format("Mapping: IObjectHelper Get is missing member case {0}", memberName));
				}
			}
			set {
				//handle null values
				if(value == null)
					return;
					
				switch (memberName) {
					case "_categoryID": _categoryID = (short)value; break;
					case "_categoryName": _categoryName = (string)value; break;
                    case "_shortName": _shortName = (string)value; break;
                    case "_sequence": _sequence = (short)value; break;
                    default: throw new Exception(string.Format("Mapping: IObjectHelper Set is missing member case {0}", memberName));
				}
			}
		}
		#endregion
		
		#region ToString
		///<summary>
		///Overwrites the base ToString method. This is used for AuditTrail purposes.
		///</summary>
		public override string ToString()
		{
			System.Text.StringBuilder stb = new System.Text.StringBuilder(500);
			
			stb.AppendFormat("_coyID={0}\n,", _categoryID.ToString() );
			stb.AppendFormat("_mGUserID={0}\n,", _categoryName.ToString() );
            stb.AppendFormat("_shortName={0}\n,", _shortName.ToString());
            stb.AppendFormat("_sequence={0}\n,", _sequence.ToString());
            return stb.ToString();
		}
		#endregion

	}
}
