//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//	   DO NOT MODIFY contents of this file. Changes to this
//	   file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using Wilson.ORMapper;


namespace GMSCore.Entity
{
	///<summary>Database mapping to table tbDivisionUser</summary>
	[DataObject(true)]
    public partial class DivisionUser : PersistBase<DivisionUser>, IObjectHelper
	{
		#region Properties
	
		private short _coyID;
		///<summary>Database mapping to column tbDivisionUser.CoyID</summary>
		[DataObjectField(true, false)]
		public short CoyID
		{
			get { return _coyID; }
			set
			{
				if (_coyID != value)
				{
					_coyID = value;
					OnPropertyChanged("CoyID");
				}
			}
		}
			
		private short _userNumID;
		///<summary>Database mapping to column tbDivisionUser.UserNumID</summary>
		[DataObjectField(true, false)]
		public short UserNumID
		{
			get { return _userNumID; }
			set
			{
				if (_userNumID != value)
				{
					_userNumID = value;
					OnPropertyChanged("UserNumID");
				}
			}
		}
			
		private string _divisionID;
		///<summary>Database mapping to column tbDivisionUser.DivisionID</summary>
		public string DivisionID
		{
			get { return _divisionID; }
			set
			{
				if (_divisionID != value)
				{
					_divisionID = value;
					OnPropertyChanged("DivisionID");
				}
			}
		}
		
		#endregion
		
		///<summary>Initializes a new instance of this class</summary>
		public DivisionUser() : base()
		{
			// Default Constructor
		}
		
		///<summary>Retrieve an instance of this class using its ID from the persistence store</summary>
		[DataObjectMethod(DataObjectMethodType.Select)]
        public static DivisionUser RetrieveByKey(short coyID, short userNumID)
		{
			DBManager db = DBManager.GetInstance();
			QueryHelper helper = db.Engine.QueryHelper;
			string where = helper.GetExpression("DivisionUser.CoyID", coyID);
			where += " and ";
			where += helper.GetExpression("DivisionUser.UserNumID", userNumID);

			return RetrieveFirst(where);			
		}
		
		///<summary>Delete instance from the persistence store based on primary key(s)</summary>
		[DataObjectMethod(DataObjectMethodType.Delete)]
        public static int DeleteByKey(short coyID, short userNumID)
		{			
			DBManager db = DBManager.GetInstance();		
			QueryHelper helper = db.Engine.QueryHelper;
			string where = helper.GetExpression("DivisionUser.CoyID", coyID);
			where += " and ";
			where += helper.GetExpression("DivisionUser.UserNumID", userNumID);
			
			return Delete(where);
		}
		
		///<summary>Delete instance from the persistence store based on primary key(s) using a transaction</summary>
		///<param name="transaction">An instance of a Wilson.ORMapper.Transaction to perform operation with.</param>
		public static int DeleteByKey(Wilson.ORMapper.Transaction transaction, short coyID, short userNumID)
		{			
			DBManager db = DBManager.GetInstance();
			QueryHelper helper = db.Engine.QueryHelper;
			string where = helper.GetExpression("DivisionUser.CoyID", coyID);
			where += " and ";
			where += helper.GetExpression("DivisionUser.UserNumID", userNumID);
			
			return Delete(transaction, where);
		}		
		#region IObjectHelper
		/// <summary>Indexer to update local member variables</summary>	
		/// <remarks>This indexer is used by the Wilson ORMapper</remarks>
		object IObjectHelper.this[string memberName]
		{
			get {
				switch (memberName) {
					case "_coyID": return _coyID;
					case "_userNumID": return _userNumID;
					case "_divisionID": return _divisionID;
									
					default: throw new Exception(string.Format("Mapping: IObjectHelper Get is missing member case {0}", memberName));
				}
			}
			set {
				//handle null values
				if(value == null)
					return;
					
				switch (memberName) {
					case "_coyID": _coyID = (short)value; break;
					case "_userNumID": _userNumID = (short)value; break;
					case "_divisionID": _divisionID = (string)value; break;
				
					default: throw new Exception(string.Format("Mapping: IObjectHelper Set is missing member case {0}", memberName));
				}
			}
		}
		#endregion
		
		#region ToString
		///<summary>
		///Overwrites the base ToString method. This is used for AuditTrail purposes.
		///</summary>
		public override string ToString()
		{
			System.Text.StringBuilder stb = new System.Text.StringBuilder(500);
			
			stb.AppendFormat("_coyID={0}\n,", _coyID.ToString() );
			stb.AppendFormat("_userNumID={0}\n,", _userNumID.ToString() );
			stb.AppendFormat("_divisionID={0}\n,", _divisionID.ToString() );
							
			
			return stb.ToString();
		}
		#endregion

	}
}
