//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//	   DO NOT MODIFY contents of this file. Changes to this
//	   file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using Wilson.ORMapper;


namespace GMSCore.Entity
{
	///<summary>Database mapping to table tbEmployeeHistory</summary>
	[DataObject(true)]
    public partial class EmployeeHistory : PersistBase<EmployeeHistory>, IObjectHelper
	{
		#region Properties
	
		private short _coyID = 0;
		///<summary>Database mapping to column tbEmployeeHistory.CoyID</summary>
		public short CoyID
		{
			get { return _coyID; }
			set
			{
				if (_coyID != value)
				{
					_coyID = value;
					OnPropertyChanged("CoyID");
				}
			}
		}
			
		private string _employeeNo;
		///<summary>Database mapping to column tbEmployeeHistory.EmployeeNo</summary>
		public string EmployeeNo
		{
			get { return _employeeNo; }
			set
			{
				if (_employeeNo != value)
				{
					_employeeNo = value;
					OnPropertyChanged("EmployeeNo");
				}
			}
		}
			
		private DateTime _startDate = DateTime.Parse("01/01/1900 00:00:00");
		///<summary>Database mapping to column tbEmployeeHistory.StartDate</summary>
		public DateTime StartDate
		{
			get { return _startDate; }
			set
			{
				if (_startDate != value)
				{
					_startDate = value;
					OnPropertyChanged("StartDate");
				}
			}
		}
			
		private DateTime _endDate = DateTime.Parse("01/01/1900 00:00:00");
		///<summary>Database mapping to column tbEmployeeHistory.EndDate</summary>
		public DateTime EndDate
		{
			get { return _endDate; }
			set
			{
				if (_endDate != value)
				{
					_endDate = value;
					OnPropertyChanged("EndDate");
				}
			}
		}
			
		private string _companyName = "";
		///<summary>Database mapping to column tbEmployeeHistory.CompanyName</summary>
		public string CompanyName
		{
			get { return _companyName; }
			set
			{
				if (_companyName != value)
				{
					_companyName = value;
					OnPropertyChanged("CompanyName");
				}
			}
		}
			
		private string _designation = "";
		///<summary>Database mapping to column tbEmployeeHistory.Designation</summary>
		public string Designation
		{
			get { return _designation; }
			set
			{
				if (_designation != value)
				{
					_designation = value;
					OnPropertyChanged("Designation");
				}
			}
		}
			
		private short _createdBy = 0;
		///<summary>Database mapping to column tbEmployeeHistory.CreatedBy</summary>
		public short CreatedBy
		{
			get { return _createdBy; }
			set
			{
				if (_createdBy != value)
				{
					_createdBy = value;
					OnPropertyChanged("CreatedBy");
				}
			}
		}
			
		private DateTime _createdDate = DateTime.Parse("01/01/1900 00:00:00");
		///<summary>Database mapping to column tbEmployeeHistory.CreatedDate</summary>
		public DateTime CreatedDate
		{
			get { return _createdDate; }
			set
			{
				if (_createdDate != value)
				{
					_createdDate = value;
					OnPropertyChanged("CreatedDate");
				}
			}
		}
		
		#endregion
		
		///<summary>Initializes a new instance of this class</summary>
		public EmployeeHistory() : base()
		{
			// Default Constructor
		}
		
		#region IObjectHelper
		/// <summary>Indexer to update local member variables</summary>	
		/// <remarks>This indexer is used by the Wilson ORMapper</remarks>
		object IObjectHelper.this[string memberName]
		{
			get {
				switch (memberName) {
					case "_coyID": return _coyID;
					case "_employeeNo": return _employeeNo;
					case "_startDate": return _startDate;
					case "_endDate": return _endDate;
					case "_companyName": return _companyName;
					case "_designation": return _designation;
					case "_createdBy": return _createdBy;
					case "_createdDate": return _createdDate;
									
					default: throw new Exception(string.Format("Mapping: IObjectHelper Get is missing member case {0}", memberName));
				}
			}
			set {
				//handle null values
				if(value == null)
					return;
					
				switch (memberName) {
					case "_coyID": _coyID = (short)value; break;
					case "_employeeNo": _employeeNo = (string)value; break;
					case "_startDate": _startDate = (DateTime)value; break;
					case "_endDate": _endDate = (DateTime)value; break;
					case "_companyName": _companyName = (string)value; break;
					case "_designation": _designation = (string)value; break;
					case "_createdBy": _createdBy = (short)value; break;
					case "_createdDate": _createdDate = (DateTime)value; break;
				
					default: throw new Exception(string.Format("Mapping: IObjectHelper Set is missing member case {0}", memberName));
				}
			}
		}
		#endregion
		
		#region ToString
		///<summary>
		///Overwrites the base ToString method. This is used for AuditTrail purposes.
		///</summary>
		public override string ToString()
		{
			System.Text.StringBuilder stb = new System.Text.StringBuilder(500);
			
			stb.AppendFormat("_coyID={0}\n,", _coyID.ToString() );
			stb.AppendFormat("_employeeNo={0}\n,", _employeeNo.ToString() );
			stb.AppendFormat("_startDate={0}\n,", _startDate.ToString() );
			stb.AppendFormat("_endDate={0}\n,", _endDate.ToString() );
			stb.AppendFormat("_companyName={0}\n,", _companyName.ToString() );
			stb.AppendFormat("_designation={0}\n,", _designation.ToString() );
			stb.AppendFormat("_createdBy={0}\n,", _createdBy.ToString() );
			stb.AppendFormat("_createdDate={0}\n,", _createdDate.ToString() );
							
			
			return stb.ToString();
		}
		#endregion

	}
}
