//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//	   This file is safe to edit because it will not be overwritten.
// </autogenerated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Data;
using Wilson.ORMapper;

namespace GMSCore.Entity
{
	public partial class MRAttachment
	{
        
        #region IsValid
		/// <summary>
        /// Validates the properies of this instance.
        /// </summary>
        /// <returns>
        /// A value indicating if this object is valid.
        /// </returns>
        public override bool IsValid()
        {
            // must be called first to clean error
            bool isValid = base.IsValid();

            //TODO: Validate properties here.            
            //When there is an error, call OnValidationError to publish the error.
            //Example: base.OnValidationError("Name", "Name is required.");

            //Returning false will cause an exception to be thrown on Save.
            return isValid;
        }
        #endregion
        
        
        #region IsAccessible [CREATE, READ, UPDATE, DELETE]
		/// <summary>
        /// Validates whether a given user can Create this Object
        /// </summary>
        /// <param name="userId">Integer value of the User's User ID.</param>
        /// <returns>True or False indicating if object is accessible</returns>
        public static bool IsCreateAccessible( int userId )
        {
			if( userId>0 )
			{
				

				
			}
        
			return true;
        }        
        /// <summary>
        /// Validates whether a given user can Read this Object
        /// </summary>
        /// <param name="userId">Integer value of the User's User ID.</param>
        /// <returns>True or False indicating if object is accessible</returns>
        public static bool IsReadAccessible( int userId )
        {
			if( userId>0 )
			{
				

            }
        
			return true;
        }
        
        /// <summary>
        /// Validates whether a given user can Update this Object
        /// </summary>
        /// <param name="userId">Integer value of the User's User ID.</param>
        /// <returns>True or False indicating if object is accessible</returns>
        public static bool IsUpdateAccessible( int userId )
        {
			if( userId>0 )
			{
				
				
			}
        
			return true;
        }
        
        /// <summary>
        /// Validates whether a given user can Delete this Object
        /// </summary>
        /// <param name="userId">Integer value of the User's User ID.</param>
        /// <returns>True or False indicating if object is accessible</returns>
        public static bool IsDeleteAccessible( int userId )
        {
			if( userId>0 )
			{
				

				
			}
        
			return true;
        }
        #endregion
        
        #region Audit [CREATE, READ, UPDATE, DELETE]
        /// <summary>
        /// Audits the Create action
        /// </summary>
        /// <param name="userId">Integer value of the User's User ID.</param>
        public void Audit_Create( int userId )
        {
			
			
        }

        /// <summary>
        /// Audits the Read action
        /// </summary>
        /// <param name="userId">Integer value of the User's User ID.</param>        
        public void Audit_Read(int userId)
        {
            
        }
        
        /// <summary>
        /// Audits the Update action
        /// </summary>
        /// <param name="userId">Integer value of the User's User ID.</param>        
        public void Audit_Update( int userId )
        {
			
			
        }
        
        /// <summary>
        /// Audits the Delete action
        /// </summary>
        /// <param name="userId">Integer value of the User's User ID.</param>        
        public void Audit_Delete( int userId )
        {
			
			
        }
        #endregion
        
	
	}
}