//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//	   DO NOT MODIFY contents of this file. Changes to this
//	   file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using Wilson.ORMapper;


namespace GMSCore.Entity
{
	///<summary>Database mapping to table tbMRPurchaser</summary>
	[DataObject(true)]
    public partial class MRPurchaser : PersistBase<MRPurchaser>, IObjectHelper
	{
		#region Properties
	
		private short _coyID;
		///<summary>Database mapping to column tbMRPurchaser.CoyID</summary>
		public short CoyID
		{
			get { return _coyID; }
			set
			{
				if (_coyID != value)
				{
					_coyID = value;
					OnPropertyChanged("CoyID");
				}
			}
		}
			
		private string _purchaserName = "";
		///<summary>Database mapping to column tbMRPurchaser.PurchaserName</summary>
		public string PurchaserName
		{
			get { return _purchaserName; }
			set
			{
				if (_purchaserName != value)
				{
					_purchaserName = value;
					OnPropertyChanged("PurchaserName");
				}
			}
		}
			
		private string _purchaserEmail = "";
		///<summary>Database mapping to column tbMRPurchaser.PurchaserEmail</summary>
		public string PurchaserEmail
		{
			get { return _purchaserEmail; }
			set
			{
				if (_purchaserEmail != value)
				{
					_purchaserEmail = value;
					OnPropertyChanged("PurchaserEmail");
				}
			}
		}
		
		#endregion
		
		///<summary>Initializes a new instance of this class</summary>
		public MRPurchaser() : base()
		{
			// Default Constructor
		}
		
		#region IObjectHelper
		/// <summary>Indexer to update local member variables</summary>	
		/// <remarks>This indexer is used by the Wilson ORMapper</remarks>
		object IObjectHelper.this[string memberName]
		{
			get {
				switch (memberName) {
					case "_coyID": return _coyID;
					case "_purchaserName": return _purchaserName;
					case "_purchaserEmail": return _purchaserEmail;
									
					default: throw new Exception(string.Format("Mapping: IObjectHelper Get is missing member case {0}", memberName));
				}
			}
			set {
				//handle null values
				if(value == null)
					return;
					
				switch (memberName) {
					case "_coyID": _coyID = (short)value; break;
					case "_purchaserName": _purchaserName = (string)value; break;
					case "_purchaserEmail": _purchaserEmail = (string)value; break;
				
					default: throw new Exception(string.Format("Mapping: IObjectHelper Set is missing member case {0}", memberName));
				}
			}
		}
		#endregion
		
		#region ToString
		///<summary>
		///Overwrites the base ToString method. This is used for AuditTrail purposes.
		///</summary>
		public override string ToString()
		{
			System.Text.StringBuilder stb = new System.Text.StringBuilder(500);
			
			stb.AppendFormat("_coyID={0}\n,", _coyID.ToString() );
			stb.AppendFormat("_purchaserName={0}\n,", _purchaserName.ToString() );
			stb.AppendFormat("_purchaserEmail={0}\n,", _purchaserEmail.ToString() );
							
			
			return stb.ToString();
		}
		#endregion

	}
}
