//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//	   DO NOT MODIFY contents of this file. Changes to this
//	   file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using Wilson.ORMapper;


namespace GMSCore.Entity
{
	///<summary>Database mapping to table tbMRShipMode</summary>
	[DataObject(true)]
    public partial class MRShipMode : PersistBase<MRShipMode>, IObjectHelper
	{
		#region Properties
	
		private string _shipModeID;
		///<summary>Database mapping to column tbMRShipMode.ShipModeID</summary>
		public string ShipModeID
		{
			get { return _shipModeID; }
			set
			{
				if (_shipModeID != value)
				{
					_shipModeID = value;
					OnPropertyChanged("ShipModeID");
				}
			}
		}
			
		private string _shipModeName;
		///<summary>Database mapping to column tbMRShipMode.ShipModeName</summary>
		public string ShipModeName
		{
			get { return _shipModeName; }
			set
			{
				if (_shipModeName != value)
				{
					_shipModeName = value;
					OnPropertyChanged("ShipModeName");
				}
			}
		}
		
		#endregion
		
		///<summary>Initializes a new instance of this class</summary>
		public MRShipMode() : base()
		{
			// Default Constructor
		}
		
		#region IObjectHelper
		/// <summary>Indexer to update local member variables</summary>	
		/// <remarks>This indexer is used by the Wilson ORMapper</remarks>
		object IObjectHelper.this[string memberName]
		{
			get {
				switch (memberName) {
					case "_shipModeID": return _shipModeID;
					case "_shipModeName": return _shipModeName;
									
					default: throw new Exception(string.Format("Mapping: IObjectHelper Get is missing member case {0}", memberName));
				}
			}
			set {
				//handle null values
				if(value == null)
					return;
					
				switch (memberName) {
					case "_shipModeID": _shipModeID = (string)value; break;
					case "_shipModeName": _shipModeName = (string)value; break;
				
					default: throw new Exception(string.Format("Mapping: IObjectHelper Set is missing member case {0}", memberName));
				}
			}
		}
		#endregion
		
		#region ToString
		///<summary>
		///Overwrites the base ToString method. This is used for AuditTrail purposes.
		///</summary>
		public override string ToString()
		{
			System.Text.StringBuilder stb = new System.Text.StringBuilder(500);
			
			stb.AppendFormat("_shipModeID={0}\n,", _shipModeID.ToString() );
			stb.AppendFormat("_shipModeName={0}\n,", _shipModeName.ToString() );
							
			
			return stb.ToString();
		}
		#endregion

	}
}
