//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//	   DO NOT MODIFY contents of this file. Changes to this
//	   file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using Wilson.ORMapper;
using GMSCore;

namespace GMSCore.Entity
{
	///<summary>Database mapping to table tbQuotationDetail</summary>
	[DataObject(true)]
    public partial class QuotationDetail : PersistBase<QuotationDetail>, IObjectHelper
	{
		#region Properties
	
		private short _coyID;
		///<summary>Database mapping to column tbQuotationDetail.CoyID</summary>
		[DataObjectField(true, false)]
		public short CoyID
		{
			get { return _coyID; }
			set
			{
				if (_coyID != value)
				{
					_coyID = value;
					OnPropertyChanged("CoyID");
				}
			}
		}
			
		private string _quotationNo;
		///<summary>Database mapping to column tbQuotationDetail.QuotationNo</summary>
		[DataObjectField(true, false)]
		public string QuotationNo
		{
			get { return _quotationNo; }
			set
			{
				if (_quotationNo != value)
				{
					_quotationNo = value;
					OnPropertyChanged("QuotationNo");
				}
			}
		}
			
		private byte _sNNo;
		///<summary>Database mapping to column tbQuotationDetail.SNNo</summary>
		[DataObjectField(true, false)]
		public byte SNNo
		{
			get { return _sNNo; }
			set
			{
				if (_sNNo != value)
				{
					_sNNo = value;
					OnPropertyChanged("SNNo");
				}
			}
		}
			
		private string _productCode = "";
		///<summary>Database mapping to column tbQuotationDetail.ProductCode</summary>
		public string ProductCode
		{
			get { return _productCode; }
			set
			{
				if (_productCode != value)
				{
					_productCode = value;
					OnPropertyChanged("ProductCode");
				}
			}
		}
			
		private string _productDescription = "";
		///<summary>Database mapping to column tbQuotationDetail.ProductDescription</summary>
		public string ProductDescription
		{
			get { return _productDescription; }
			set
			{
				if (_productDescription != value)
				{
					_productDescription = value;
					OnPropertyChanged("ProductDescription");
				}
			}
		}
			
		private Nullable<decimal> _quantity;
		///<summary>Database mapping to column tbQuotationDetail.Quantity</summary>
		public Nullable<decimal> Quantity
		{
			get { return _quantity; }
			set
			{
				if (_quantity != value)
				{
					_quantity = value;
					OnPropertyChanged("Quantity");
				}
			}
		}
			
		private Nullable<decimal> _listPrice;
		///<summary>Database mapping to column tbQuotationDetail.ListPrice</summary>
		public Nullable<decimal> ListPrice
		{
			get { return _listPrice; }
			set
			{
				if (_listPrice != value)
				{
					_listPrice = value;
					OnPropertyChanged("ListPrice");
				}
			}
		}
			
		private Nullable<decimal> _minSellingPrice;
		///<summary>Database mapping to column tbQuotationDetail.MinSellingPrice</summary>
		public Nullable<decimal> MinSellingPrice
		{
			get { return _minSellingPrice; }
			set
			{
				if (_minSellingPrice != value)
				{
					_minSellingPrice = value;
					OnPropertyChanged("MinSellingPrice");
				}
			}
		}
			
		private Nullable<decimal> _unitPrice;
		///<summary>Database mapping to column tbQuotationDetail.UnitPrice</summary>
		public Nullable<decimal> UnitPrice
		{
			get { return _unitPrice; }
			set
			{
				if (_unitPrice != value)
				{
					_unitPrice = value;
					OnPropertyChanged("UnitPrice");
				}
			}
		}
			
		private Nullable<decimal> _cost;
		///<summary>Database mapping to column tbQuotationDetail.Cost</summary>
		public Nullable<decimal> Cost
		{
			get { return _cost; }
			set
			{
				if (_cost != value)
				{
					_cost = value;
					OnPropertyChanged("Cost");
				}
			}
		}
			
		private short _createdBy = 0;
		///<summary>Database mapping to column tbQuotationDetail.CreatedBy</summary>
		public short CreatedBy
		{
			get { return _createdBy; }
			set
			{
				if (_createdBy != value)
				{
					_createdBy = value;
					OnPropertyChanged("CreatedBy");
				}
			}
		}
			
		private Nullable<DateTime> _createdDate;
		///<summary>Database mapping to column tbQuotationDetail.CreatedDate</summary>
		public Nullable<DateTime> CreatedDate
		{
			get { return _createdDate; }
			set
			{
				if (_createdDate != value)
				{
					_createdDate = value;
					OnPropertyChanged("CreatedDate");
				}
			}
		}
			
		private short _modifiedBy = 0;
		///<summary>Database mapping to column tbQuotationDetail.ModifiedBy</summary>
		public short ModifiedBy
		{
			get { return _modifiedBy; }
			set
			{
				if (_modifiedBy != value)
				{
					_modifiedBy = value;
					OnPropertyChanged("ModifiedBy");
				}
			}
		}
			
		private Nullable<DateTime> _modifiedDate;
		///<summary>Database mapping to column tbQuotationDetail.ModifiedDate</summary>
		public Nullable<DateTime> ModifiedDate
		{
			get { return _modifiedDate; }
			set
			{
				if (_modifiedDate != value)
				{
					_modifiedDate = value;
					OnPropertyChanged("ModifiedDate");
				}
			}
		}
			
		private Nullable<byte> _dSNNo;
		///<summary>Database mapping to column tbQuotationDetail.DSNNo</summary>
		public Nullable<byte> DSNNo
		{
			get { return _dSNNo; }
			set
			{
				if (_dSNNo != value)
				{
					_dSNNo = value;
					OnPropertyChanged("DSNNo");
				}
			}
		}
			
		private byte _revisionNo;
		///<summary>Database mapping to column tbQuotationDetail.RevisionNo</summary>
		[DataObjectField(true, false)]
		public byte RevisionNo
		{
			get { return _revisionNo; }
			set
			{
				if (_revisionNo != value)
				{
					_revisionNo = value;
					OnPropertyChanged("RevisionNo");
				}
			}
		}
			
		private string _dOptSNNo = "";
		///<summary>Database mapping to column tbQuotationDetail.DOptSNNo</summary>
		public string DOptSNNo
		{
			get { return _dOptSNNo; }
			set
			{
				if (_dOptSNNo != value)
				{
					_dOptSNNo = value;
					OnPropertyChanged("DOptSNNo");
				}
			}
		}
			
		private string _uOM = "";
		///<summary>Database mapping to column tbQuotationDetail.UOM</summary>
		public string UOM
		{
			get { return _uOM; }
			set
			{
				if (_uOM != value)
				{
					_uOM = value;
					OnPropertyChanged("UOM");
				}
			}
		}

        private string _recipeNo = "";
        ///<summary>Database mapping to column tbQuotationDetail.RecipeNo</summary>
        public string RecipeNo
        {
            get { return _recipeNo; }
            set
            {
                if (_recipeNo != value)
                {
                    _recipeNo = value;
                    OnPropertyChanged("RecipeNo");
                }
            }
        }

        private string _productNotes = "";
        ///<summary>Database mapping to column tbQuotationDetail.ProductNotes</summary>
        public string ProductNotes
        {
            get { return _productNotes; }
            set
            {
                if (_productNotes != value)
                {
                    _productNotes = value;
                    OnPropertyChanged("ProductNotes");
                }
            }
        }

        private int _batchSize;
        ///<summary>Database mapping to column tbQuotationDetail.BatchSize</summary>
        public int BatchSize
        {
            get { return _batchSize; }
            set
            {
                if (_batchSize != value)
                {
                    _batchSize = value;
                    OnPropertyChanged("BatchSize");
                }
            }
        }

        private string _tagNo = "";
        ///<summary>Database mapping to column tbQuotationDetail.TagNo</summary>
        public string TagNo
        {
            get { return _tagNo; }
            set
            {
                if (_tagNo != value)
                {
                    _tagNo = value;
                    OnPropertyChanged("TagNo");
                }
            }
        }
		
		#endregion
		
		///<summary>Initializes a new instance of this class</summary>
		public QuotationDetail() : base()
		{
			// Default Constructor
		}
		
		///<summary>Retrieve an instance of this class using its ID from the persistence store</summary>
		[DataObjectMethod(DataObjectMethodType.Select)]
        public static QuotationDetail RetrieveByKey(short coyID, string quotationNo, byte sNNo, byte revisionNo)
		{
			DBManager db = DBManager.GetInstance();
			QueryHelper helper = db.Engine.QueryHelper;
			string where = helper.GetExpression("QuotationDetail.CoyID", coyID);
			where += " and ";
			where += helper.GetExpression("QuotationDetail.QuotationNo", quotationNo);
			where += " and ";
			where += helper.GetExpression("QuotationDetail.SNNo", sNNo);
			where += " and ";
			where += helper.GetExpression("QuotationDetail.RevisionNo", revisionNo);

			return RetrieveFirst(where);			
		}
		
		///<summary>Delete instance from the persistence store based on primary key(s)</summary>
		[DataObjectMethod(DataObjectMethodType.Delete)]
        public static int DeleteByKey(short coyID, string quotationNo, byte sNNo, byte revisionNo)
		{			
			DBManager db = DBManager.GetInstance();		
			QueryHelper helper = db.Engine.QueryHelper;
			string where = helper.GetExpression("QuotationDetail.CoyID", coyID);
			where += " and ";
			where += helper.GetExpression("QuotationDetail.QuotationNo", quotationNo);
			where += " and ";
			where += helper.GetExpression("QuotationDetail.SNNo", sNNo);
			where += " and ";
			where += helper.GetExpression("QuotationDetail.RevisionNo", revisionNo);
			
			return Delete(where);
		}
		
		///<summary>Delete instance from the persistence store based on primary key(s) using a transaction</summary>
		///<param name="transaction">An instance of a Wilson.ORMapper.Transaction to perform operation with.</param>
		public static int DeleteByKey(Wilson.ORMapper.Transaction transaction, short coyID, string quotationNo, byte sNNo, byte revisionNo)
		{			
			DBManager db = DBManager.GetInstance();
			QueryHelper helper = db.Engine.QueryHelper;
			string where = helper.GetExpression("QuotationDetail.CoyID", coyID);
			where += " and ";
			where += helper.GetExpression("QuotationDetail.QuotationNo", quotationNo);
			where += " and ";
			where += helper.GetExpression("QuotationDetail.SNNo", sNNo);
			where += " and ";
			where += helper.GetExpression("QuotationDetail.RevisionNo", revisionNo);
			
			return Delete(transaction, where);
		}		
		#region IObjectHelper
		/// <summary>Indexer to update local member variables</summary>	
		/// <remarks>This indexer is used by the Wilson ORMapper</remarks>
		object IObjectHelper.this[string memberName]
		{
			get {
				switch (memberName) {
					case "_coyID": return _coyID;
					case "_quotationNo": return _quotationNo;
					case "_sNNo": return _sNNo;
					case "_productCode": return _productCode;
					case "_productDescription": return _productDescription;
					case "_quantity": return _quantity;
					case "_listPrice": return _listPrice;
					case "_minSellingPrice": return _minSellingPrice;
					case "_unitPrice": return _unitPrice;
					case "_cost": return _cost;
					case "_createdBy": return _createdBy;
					case "_createdDate": return _createdDate;
					case "_modifiedBy": return _modifiedBy;
					case "_modifiedDate": return _modifiedDate;
					case "_dSNNo": return _dSNNo;
					case "_revisionNo": return _revisionNo;
					case "_dOptSNNo": return _dOptSNNo;
					case "_uOM": return _uOM;
                    case "_recipeNo": return _recipeNo;
                    case "_productNotes": return _productNotes;
                    case "_batchSize": return _batchSize;
                    case "_tagNo": return _tagNo;
									
					default: throw new Exception(string.Format("Mapping: IObjectHelper Get is missing member case {0}", memberName));
				}
			}
			set {
				//handle null values
				if(value == null)
					return;
					
				switch (memberName) {
					case "_coyID": _coyID = (short)value; break;
					case "_quotationNo": _quotationNo = (string)value; break;
					case "_sNNo": _sNNo = (byte)value; break;
					case "_productCode": _productCode = (string)value; break;
					case "_productDescription": _productDescription = (string)value; break;
					case "_quantity": _quantity = (Nullable<decimal>)value; break;
					case "_listPrice": _listPrice = (Nullable<decimal>)value; break;
					case "_minSellingPrice": _minSellingPrice = (Nullable<decimal>)value; break;
					case "_unitPrice": _unitPrice = (Nullable<decimal>)value; break;
					case "_cost": _cost = (Nullable<decimal>)value; break;
					case "_createdBy": _createdBy = (short)value; break;
					case "_createdDate": _createdDate = (Nullable<DateTime>)value; break;
					case "_modifiedBy": _modifiedBy = (short)value; break;
					case "_modifiedDate": _modifiedDate = (Nullable<DateTime>)value; break;
					case "_dSNNo": _dSNNo = (Nullable<byte>)value; break;
					case "_revisionNo": _revisionNo = (byte)value; break;
					case "_dOptSNNo": _dOptSNNo = (string)value; break;
					case "_uOM": _uOM = (string)value; break;
                    case "_recipeNo": _recipeNo = (string)value; break;
                    case "_productNotes": _productNotes = (string)value; break;
                    case "_batchSize": _batchSize = (int)value; break;
                    case "_tagNo": _tagNo = (string)value; break;
				
					default: throw new Exception(string.Format("Mapping: IObjectHelper Set is missing member case {0}", memberName));
				}
			}
		}
		#endregion
		
		#region ToString
		///<summary>
		///Overwrites the base ToString method. This is used for AuditTrail purposes.
		///</summary>
		public override string ToString()
		{
			System.Text.StringBuilder stb = new System.Text.StringBuilder(500);
			
			stb.AppendFormat("_coyID={0}\n,", _coyID.ToString() );
			stb.AppendFormat("_quotationNo={0}\n,", _quotationNo.ToString() );
			stb.AppendFormat("_sNNo={0}\n,", _sNNo.ToString() );
			stb.AppendFormat("_productCode={0}\n,", _productCode.ToString() );
			stb.AppendFormat("_productDescription={0}\n,", _productDescription.ToString() );
			stb.AppendFormat("_quantity={0}\n,", _quantity.ToString() );
			stb.AppendFormat("_listPrice={0}\n,", _listPrice.ToString() );
			stb.AppendFormat("_minSellingPrice={0}\n,", _minSellingPrice.ToString() );
			stb.AppendFormat("_unitPrice={0}\n,", _unitPrice.ToString() );
			stb.AppendFormat("_cost={0}\n,", _cost.ToString() );
			stb.AppendFormat("_createdBy={0}\n,", _createdBy.ToString() );
			stb.AppendFormat("_createdDate={0}\n,", _createdDate.ToString() );
			stb.AppendFormat("_modifiedBy={0}\n,", _modifiedBy.ToString() );
			stb.AppendFormat("_modifiedDate={0}\n,", _modifiedDate.ToString() );
			stb.AppendFormat("_dSNNo={0}\n,", _dSNNo.ToString() );
			stb.AppendFormat("_revisionNo={0}\n,", _revisionNo.ToString() );
			stb.AppendFormat("_dOptSNNo={0}\n,", _dOptSNNo.ToString() );
			stb.AppendFormat("_uOM={0}\n,", _uOM.ToString() );
            stb.AppendFormat("_recipeNo={0}\n,", _recipeNo.ToString());
            stb.AppendFormat("_productNotes={0}\n,", _productNotes.ToString());
            stb.AppendFormat("_batchSize={0}\n,", _batchSize.ToString());
            stb.AppendFormat("_tagNo={0}\n,", _tagNo.ToString());
							
			
			return stb.ToString();
		}
		#endregion

	}
}
