//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//	   DO NOT MODIFY contents of this file. Changes to this
//	   file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using Wilson.ORMapper;
using GMSCore;

namespace GMSCore.Entity
{
	///<summary>Database mapping to table tbSalesPerson</summary>
	[DataObject(true)]
    public partial class SalesPerson : PersistBase<SalesPerson>, IObjectHelper
	{
		#region Properties
	
		private short _coyID;
		///<summary>Database mapping to column tbSalesPerson.CoyID</summary>
		[DataObjectField(true, false)]
		public short CoyID
		{
			get { return _coyID; }
			set
			{
				if (_coyID != value)
				{
					_coyID = value;
					OnPropertyChanged("CoyID");
				}
			}
		}
			
		private string _salesPersonID;
		///<summary>Database mapping to column tbSalesPerson.SalesPersonID</summary>
		[DataObjectField(true, false)]
		public string SalesPersonID
		{
			get { return _salesPersonID; }
			set
			{
				if (_salesPersonID != value)
				{
					_salesPersonID = value;
					OnPropertyChanged("SalesPersonID");
				}
			}
		}
			
		private string _salesPersonName = "";
		///<summary>Database mapping to column tbSalesPerson.SalesPersonName</summary>
		public string SalesPersonName
		{
			get { return _salesPersonName; }
			set
			{
				if (_salesPersonName != value)
				{
					_salesPersonName = value;
					OnPropertyChanged("SalesPersonName");
				}
			}
		}
			
		private short _createdBy = 0;
		///<summary>Database mapping to column tbSalesPerson.CreatedBy</summary>
		public short CreatedBy
		{
			get { return _createdBy; }
			set
			{
				if (_createdBy != value)
				{
					_createdBy = value;
					OnPropertyChanged("CreatedBy");
				}
			}
		}
			
		private DateTime _createdDate = DateTime.Parse("01/01/1900 00:00:00");
		///<summary>Database mapping to column tbSalesPerson.CreatedDate</summary>
		public DateTime CreatedDate
		{
			get { return _createdDate; }
			set
			{
				if (_createdDate != value)
				{
					_createdDate = value;
					OnPropertyChanged("CreatedDate");
				}
			}
		}
			
		private string _designation = "";
		///<summary>Database mapping to column tbSalesPerson.Designation</summary>
		public string Designation
		{
			get { return _designation; }
			set
			{
				if (_designation != value)
				{
					_designation = value;
					OnPropertyChanged("Designation");
				}
			}
		}
			
		private string _mobilePhone = "";
		///<summary>Database mapping to column tbSalesPerson.MobilePhone</summary>
		public string MobilePhone
		{
			get { return _mobilePhone; }
			set
			{
				if (_mobilePhone != value)
				{
					_mobilePhone = value;
					OnPropertyChanged("MobilePhone");
				}
			}
		}
			
		private string _dID = "";
		///<summary>Database mapping to column tbSalesPerson.DID</summary>
		public string DID
		{
			get { return _dID; }
			set
			{
				if (_dID != value)
				{
					_dID = value;
					OnPropertyChanged("DID");
				}
			}
		}
			
		private string _fax = "";
		///<summary>Database mapping to column tbSalesPerson.Fax</summary>
		public string Fax
		{
			get { return _fax; }
			set
			{
				if (_fax != value)
				{
					_fax = value;
					OnPropertyChanged("Fax");
				}
			}
		}
			
		private string _email = "";
		///<summary>Database mapping to column tbSalesPerson.Email</summary>
		public string Email
		{
			get { return _email; }
			set
			{
				if (_email != value)
				{
					_email = value;
					OnPropertyChanged("Email");
				}
			}
		}
			
		private short _approvedUserID = 0;
		///<summary>Database mapping to column tbSalesPerson.ApprovedUserID</summary>
		public short ApprovedUserID
		{
			get { return _approvedUserID; }
			set
			{
				if (_approvedUserID != value)
				{
					_approvedUserID = value;
					OnPropertyChanged("ApprovedUserID");
				}
			}
		}

        ///<summary>Customize for salesperson mapping display</summary>
        public string SalesPersonNameNID
        {
            get { return this._salesPersonID + "-" + this._salesPersonName; }
            set
            {
                SalesPersonNameNID = value;
            }
        }

        private string salesIDName = "";
        ///<summary>Created for display purpose</summary>
        public string SalesIDName
        {
            get { return SalesPersonName + " - " + SalesPersonID; }
            set
            {
                if (salesIDName != value)
                {
                    salesIDName = value;
                }
            }
        }

        private short _dim1 = 0;
        ///<summary>Database mapping to column tbSalesPerson.ApprovedUserID</summary>
        public short Dim1
        {
            get { return _dim1; }
            set
            {
                if (_dim1 != value)
                {
                    _dim1 = value;
                    OnPropertyChanged("Dim1");
                }
            }
        }

        private short _dim2 = 0;
        ///<summary>Database mapping to column tbSalesPerson.ApprovedUserID</summary>
        public short Dim2
        {
            get { return _dim2; }
            set
            {
                if (_dim2 != value)
                {
                    _dim2 = value;
                    OnPropertyChanged("Dim2");
                }
            }
        }

        private short _dim3 = 0;
        ///<summary>Database mapping to column tbSalesPerson.ApprovedUserID</summary>
        public short Dim3
        {
            get { return _dim3; }
            set
            {
                if (_dim3 != value)
                {
                    _dim3 = value;
                    OnPropertyChanged("Dim3");
                }
            }
        }

        private short _dim4 = 0;
        ///<summary>Database mapping to column tbSalesPerson.ApprovedUserID</summary>
        public short Dim4
        {
            get { return _dim4; }
            set
            {
                if (_dim4 != value)
                {
                    _dim4 = value;
                    OnPropertyChanged("Dim4");
                }
            }
        }

        private string _shortName = "";
        public string ShortName
        {
            get { return _shortName; }
            set
            {
                if (_shortName != value)
                {
                    _shortName = value;
                    OnPropertyChanged("ShortName");
                }
            }
        }

        private bool _isBudget = false;
        ///<summary>Database mapping to column tbProductGroup.IsBudget</summary>
        public bool IsBudget
        {
            get { return _isBudget; }
            set
            {
                if (_isBudget != value)
                {
                    _isBudget = value;
                    OnPropertyChanged("IsBudget");
                }
            }
        }
        #endregion

        ///<summary>Initializes a new instance of this class</summary>
        public SalesPerson() : base()
		{
			// Default Constructor
		}
		
		///<summary>Retrieve an instance of this class using its ID from the persistence store</summary>
		[DataObjectMethod(DataObjectMethodType.Select)]
        public static SalesPerson RetrieveByKey(short coyID, string salesPersonID)
		{
			DBManager db = DBManager.GetInstance();
			QueryHelper helper = db.Engine.QueryHelper;
			string where = helper.GetExpression("SalesPerson.CoyID", coyID);
			where += " and ";
			where += helper.GetExpression("SalesPerson.SalesPersonID", salesPersonID);

			return RetrieveFirst(where);			
		}
		
		///<summary>Delete instance from the persistence store based on primary key(s)</summary>
		[DataObjectMethod(DataObjectMethodType.Delete)]
        public static int DeleteByKey(short coyID, string salesPersonID)
		{			
			DBManager db = DBManager.GetInstance();		
			QueryHelper helper = db.Engine.QueryHelper;
			string where = helper.GetExpression("SalesPerson.CoyID", coyID);
			where += " and ";
			where += helper.GetExpression("SalesPerson.SalesPersonID", salesPersonID);
			
			return Delete(where);
		}
		
		///<summary>Delete instance from the persistence store based on primary key(s) using a transaction</summary>
		///<param name="transaction">An instance of a Wilson.ORMapper.Transaction to perform operation with.</param>
		public static int DeleteByKey(Wilson.ORMapper.Transaction transaction, short coyID, string salesPersonID)
		{			
			DBManager db = DBManager.GetInstance();
			QueryHelper helper = db.Engine.QueryHelper;
			string where = helper.GetExpression("SalesPerson.CoyID", coyID);
			where += " and ";
			where += helper.GetExpression("SalesPerson.SalesPersonID", salesPersonID);
			
			return Delete(transaction, where);
		}		
		#region IObjectHelper
		/// <summary>Indexer to update local member variables</summary>	
		/// <remarks>This indexer is used by the Wilson ORMapper</remarks>
		object IObjectHelper.this[string memberName]
		{
			get {
				switch (memberName) {
					case "_coyID": return _coyID;
					case "_salesPersonID": return _salesPersonID;
					case "_salesPersonName": return _salesPersonName;
					case "_createdBy": return _createdBy;
					case "_createdDate": return _createdDate;
					case "_designation": return _designation;
					case "_mobilePhone": return _mobilePhone;
					case "_dID": return _dID;
					case "_fax": return _fax;
					case "_email": return _email;
					case "_approvedUserID": return _approvedUserID;
                    case "_dim1": return _dim1;
                    case "_dim2": return _dim2;
                    case "_dim3": return _dim3;
                    case "_dim4": return _dim4;
                    case "_shortName": return _shortName;
                    case "_isBudget": return _isBudget;

                    default: throw new Exception(string.Format("Mapping: IObjectHelper Get is missing member case {0}", memberName));
				}
			}
			set {
				//handle null values
				if(value == null)
					return;
					
				switch (memberName) {
					case "_coyID": _coyID = (short)value; break;
					case "_salesPersonID": _salesPersonID = (string)value; break;
					case "_salesPersonName": _salesPersonName = (string)value; break;
					case "_createdBy": _createdBy = (short)value; break;
					case "_createdDate": _createdDate = (DateTime)value; break;
					case "_designation": _designation = (string)value; break;
					case "_mobilePhone": _mobilePhone = (string)value; break;
					case "_dID": _dID = (string)value; break;
					case "_fax": _fax = (string)value; break;
					case "_email": _email = (string)value; break;
					case "_approvedUserID": _approvedUserID = (short)value; break;
                    case "_dim1": _dim1 = (short)value; break;
                    case "_dim2": _dim2 = (short)value; break;
                    case "_dim3": _dim3 = (short)value; break;
                    case "_dim4": _dim4 = (short)value; break;
                    case "_shortName": _shortName = (string)value; break;
                    case "_isBudget": _isBudget = (bool)value; break;
                    default: throw new Exception(string.Format("Mapping: IObjectHelper Set is missing member case {0}", memberName));
				}
			}
		}
		#endregion
		
		#region ToString
		///<summary>
		///Overwrites the base ToString method. This is used for AuditTrail purposes.
		///</summary>
		public override string ToString()
		{
			System.Text.StringBuilder stb = new System.Text.StringBuilder(500);
			
			stb.AppendFormat("_coyID={0}\n,", _coyID.ToString() );
			stb.AppendFormat("_salesPersonID={0}\n,", _salesPersonID.ToString() );
			stb.AppendFormat("_salesPersonName={0}\n,", _salesPersonName.ToString() );
			stb.AppendFormat("_createdBy={0}\n,", _createdBy.ToString() );
			stb.AppendFormat("_createdDate={0}\n,", _createdDate.ToString() );
			stb.AppendFormat("_designation={0}\n,", _designation.ToString() );
			stb.AppendFormat("_mobilePhone={0}\n,", _mobilePhone.ToString() );
			stb.AppendFormat("_dID={0}\n,", _dID.ToString() );
			stb.AppendFormat("_fax={0}\n,", _fax.ToString() );
			stb.AppendFormat("_email={0}\n,", _email.ToString() );
			stb.AppendFormat("_approvedUserID={0}\n,", _approvedUserID.ToString() );
            stb.AppendFormat("_dim1={0}\n,", _dim1.ToString());
            stb.AppendFormat("_dim2={0}\n,", _dim2.ToString());
            stb.AppendFormat("_dim3={0}\n,", _dim3.ToString());
            stb.AppendFormat("_dim4={0}\n,", _dim4.ToString());
            stb.AppendFormat("_shortName={0}\n,", _shortName.ToString());
            stb.AppendFormat("_isBudget={0}\n,", _isBudget.ToString());
            return stb.ToString();
		}
		#endregion

	}
}
