//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//	   DO NOT MODIFY contents of this file. Changes to this
//	   file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using Wilson.ORMapper;
using GMSCore;

namespace GMSCore.Entity
{
	///<summary>Database mapping to table tbStockBalance</summary>
	[DataObject(true)]
    public partial class StockBalance : PersistBase<StockBalance>, IObjectHelper
	{
		#region Properties
	
		private short _coyID;
		///<summary>Database mapping to column tbStockBalance.CoyID</summary>
		public short CoyID
		{
			get { return _coyID; }
			set
			{
				if (_coyID != value)
				{
					_coyID = value;
					OnPropertyChanged("CoyID");
				}
			}
		}
			
		private DateTime _trnDate;
		///<summary>Database mapping to column tbStockBalance.TrnDate</summary>
		public DateTime TrnDate
		{
			get { return _trnDate; }
			set
			{
				if (_trnDate != value)
				{
					_trnDate = value;
					OnPropertyChanged("TrnDate");
				}
			}
		}
			
		private string _productCode = "";
		///<summary>Database mapping to column tbStockBalance.ProductCode</summary>
		public string ProductCode
		{
			get { return _productCode; }
			set
			{
				if (_productCode != value)
				{
					_productCode = value;
					OnPropertyChanged("ProductCode");
				}
			}
		}
			
		private string _productGroupCode;
		///<summary>Database mapping to column tbStockBalance.ProductGroupCode</summary>
		public string ProductGroupCode
		{
			get { return _productGroupCode; }
			set
			{
				if (_productGroupCode != value)
				{
					_productGroupCode = value;
					OnPropertyChanged("ProductGroupCode");
				}
			}
		}
			
		private string _productGroupName;
		///<summary>Database mapping to column tbStockBalance.ProductGroupName</summary>
		public string ProductGroupName
		{
			get { return _productGroupName; }
			set
			{
				if (_productGroupName != value)
				{
					_productGroupName = value;
					OnPropertyChanged("ProductGroupName");
				}
			}
		}
			
		private double _balanceQty = 0;
		///<summary>Database mapping to column tbStockBalance.BalanceQty</summary>
		public double BalanceQty
		{
			get { return _balanceQty; }
			set
			{
				if (_balanceQty != value)
				{
					_balanceQty = value;
					OnPropertyChanged("BalanceQty");
				}
			}
		}
			
		private double _costWt = 0;
		///<summary>Database mapping to column tbStockBalance.CostWt</summary>
		public double CostWt
		{
			get { return _costWt; }
			set
			{
				if (_costWt != value)
				{
					_costWt = value;
					OnPropertyChanged("CostWt");
				}
			}
		}
		
		#endregion
		
		///<summary>Initializes a new instance of this class</summary>
		public StockBalance() : base()
		{
			// Default Constructor
		}
		
		#region IObjectHelper
		/// <summary>Indexer to update local member variables</summary>	
		/// <remarks>This indexer is used by the Wilson ORMapper</remarks>
		object IObjectHelper.this[string memberName]
		{
			get {
				switch (memberName) {
					case "_coyID": return _coyID;
					case "_trnDate": return _trnDate;
					case "_productCode": return _productCode;
					case "_productGroupCode": return _productGroupCode;
					case "_productGroupName": return _productGroupName;
					case "_balanceQty": return _balanceQty;
					case "_costWt": return _costWt;
									
					default: throw new Exception(string.Format("Mapping: IObjectHelper Get is missing member case {0}", memberName));
				}
			}
			set {
				//handle null values
				if(value == null)
					return;
					
				switch (memberName) {
					case "_coyID": _coyID = (short)value; break;
					case "_trnDate": _trnDate = (DateTime)value; break;
					case "_productCode": _productCode = (string)value; break;
					case "_productGroupCode": _productGroupCode = (string)value; break;
					case "_productGroupName": _productGroupName = (string)value; break;
					case "_balanceQty": _balanceQty = (double)value; break;
					case "_costWt": _costWt = (double)value; break;
				
					default: throw new Exception(string.Format("Mapping: IObjectHelper Set is missing member case {0}", memberName));
				}
			}
		}
		#endregion
		
		#region ToString
		///<summary>
		///Overwrites the base ToString method. This is used for AuditTrail purposes.
		///</summary>
		public override string ToString()
		{
			System.Text.StringBuilder stb = new System.Text.StringBuilder(500);
			
			stb.AppendFormat("_coyID={0}\n,", _coyID.ToString() );
			stb.AppendFormat("_trnDate={0}\n,", _trnDate.ToString() );
			stb.AppendFormat("_productCode={0}\n,", _productCode.ToString() );
			stb.AppendFormat("_productGroupCode={0}\n,", _productGroupCode.ToString() );
			stb.AppendFormat("_productGroupName={0}\n,", _productGroupName.ToString() );
			stb.AppendFormat("_balanceQty={0}\n,", _balanceQty.ToString() );
			stb.AppendFormat("_costWt={0}\n,", _costWt.ToString() );
							
			
			return stb.ToString();
		}
		#endregion

	}
}
