//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//	   DO NOT MODIFY contents of this file. Changes to this
//	   file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using Wilson.ORMapper;
using GMSCore;

namespace GMSCore.Entity
{
	///<summary>Database mapping to table tbTaxType</summary>
	[DataObject(true)]
    public partial class TaxType : PersistBase<TaxType>, IObjectHelper
	{
		#region Properties
	
		private short _coyID;
		///<summary>Database mapping to column tbTaxType.CoyID</summary>
		[DataObjectField(true, false)]
		public short CoyID
		{
			get { return _coyID; }
			set
			{
				if (_coyID != value)
				{
					_coyID = value;
					OnPropertyChanged("CoyID");
				}
			}
		}
			
		private string _taxTypeID;
		///<summary>Database mapping to column tbTaxType.TaxTypeID</summary>
		[DataObjectField(true, false)]
		public string TaxTypeID
		{
			get { return _taxTypeID; }
			set
			{
				if (_taxTypeID != value)
				{
					_taxTypeID = value;
					OnPropertyChanged("TaxTypeID");
				}
			}
		}
			
		private string _taxName = "";
		///<summary>Database mapping to column tbTaxType.TaxName</summary>
		public string TaxName
		{
			get { return _taxName; }
			set
			{
				if (_taxName != value)
				{
					_taxName = value;
					OnPropertyChanged("TaxName");
				}
			}
		}
			
		private Nullable<decimal> _taxRate;
		///<summary>Database mapping to column tbTaxType.TaxRate</summary>
		public Nullable<decimal> TaxRate
		{
			get { return _taxRate; }
			set
			{
				if (_taxRate != value)
				{
					_taxRate = value;
					OnPropertyChanged("TaxRate");
				}
			}
		}
			
		private short _createdBy = 0;
		///<summary>Database mapping to column tbTaxType.CreatedBy</summary>
		public short CreatedBy
		{
			get { return _createdBy; }
			set
			{
				if (_createdBy != value)
				{
					_createdBy = value;
					OnPropertyChanged("CreatedBy");
				}
			}
		}
			
		private Nullable<DateTime> _createdDate;
		///<summary>Database mapping to column tbTaxType.CreatedDate</summary>
		public Nullable<DateTime> CreatedDate
		{
			get { return _createdDate; }
			set
			{
				if (_createdDate != value)
				{
					_createdDate = value;
					OnPropertyChanged("CreatedDate");
				}
			}
		}
			
		private short _modifiedBy = 0;
		///<summary>Database mapping to column tbTaxType.ModifiedBy</summary>
		public short ModifiedBy
		{
			get { return _modifiedBy; }
			set
			{
				if (_modifiedBy != value)
				{
					_modifiedBy = value;
					OnPropertyChanged("ModifiedBy");
				}
			}
		}
			
		private Nullable<DateTime> _modifiedDate;
		///<summary>Database mapping to column tbTaxType.ModifiedDate</summary>
		public Nullable<DateTime> ModifiedDate
		{
			get { return _modifiedDate; }
			set
			{
				if (_modifiedDate != value)
				{
					_modifiedDate = value;
					OnPropertyChanged("ModifiedDate");
				}
			}
		}

        private Nullable<bool> _isCustomerSales;
        ///<summary>Database mapping to column tbQuotationHeader.IsCustomerSales</summary>
        public Nullable<bool> IsCustomerSales
        {
            get { return _isCustomerSales; }
            set
            {
                if (_isCustomerSales != value)
                {
                    _isCustomerSales = value;
                    OnPropertyChanged("IsCustomerSales");
                }
            }
        }

        #endregion

        ///<summary>Initializes a new instance of this class</summary>
        public TaxType() : base()
		{
			// Default Constructor
		}
		
		///<summary>Retrieve an instance of this class using its ID from the persistence store</summary>
		[DataObjectMethod(DataObjectMethodType.Select)]
        public static TaxType RetrieveByKey(short coyID, string taxTypeID)
		{
			DBManager db = DBManager.GetInstance();
			QueryHelper helper = db.Engine.QueryHelper;
			string where = helper.GetExpression("TaxType.CoyID", coyID);
			where += " and ";
			where += helper.GetExpression("TaxType.TaxTypeID", taxTypeID);

			return RetrieveFirst(where);			
		}
		
		///<summary>Delete instance from the persistence store based on primary key(s)</summary>
		[DataObjectMethod(DataObjectMethodType.Delete)]
        public static int DeleteByKey(short coyID, string taxTypeID)
		{			
			DBManager db = DBManager.GetInstance();		
			QueryHelper helper = db.Engine.QueryHelper;
			string where = helper.GetExpression("TaxType.CoyID", coyID);
			where += " and ";
			where += helper.GetExpression("TaxType.TaxTypeID", taxTypeID);
			
			return Delete(where);
		}
		
		///<summary>Delete instance from the persistence store based on primary key(s) using a transaction</summary>
		///<param name="transaction">An instance of a Wilson.ORMapper.Transaction to perform operation with.</param>
		public static int DeleteByKey(Wilson.ORMapper.Transaction transaction, short coyID, string taxTypeID)
		{			
			DBManager db = DBManager.GetInstance();
			QueryHelper helper = db.Engine.QueryHelper;
			string where = helper.GetExpression("TaxType.CoyID", coyID);
			where += " and ";
			where += helper.GetExpression("TaxType.TaxTypeID", taxTypeID);
			
			return Delete(transaction, where);
		}		
		#region IObjectHelper
		/// <summary>Indexer to update local member variables</summary>	
		/// <remarks>This indexer is used by the Wilson ORMapper</remarks>
		object IObjectHelper.this[string memberName]
		{
			get {
				switch (memberName) {
					case "_coyID": return _coyID;
					case "_taxTypeID": return _taxTypeID;
					case "_taxName": return _taxName;
					case "_taxRate": return _taxRate;
					case "_createdBy": return _createdBy;
					case "_createdDate": return _createdDate;
					case "_modifiedBy": return _modifiedBy;
					case "_modifiedDate": return _modifiedDate;
                    case "_isCustomerSales": return _isCustomerSales;

                    default: throw new Exception(string.Format("Mapping: IObjectHelper Get is missing member case {0}", memberName));
				}
			}
			set {
				//handle null values
				if(value == null)
					return;
					
				switch (memberName) {
					case "_coyID": _coyID = (short)value; break;
					case "_taxTypeID": _taxTypeID = (string)value; break;
					case "_taxName": _taxName = (string)value; break;
					case "_taxRate": _taxRate = (Nullable<decimal>)value; break;
					case "_createdBy": _createdBy = (short)value; break;
					case "_createdDate": _createdDate = (Nullable<DateTime>)value; break;
					case "_modifiedBy": _modifiedBy = (short)value; break;
					case "_modifiedDate": _modifiedDate = (Nullable<DateTime>)value; break;
                    case "_isCustomerSales": _isCustomerSales = (Nullable<bool>)value; break;

                    default: throw new Exception(string.Format("Mapping: IObjectHelper Set is missing member case {0}", memberName));
				}
			}
		}
		#endregion
		
		#region ToString
		///<summary>
		///Overwrites the base ToString method. This is used for AuditTrail purposes.
		///</summary>
		public override string ToString()
		{
			System.Text.StringBuilder stb = new System.Text.StringBuilder(500);
			
			stb.AppendFormat("_coyID={0}\n,", _coyID.ToString() );
			stb.AppendFormat("_taxTypeID={0}\n,", _taxTypeID.ToString() );
			stb.AppendFormat("_taxName={0}\n,", _taxName.ToString() );
			stb.AppendFormat("_taxRate={0}\n,", _taxRate.ToString() );
			stb.AppendFormat("_createdBy={0}\n,", _createdBy.ToString() );
			stb.AppendFormat("_createdDate={0}\n,", _createdDate.ToString() );
			stb.AppendFormat("_modifiedBy={0}\n,", _modifiedBy.ToString() );
			stb.AppendFormat("_modifiedDate={0}\n,", _modifiedDate.ToString() );
            stb.AppendFormat("_isCustomerSales={0}\n,", _isCustomerSales.ToString());

            return stb.ToString();
		}
		#endregion

	}
}
