//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//	   DO NOT MODIFY contents of this file. Changes to this
//	   file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel; 
using System.ComponentModel;
using Wilson.ORMapper;


namespace GMSCore.Entity
{
	///<summary>Database mapping to table tbVendor</summary>
	[DataObject(true)]
    public partial class Vendor : PersistBase<Vendor>, IObjectHelper
	{
        #region Properties

        private int _vendorID;
        ///<summary>Database mapping to column tbVendor.VendorID</summary>
        [DataObjectField(true, true)]
        public int VendorID
        {
            get { return _vendorID; }
        
        }

        private int _coyID;
        ///<summary>Database mapping to column tbVendor.FormID</summary>
        public int CoyID
		{
			get { return _coyID; }
			set
			{
				if (_coyID != value)
				{
					_coyID = value;
					OnPropertyChanged("CoyID");
				}
			}
		}
					
			
		private string _companyName;
        ///<summary>Database mapping to column tbVendor.CompanyName</summary>
        public string CompanyName
		{ 
			get { return _companyName; }
			set
			{
				if (_companyName != value)
				{
                    _companyName = value;
					OnPropertyChanged("CompanyName");
				}
			}
		}

        private string _email;
        ///<summary>Database mapping to column tbVendor.Email</summary>
        public string Email
        {
            get { return _email; }
            set
            {
                if (_email != value)
                {
                    _email = value;
                    OnPropertyChanged("Email");
                }
            }
        }


        #endregion

        ///<summary>Initializes a new instance of this class</summary>
        public Vendor() : base()
		{
			// Default Constructor
		}
		///<summary>Initializes a new instance of this class</summary>
		///<param name="startTracking">Set to true to begin ORMapper tracking on this instance</param>
		public Vendor(bool startTracking) : base(startTracking)
		{
			
		}
		
		///<summary>Retrieve an instance of this class using its ID from the persistence store</summary>
		[DataObjectMethod(DataObjectMethodType.Select)]
        public static Vendor RetrieveByKey(int vendorID)
		{
			DBManager db = DBManager.GetInstance();
			return db.Engine.GetObject<Vendor>(vendorID);
		}
		
		///<summary>Delete instance from the persistence store based on primary key(s)</summary>
		[DataObjectMethod(DataObjectMethodType.Delete)]
        public static int DeleteByKey(int vendorID)
		{			
			DBManager db = DBManager.GetInstance();		
			QueryHelper helper = db.Engine.QueryHelper;
			string where = helper.GetExpression("Vendor.VendorID", vendorID);
			
			return Delete(where);
		}
		
		///<summary>Delete instance from the persistence store based on primary key(s) using a transaction</summary>
		///<param name="transaction">An instance of a Wilson.ORMapper.Transaction to perform operation with.</param>
		public static int DeleteByKey(Wilson.ORMapper.Transaction transaction, int vendorID)
		{			
			DBManager db = DBManager.GetInstance();
			QueryHelper helper = db.Engine.QueryHelper;
			string where = helper.GetExpression("Vendor.VendorID", vendorID);
			
			return Delete(transaction, where);
		}		
		#region IObjectHelper
		/// <summary>Indexer to update local member variables</summary>	
		/// <remarks>This indexer is used by the Wilson ORMapper</remarks>
		object IObjectHelper.this[string memberName]
		{
			get {
				switch (memberName) {
                    case "_vendorID": return _vendorID;
                    case "_coyID": return _coyID;
					case "_companyName": return _companyName;
                    case "_email": return _email;

                    default: throw new Exception(string.Format("Mapping: IObjectHelper Get is missing member case {0}", memberName));
				}
			}
			set {
				//handle null values
				if(value == null)
					return;
					
				switch (memberName) {
                    case "_vendorID": _vendorID = (int)value; break;
                    case "_coyID": _coyID = (int)value; break;
					case "_companyName": _companyName = (string)value; break;
                    case "_email": _email = (string)value; break;

                    default: throw new Exception(string.Format("Mapping: IObjectHelper Set is missing member case {0}", memberName));
				}
			}
		}
		#endregion
		
		#region ToString
		///<summary>
		///Overwrites the base ToString method. This is used for AuditTrail purposes.
		///</summary>
		public override string ToString()
		{
			System.Text.StringBuilder stb = new System.Text.StringBuilder(500);
			
			stb.AppendFormat("_vendorID={0}\n,", _vendorID.ToString() );
			stb.AppendFormat("_coyID={0}\n,", _coyID.ToString() );
			stb.AppendFormat("_companyName={0}\n,", _companyName.ToString() );
            stb.AppendFormat("_email={0}\n,", _email.ToString());
    
            return stb.ToString();
		}
		#endregion

	}
}
