//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//	   DO NOT MODIFY contents of this file. Changes to this
//	   file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using Wilson.ORMapper;
using GMSCore;

namespace GMSCore.Entity
{
	///<summary>Database mapping to table vwModuleListing</summary>
	[DataObject(true)]
    public partial class VwModuleListing : RetrieveBase<VwModuleListing>, IObjectHelper
	{
		#region Properties
	
		private short _moduleID;
		///<summary>Database mapping to column vwModuleListing.ModuleID</summary>
		public short ModuleID
		{
			get { return _moduleID; }
			set { _moduleID = value; }
		}
			
		private short _moduleCategoryID;
		///<summary>Database mapping to column vwModuleListing.ModuleCategoryID</summary>
		public short ModuleCategoryID
		{
			get { return _moduleCategoryID; }
			set { _moduleCategoryID = value; }
		}
			
		private string _functionName;
		///<summary>Database mapping to column vwModuleListing.FunctionName</summary>
		public string FunctionName
		{
			get { return _functionName; }
			set { _functionName = value; }
		}
			
		private short _parentModuleID = 0;
		///<summary>Database mapping to column vwModuleListing.ParentModuleID</summary>
		public short ParentModuleID
		{
			get { return _parentModuleID; }
			set { _parentModuleID = value; }
		}
			
		private string _parentModuleName;
		///<summary>Database mapping to column vwModuleListing.ParentModuleName</summary>
		public string ParentModuleName
		{
			get { return _parentModuleName; }
			set { _parentModuleName = value; }
		}
			
		private short _seqID;
		///<summary>Database mapping to column vwModuleListing.SeqID</summary>
		public short SeqID
		{
			get { return _seqID; }
			set { _seqID = value; }
		}
		
		#endregion
		
		///<summary>Initializes a new instance of this class</summary>
		public VwModuleListing() : base()
		{
			// Default Constructor
		}
		
		#region IObjectHelper
		/// <summary>Indexer to update local member variables</summary>	
		/// <remarks>This indexer is used by the Wilson ORMapper</remarks>
		object IObjectHelper.this[string memberName]
		{
			get {
				switch (memberName) {
					case "_moduleID": return _moduleID;
					case "_moduleCategoryID": return _moduleCategoryID;
					case "_functionName": return _functionName;
					case "_parentModuleID": return _parentModuleID;
					case "_parentModuleName": return _parentModuleName;
					case "_seqID": return _seqID;
									
					default: throw new Exception(string.Format("Mapping: IObjectHelper Get is missing member case {0}", memberName));
				}
			}
			set {
				//handle null values
				if(value == null)
					return;
					
				switch (memberName) {
					case "_moduleID": _moduleID = (short)value; break;
					case "_moduleCategoryID": _moduleCategoryID = (short)value; break;
					case "_functionName": _functionName = (string)value; break;
					case "_parentModuleID": _parentModuleID = (short)value; break;
					case "_parentModuleName": _parentModuleName = (string)value; break;
					case "_seqID": _seqID = (short)value; break;
				
					default: throw new Exception(string.Format("Mapping: IObjectHelper Set is missing member case {0}", memberName));
				}
			}
		}
		#endregion
		
		#region ToString
		///<summary>
		///Overwrites the base ToString method. This is used for AuditTrail purposes.
		///</summary>
		public override string ToString()
		{
			System.Text.StringBuilder stb = new System.Text.StringBuilder(500);
			
			stb.AppendFormat("_moduleID={0}\n,", _moduleID.ToString() );
			stb.AppendFormat("_moduleCategoryID={0}\n,", _moduleCategoryID.ToString() );
			stb.AppendFormat("_functionName={0}\n,", _functionName.ToString() );
			stb.AppendFormat("_parentModuleID={0}\n,", _parentModuleID.ToString() );
			stb.AppendFormat("_parentModuleName={0}\n,", _parentModuleName.ToString() );
			stb.AppendFormat("_seqID={0}\n,", _seqID.ToString() );
							
			
			return stb.ToString();
		}
		#endregion

	}
}
