DELETE FROM tbFinanceItemSeq where Report = 'PNL'

INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('PNL',1,1,1081)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('PNL',2,2,1082)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('PNL',3,3,1083)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('PNL',4,4,1084)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('PNL',5,5,1085)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('PNL',6,6,1086)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('PNL',7,7,1087)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('PNL',8,8,1088)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('PNL',9,9,1126)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('PNL',10,10,1089)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('PNL',11,11,1090)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('PNL',12,12,1091)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('PNL',13,13,1092)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('PNL',14,14,1093)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('PNL',15,15,1094)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('PNL',16,16,1095)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('PNL',17,17,1096)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('PNL',18,18,1097)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('PNL',19,19,1098)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('PNL',20,20,1099)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('PNL',21,21,1100)

INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('PNL',22,22,1101)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('PNL',23,23,1102)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('PNL',24,24,1103)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('PNL',25,25,1104)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('PNL',26,26,1105)

INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('PNL',27,27,1106)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('PNL',28,28,1107)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('PNL',29,29,1108)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('PNL',30,30,1109)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('PNL',31,31,1110)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('PNL',32,32,1111)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('PNL',33,33,1376)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('PNL',34,34,1377)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('PNL',35,35,1112)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('PNL',36,36,1113)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('PNL',37,37,1114)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('PNL',38,38,1115)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('PNL',39,39,1585)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('PNL',40,40,1116)

INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('PNL',41,41,1117)

INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('PNL',42,42,1118)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('PNL',43,43,1119)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('PNL',44,44,1120)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('PNL',45,45,1121)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('PNL',46,46,1122)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('PNL',47,47,(SELECT TOP 1 ItemID FROM tbFinanceItem where ItemName = '(PNL)Derivatives Gain/(Loss)'))


INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('PNL',48,48,(SELECT TOP 1 ItemID FROM tbFinanceItem where ItemName = '(PNL)Forex Gain/(Loss)'))
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('PNL',49,49,1125)

INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('PNL',50,50,1127)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('PNL',51,51,1128)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('PNL',52,52,1129)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('PNL',53,53,1130)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('PNL',54,54,1131)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('PNL',55,55,1474)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('PNL',56,0,46)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('PNL',57,1,1135)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('PNL',58,2,1136)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('PNL',59,3,1137)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('PNL',60,4,50)

INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('PNL',61,5,1139)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('PNL',62,6,53)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('PNL',63,7,52)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('PNL',64,8,1140)
