DELETE FROM tbFinanceItemSeq where Report = 'MA'

INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MA',1,1,1283)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MA',2,2,1284)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MA',3,3,1285)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MA',4,4,1286)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MA',5,5,1287)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MA',6,6,1288)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MA',7,7,1289)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MA',8,8,1290)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MA',9,9,1291)

INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MA',10,10,1293)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MA',11,11,1294)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MA',12,12,1295)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MA',13,13,1296)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MA',14,14,1297)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MA',15,15,1298)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MA',16,16,1299)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MA',17,17,1300)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MA',18,18,1301)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MA',19,19,1302)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MA',20,20,1303)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MA',21,21,1304)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MA',22,22,1305)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MA',23,23,1306)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MA',24,24,1307)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MA',25,25,1308)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MA',26,26,1309)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MA',27,27,1310)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MA',28,28,1311)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MA',29,29,1312)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MA',30,30,(SELECT TOP 1 ItemID FROM tbFinanceItem where ItemName = '(MA)IL-QA Allocated Cost'))
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MA',31,31,(SELECT TOP 1 ItemID FROM tbFinanceItem where ItemName = '(MA)IL-PM Allocated Cost'))
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MA',32,32,1313)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MA',33,33,1314)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MA',34,34,1315)

INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MA',35,35,(SELECT TOP 1 ItemID FROM tbFinanceItem where ItemName = '(MA)Carriage/Transport/Storage'))
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MA',36,36,1317)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MA',37,37,1318)


INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MA',38,38,(SELECT TOP 1 ItemID FROM tbFinanceItem where ItemName = '(MA)Disposal of Slurge/Others'))


INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MA',39,39,(SELECT TOP 1 ItemID FROM tbFinanceItem where ItemName = '(MA)VO-QA Allocated Cost'))
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MA',40,40,(SELECT TOP 1 ItemID FROM tbFinanceItem where ItemName = '(MA)VO-PM Allocated Cost'))

INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MA',41,41,(SELECT TOP 1 ItemID FROM tbFinanceItem where ItemName = '(MA)Other Variable Overhead'))
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MA',42,42,(SELECT TOP 1 ItemID FROM tbFinanceItem where ItemName = '(MA)Total Variable Overhead'))
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MA',43,43,1324)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MA',44,44,1325)

INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MA',45,45,(SELECT TOP 1 ItemID FROM tbFinanceItem where ItemName = '(MA)Repair & Maintainance/Upkeep'))

INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MA',46,46,(SELECT TOP 1 ItemID FROM tbFinanceItem where ItemName = '(MA)Leasing of Mac & Equip/Vehicles/Cyl'))
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MA',47,47,1328)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MA',48,48,1329)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MA',49,49,1330)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MA',50,50,1331)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MA',51,51,(SELECT TOP 1 ItemID FROM tbFinanceItem where ItemName = '(MA)QA Allocated Cost'))
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MA',52,52,(SELECT TOP 1 ItemID FROM tbFinanceItem where ItemName = '(MA)PM Allocated Cost'))
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MA',53,53,1332)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MA',54,54,1333)
