DELETE FROM tbFinanceItemSeq where Report = 'BSD'

INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',1,1,562)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',2,2,563)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',3,3,564)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',4,4,565)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',5,5,566)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',6,6,567)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',7,7,568)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',8,8,569)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',9,9,570)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',10,10,571)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',11,11,572)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',12,12,573)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',13,13,574)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',14,14,575)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',15,15,576)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',16,16,(SELECT top 1 ItemID FROM tbFinanceItem where ItemName = '(BSD)Stocks Return'))
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',17,17,(SELECT top 1 ItemID FROM tbFinanceItem where ItemName = '(BSD)COGS Clearing Account'))
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',18,18,577)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',19,19,578)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',20,20,579)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',21,21,580)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',22,22,581)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',23,23,582)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',24,24,583)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',25,25,584)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',26,26,585)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',27,27,(SELECT top 1 ItemID FROM tbFinanceItem where ItemName = '(BSD)Due from Interco-Non-Trade Clearing'))
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',28,28,586)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',29,29,587)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',30,30,588)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',31,31,589)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',32,32,590)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',33,33,591)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',34,34,592)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',35,35,593)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',36,36,594)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',37,37,595)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',38,38,596)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',39,39,597)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',40,40,(SELECT top 1 ItemID FROM tbFinanceItem where ItemName = '(BSD)Due from Assoc-Non-Trade Clearing'))
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',41,41,598)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',42,42,599)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',43,43,600)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',44,44,601)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',45,45,(SELECT top 1 ItemID FROM tbFinanceItem where ItemName = '(BSD)Due from Rel-Non-Trade Clearing'))
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',46,46,602)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',47,47,603)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',48,48,604)
 
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',49,49,606)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',50,50,607)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',51,51,608)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',52,52,609)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',53,53,610)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',54,54,611)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',55,55,612)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',56,56,613)
 
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',57,57,615)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',58,58,616)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',59,59,617)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',60,60,(SELECT top 1 ItemID FROM tbFinanceItem where ItemName = '(BSD)Sundry Debtors'))
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',61,61,618)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',62,62,(SELECT top 1 ItemID FROM tbFinanceItem where ItemName = '(BSD)Suspense-HR'))
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',63,62,619)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',64,63,620)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',65,64,621)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',66,65,(SELECT top 1 ItemID FROM tbFinanceItem where ItemName = '(BSD)Prov for Impairment-Freehold Land'))
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',67,66,622)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',68,67,623)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',69,68,(SELECT top 1 ItemID FROM tbFinanceItem where ItemName = '(BSD)Prov for Impairment-Leasehold Land'))
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',70,69,624)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',71,70,625)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',72,71,(SELECT top 1 ItemID FROM tbFinanceItem where ItemName = '(BSD)Prov for Impairment-Land Rights'))
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',73,72,626)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',74,73,627)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',75,74,(SELECT top 1 ItemID FROM tbFinanceItem where ItemName = '(BSD)Prov for Impairment-Building'))
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',76,75,628)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',77,76,629)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',78,77,630)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',79,78,(SELECT top 1  ItemID FROM tbFinanceItem where ItemName = '(BSD)Prov for Impairment-Renovations'))
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',80,79,631)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',81,80,632)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',82,81,(SELECT top 1 ItemID FROM tbFinanceItem where ItemName = '(BSD)Prov for Impairment-Investment Property'))
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',83,82,633)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',84,83,634)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',85,84,635)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',86,85,636)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',87,86,637)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',88,87,(SELECT top 1 ItemID FROM tbFinanceItem where ItemName = '(BSD)Prov for Impairment-Machinery'))
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',89,88,638)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',90,89,639)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',91,90,(SELECT top 1 ItemID FROM tbFinanceItem where ItemName = '(BSD)Prov for Impairment-Equipment'))
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',92,91,640)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',93,92,641)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',94,93,(SELECT top 1 ItemID FROM tbFinanceItem where ItemName = '(BSD)Prov for Impairment-Rental Equipment'))
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',95,94,642)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',96,95,643)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',97,96,(SELECT top 1 ItemID FROM tbFinanceItem where ItemName = '(BSD)Prov for Impairment-Pipelines'))
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',98,97,644)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',99,98,645)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',100,99,(SELECT top 1 ItemID FROM tbFinanceItem where ItemName = '(BSD)Prov for Impairment-Storage Tanks'))
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',101,100,646)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',102,101,647)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',103,102,(SELECT top 1 ItemID FROM tbFinanceItem where ItemName = '(BSD)Prov for Impairment-ISO Tanks'))
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',104,103,648)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',105,104,649)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',106,105,1584)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',107,106,650)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',108,107,651)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',109,108,(SELECT top 1 ItemID FROM tbFinanceItem where ItemName = '(BSD)Prov for Impairment-Tools'))
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',110,109,652)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',111,110,653)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',112,111,(SELECT top 1 ItemID FROM tbFinanceItem where ItemName = '(BSD)Prov for Impairment-Dies & Moulds'))
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',113,112,654)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',114,113,655)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',115,114,(SELECT top 1 ItemID FROM tbFinanceItem where ItemName = '(BSD)Prov for Impairment-Spare Parts'))
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',116,115,656)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',117,116,657)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',118,117,(SELECT top 1 ItemID FROM tbFinanceItem where ItemName = '(BSD)Prov for Impairment-F&F'))
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',119,118,658)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',120,119,659)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',121,120,(SELECT top 1 ItemID FROM tbFinanceItem where ItemName = '(BSD)Prov for Impairment-Office Equip'))
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',122,121,660)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',123,122,661)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',124,123,(SELECT top 1 ItemID FROM tbFinanceItem where ItemName = '(BSD)Prov for Impairment-Computer'))
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',125,124,662)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',126,125,663)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',127,126,(SELECT top 1 ItemID FROM tbFinanceItem where ItemName = '(BSD)Prov for Impairment-Motor Vehicle'))
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',128,127,(SELECT top 1 ItemID FROM tbFinanceItem where ItemName = '(BSD)Fixed Assets Clearing Account'))
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',129,128,664)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',130,129,665)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',131,130,(SELECT top 1 ItemID FROM tbFinanceItem where ItemName = '(BSD)Prov for Impairment-Subsidiary '))
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',132,131,666)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',133,132,(SELECT top 1 ItemID FROM tbFinanceItem where ItemName = '(BSD)Prov for Impairment-JV Co'))
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',134,133,667)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',135,134,(SELECT top 1 ItemID FROM tbFinanceItem where ItemName = '(BSD)Prov for Impairment-Assoc Co'))
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',136,135,668)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',137,136,(SELECT top 1 ItemID FROM tbFinanceItem where ItemName = '(BSD)Prov for Impairment-Rel Co'))
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',138,137,669)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',139,138,(SELECT top 1ItemID FROM tbFinanceItem where ItemName = '(BSD)Prov for Impairment-Quoted Shares'))
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',140,139,670)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',141,140,(SELECT top 1 ItemID FROM tbFinanceItem where ItemName = '(BSD)Amort-Trade Name'))
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',142,141,671)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',143,142,(SELECT top 1 ItemID FROM tbFinanceItem where ItemName = '(BSD)Amort-Customer Relationship'))
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',144,143,672)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',145,144,(SELECT top 1 ItemID FROM tbFinanceItem where ItemName = '(BSD)Amort-Trademark & Patent'))
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',146,145,673)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',147,146,(SELECT top 1 ItemID FROM tbFinanceItem where ItemName = '(BSD)Amort-Product License'))
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',148,147,674)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',149,148,(SELECT top 1 ItemID FROM tbFinanceItem where ItemName = '(BSD)Amort-Club Membership'))
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',150,149,675)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',151,150,676)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',152,151,(SELECT top 1 ItemID FROM tbFinanceItem where ItemName = '(BSD)Prov for DD-Interco - Non Current'))
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',153,152,677)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',154,153,(SELECT top 1 ItemID FROM tbFinanceItem where ItemName = '(BSD)Prov for DD-JV/Assoc - Non Current'))
 
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',155,154,678)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',156,155,(SELECT top 1 ItemID FROM tbFinanceItem where ItemName = '(BSD)Prov for DD-Rel-Non Current'))
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',157,156,679)
 
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',158,158,(SELECT top 1 ItemID FROM tbFinanceItem where ItemName = '(BSD)Derivatives Asset - Non Current'))
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',159,159,681)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',160,160,682)
 
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',161,162,684)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',162,163,685)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',163,164,686)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',164,165,687)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',165,166,688)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',166,167,689)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',167,168,690)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',168,169,691)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',169,169,(SELECT top 1 ItemID FROM tbFinanceItem where ItemName = '(BSD)HP Int in Suspense'))
 
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',170,170,(SELECT top 1 ItemID FROM tbFinanceItem where ItemName = '(BSD)Trade Creditors'))
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',171,171,693)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',172,172,694)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',173,173,698)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',174,174,699)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',175,175,700)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',176,176,695)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',177,177,696)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',178,178,697)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',179,179,701)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',180,180,702)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',181,181,703)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',182,182,704)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',183,183,705)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',184,184,706)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',185,185,707)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',186,186,708)
 
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',187,187,710)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',188,188,711)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',189,189,712)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',190,190,713)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',191,191,714)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',192,192,715)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',193,193,716)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',194,194,717)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',195,195,718)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',196,196,719)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',197,197,720)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',198,198,721)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',199,199,722)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',200,200,723)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',201,201,724)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',202,202,725)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',203,203,1593)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',204,203,(SELECT top 1 ItemID FROM tbFinanceItem where ItemName = '(BSD)Overpayment For Bill Lost'))
 
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',205,205,727)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',206,206,728)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',207,207,729)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',208,208,730)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',209,209,731)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',210,210,732)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',211,211,733)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',212,212,734)
 
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',213,213,736)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',214,214,737)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',215,215,738)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',216,216,739)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',217,217,740)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',218,218,741)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',219,219,742)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',220,220,743)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',221,221,744)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',222,222,745)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',223,223,746)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',224,224,747)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',225,225,748)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',226,226,749)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',227,227,750)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',228,228,751)
 
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',229,229,(SELECT top 1 ItemID FROM tbFinanceItem where ItemName = '(BSD)Derivatives Liability'))
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',230,230,753)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',231,231,754)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',232,232,755)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',233,233,756)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',234,234,757)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',235,235,758)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',236,236,759)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',237,237,760)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',238,238,761)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',239,239,762)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',240,240,763)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',241,241,764)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',242,242,765)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',243,243,766)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',244,244,767)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',245,245,768)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',246,246,769)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',247,247,(SELECT top 1 ItemID FROM tbFinanceItem where ItemName = '(BSD)Dividend Declared'))
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',248,248,770)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',249,249,771)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',250,250,772)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('BSD',251,251,773)
