DELETE FROM tbFinanceItemSeq where Report = 'MAD'
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MAD',1,0,1141)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MAD',2,1,1142)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MAD',3,2,1143)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MAD',4,3,1144)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MAD',5,4,1145)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MAD',6,5,1146)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MAD',7,6,1147)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MAD',8,7,1148)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MAD',9,8,1149)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MAD',10,0,1150)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MAD',11,9,1151)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MAD',12,10,1152)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MAD',13,11,1153)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MAD',14,12,1154)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MAD',15,13,1155)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MAD',16,14,1156)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MAD',17,15,1157)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MAD',18,16,1158)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MAD',19,17,1159)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MAD',20,18,1160)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MAD',21,19,1161)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MAD',22,20,1162)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MAD',23,21,1163)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MAD',24,22,1164)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MAD',25,23,1165)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MAD',26,24,1166)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MAD',27,25,1167)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MAD',28,26,1168)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MAD',29,27,1169)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MAD',30,28,1170)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MAD',31,29,1171)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MAD',32,30,1172)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MAD',33,31,1173)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MAD',34,32,1174)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MAD',35,33,1175)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MAD',36,34,1176)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MAD',37,35,1177)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MAD',38,36,1178)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MAD',39,37,(SELECT ItemID FROM tbFinanceItem where ItemName = '(MAD)Direct Exps-Others'))
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MAD',40,38,1179)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MAD',41,39,1180)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MAD',42,0,1181)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MAD',43,40,1182)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MAD',44,41,1183)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MAD',45,42,1184)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MAD',46,43,1185)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MAD',47,44,1186)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MAD',48,45,1187)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MAD',49,46,1188)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MAD',50,47,1189)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MAD',51,48,1190)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MAD',52,49,1191)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MAD',53,50,1192)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MAD',54,51,1193)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MAD',55,52,1194)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MAD',56,53,1195)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MAD',57,54,1196)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MAD',58,55,1197)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MAD',59,56,1198)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MAD',60,57,1199)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MAD',61,58,1200)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MAD',62,59,1201)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MAD',63,60,1202)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MAD',64,61,1203)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MAD',65,62,1204)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MAD',66,63,1205)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MAD',67,64,1206)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MAD',68,65,1207)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MAD',69,66,(SELECT ItemID FROM tbFinanceItem where ItemName = '(MAD)IL-QA Allocated Cost'))
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MAD',70,67,(SELECT ItemID FROM tbFinanceItem where ItemName = '(MAD)IL-PM Allocated Cost'))
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MAD',71,68,1208)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MAD',72,69,1209)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MAD',73,70,1210)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MAD',74,71,1211)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MAD',75,72,1212)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MAD',76,73,1213)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MAD',77,74,1214)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MAD',78,75,1215)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MAD',79,76,1216)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MAD',80,77,1217)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MAD',81,78,1218)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MAD',82,79,1219)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MAD',83,80,1220)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MAD',84,81,1221)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MAD',85,82,1222)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MAD',86,83,1223)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MAD',87,84,1224)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MAD',88,85,1225)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MAD',89,86,1226)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MAD',90,87,(SELECT ItemID FROM tbFinanceItem where ItemName = '(MAD)VO-QA Allocated Cost'))
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MAD',91,88,(SELECT ItemID FROM tbFinanceItem where ItemName = '(MAD)VO-PM Allocated Cost'))
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MAD',92,89,(SELECT ItemID FROM tbFinanceItem where ItemName = '(MAD)Other Variable Overhead'))
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MAD',93,90,1227)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MAD',94,91,1228)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MAD',95,92,1229)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MAD',96,93,1230)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MAD',97,94,1231)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MAD',98,95,1232)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MAD',99,96,(SELECT ItemID FROM tbFinanceItem where ItemName = '(MAD)R&M-Factory'))
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MAD',100,97,1233)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MAD',101,98,1234)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MAD',102,99,1235)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MAD',103,100,1236)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MAD',104,101,1237)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MAD',105,102,1238)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MAD',106,103,1239)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MAD',107,104,1240)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MAD',108,105,1241)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MAD',109,106,1242)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MAD',110,107,1243)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MAD',111,108,1244)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MAD',112,109,1245)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MAD',113,110,(SELECT ItemID FROM tbFinanceItem where ItemName = '(MAD)Upkeep-Plant'))
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MAD',114,111,(SELECT ItemID FROM tbFinanceItem where ItemName = '(MAD)Upkeep-Machinery'))
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MAD',115,112,(SELECT ItemID FROM tbFinanceItem where ItemName = '(MAD)Upkeep-Equipment'))
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MAD',116,113,(SELECT ItemID FROM tbFinanceItem where ItemName = '(MAD)Upkeep-Racks & Cylinders'))
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MAD',117,114,(SELECT ItemID FROM tbFinanceItem where ItemName = '(MAD)Upkeep-Furniture & Fitting'))
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MAD',118,115,(SELECT ItemID FROM tbFinanceItem where ItemName = '(MAD)Upkeep-Office Equip'))
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MAD',119,116,(SELECT ItemID FROM tbFinanceItem where ItemName = '(MAD)Upkeep-Computers'))
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MAD',120,117,1246)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MAD',121,118,1247)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MAD',122,119,1248)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MAD',123,120,1249)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MAD',124,121,1250)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MAD',125,122,1251)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MAD',126,123,1252)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MAD',127,124,1253)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MAD',128,125,1254)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MAD',129,126,1255)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MAD',130,127,1256)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MAD',131,128,1257)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MAD',132,129,1258)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MAD',133,130,1259)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MAD',134,131,1260)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MAD',135,132,1261)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MAD',136,133,1262)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MAD',137,134,1263)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MAD',138,135,1264)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MAD',139,136,1265)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MAD',140,137,1266)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MAD',141,138,1267)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MAD',142,139,1268)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MAD',143,140,1269)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MAD',144,141,1270)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MAD',145,142,1271)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MAD',146,143,1272)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MAD',147,144,1273)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MAD',148,145,1274)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MAD',149,146,1275)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MAD',150,147,1276)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MAD',151,148,(SELECT ItemID FROM tbFinanceItem where ItemName = '(MAD)QA Allocated Cost'))
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MAD',152,149,(SELECT ItemID FROM tbFinanceItem where ItemName = '(MAD)PM Allocated Cost'))
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MAD',153,150,1277)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MAD',154,151,1278)
INSERT INTO tbFinanceItemSeq(Report,ItemSeqID,ItemSN,ItemID) VALUES('MAD',155,152,1279)
