//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.832
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GMSWeb.Organization.Upload {
    
    public partial class UploadSpecial {
        protected System.Web.UI.HtmlControls.HtmlHead Head1;
        protected System.Web.UI.HtmlControls.HtmlForm form1;
        protected Microsoft.Web.UI.ScriptManager scriptMgr;
        protected System.Web.UI.WebControls.Label lblParameter;
        protected System.Web.UI.WebControls.DropDownList ddlCompanyParameter;
        protected System.Web.UI.HtmlControls.HtmlGenericControl Resultslbl;
        protected System.Web.UI.WebControls.Label lblTotalRecordsFound;
        protected Microsoft.Web.UI.UpdatePanel udpSpecialDataUpdater;
        protected System.Web.UI.WebControls.DataGrid dgSpecialData;
        protected System.Web.UI.HtmlControls.HtmlGenericControl Pageslbl;
        protected System.Web.UI.WebControls.LinkButton lnkFirst;
        protected System.Web.UI.WebControls.LinkButton lnkPrev;
        protected System.Web.UI.WebControls.Label lblPage;
        protected System.Web.UI.WebControls.LinkButton lnkNext;
        protected System.Web.UI.WebControls.LinkButton lnkLast;
        protected Microsoft.Web.UI.UpdatePanel udpMsgUpdater;
        protected GMSWeb.CustomCtrl.MessagePanelControl PageMsgPanel;
    }
}
