//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.832
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GMSWeb.Admin.SystemData {
    
    public partial class ItemStructureListing {
        protected System.Web.UI.HtmlControls.HtmlHead Head1;
        protected System.Web.UI.HtmlControls.HtmlForm form1;
        protected Microsoft.Web.UI.ScriptManager scriptMgr;
        protected System.Web.UI.WebControls.Label lblPurpose;
        protected System.Web.UI.WebControls.DropDownList ddlPurpose;
        protected Microsoft.Web.UI.UpdatePanel udpItemStructureUpdater;
        protected System.Web.UI.WebControls.DataGrid dgItemStructure;
        protected Microsoft.Web.UI.UpdatePanel udpMsgUpdater;
        protected GMSWeb.CustomCtrl.MessagePanelControl PageMsgPanel;
    }
}
