//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//	   DO NOT MODIFY contents of this file. Changes to this
//	   file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using Wilson.ORMapper;
using eLogixCore;

namespace GMSCore.Entity
{
	///<summary>Database mapping to table A21IMTransactionDetail</summary>
	[DataObject(true)]
    public partial class A21IMTransactionDetail : PersistBase<A21IMTransactionDetail>, IObjectHelper
	{
		#region Properties
	
		private string _company;
		///<summary>Database mapping to column A21IMTransactionDetail.Company</summary>
		public string Company
		{
			get { return _company; }
			set
			{
				if (_company != value)
				{
					_company = value;
					OnPropertyChanged("Company");
				}
			}
		}
			
		private string _trnType;
		///<summary>Database mapping to column A21IMTransactionDetail.TrnType</summary>
		public string TrnType
		{
			get { return _trnType; }
			set
			{
				if (_trnType != value)
				{
					_trnType = value;
					OnPropertyChanged("TrnType");
				}
			}
		}
			
		private int _trnNo;
		///<summary>Database mapping to column A21IMTransactionDetail.TrnNo</summary>
		public int TrnNo
		{
			get { return _trnNo; }
			set
			{
				if (_trnNo != value)
				{
					_trnNo = value;
					OnPropertyChanged("TrnNo");
				}
			}
		}
			
		private string _product;
		///<summary>Database mapping to column A21IMTransactionDetail.Product</summary>
		public string Product
		{
			get { return _product; }
			set
			{
				if (_product != value)
				{
					_product = value;
					OnPropertyChanged("Product");
				}
			}
		}
			
		private string _warehouse;
		///<summary>Database mapping to column A21IMTransactionDetail.Warehouse</summary>
		public string Warehouse
		{
			get { return _warehouse; }
			set
			{
				if (_warehouse != value)
				{
					_warehouse = value;
					OnPropertyChanged("Warehouse");
				}
			}
		}
			
		private double _issueQuantity = 0;
		///<summary>Database mapping to column A21IMTransactionDetail.IssueQuantity</summary>
		public double IssueQuantity
		{
			get { return _issueQuantity; }
			set
			{
				if (_issueQuantity != value)
				{
					_issueQuantity = value;
					OnPropertyChanged("IssueQuantity");
				}
			}
		}
			
		private double _cost = 0;
		///<summary>Database mapping to column A21IMTransactionDetail.Cost</summary>
		public double Cost
		{
			get { return _cost; }
			set
			{
				if (_cost != value)
				{
					_cost = value;
					OnPropertyChanged("Cost");
				}
			}
		}
			
		private double _receiptQuantity = 0;
		///<summary>Database mapping to column A21IMTransactionDetail.ReceiptQuantity</summary>
		public double ReceiptQuantity
		{
			get { return _receiptQuantity; }
			set
			{
				if (_receiptQuantity != value)
				{
					_receiptQuantity = value;
					OnPropertyChanged("ReceiptQuantity");
				}
			}
		}
			
		private double _rate = 0;
		///<summary>Database mapping to column A21IMTransactionDetail.Rate</summary>
		public double Rate
		{
			get { return _rate; }
			set
			{
				if (_rate != value)
				{
					_rate = value;
					OnPropertyChanged("Rate");
				}
			}
		}
			
		private string _stockUnit = "";
		///<summary>Database mapping to column A21IMTransactionDetail.StockUnit</summary>
		public string StockUnit
		{
			get { return _stockUnit; }
			set
			{
				if (_stockUnit != value)
				{
					_stockUnit = value;
					OnPropertyChanged("StockUnit");
				}
			}
		}
			
		private double _costWt = 0;
		///<summary>Database mapping to column A21IMTransactionDetail.CostWt</summary>
		public double CostWt
		{
			get { return _costWt; }
			set
			{
				if (_costWt != value)
				{
					_costWt = value;
					OnPropertyChanged("CostWt");
				}
			}
		}
			
		private double _costFIFO = 0;
		///<summary>Database mapping to column A21IMTransactionDetail.CostFIFO</summary>
		public double CostFIFO
		{
			get { return _costFIFO; }
			set
			{
				if (_costFIFO != value)
				{
					_costFIFO = value;
					OnPropertyChanged("CostFIFO");
				}
			}
		}
			
		private double _costStd = 0;
		///<summary>Database mapping to column A21IMTransactionDetail.CostStd</summary>
		public double CostStd
		{
			get { return _costStd; }
			set
			{
				if (_costStd != value)
				{
					_costStd = value;
					OnPropertyChanged("CostStd");
				}
			}
		}
			
		private double _costOth = 0;
		///<summary>Database mapping to column A21IMTransactionDetail.CostOth</summary>
		public double CostOth
		{
			get { return _costOth; }
			set
			{
				if (_costOth != value)
				{
					_costOth = value;
					OnPropertyChanged("CostOth");
				}
			}
		}
			
		private double _issuedOut = 0;
		///<summary>Database mapping to column A21IMTransactionDetail.IssuedOut</summary>
		public double IssuedOut
		{
			get { return _issuedOut; }
			set
			{
				if (_issuedOut != value)
				{
					_issuedOut = value;
					OnPropertyChanged("IssuedOut");
				}
			}
		}
			
		private double _balQty = 0;
		///<summary>Database mapping to column A21IMTransactionDetail.BalQty</summary>
		public double BalQty
		{
			get { return _balQty; }
			set
			{
				if (_balQty != value)
				{
					_balQty = value;
					OnPropertyChanged("BalQty");
				}
			}
		}
			
		private string _clearFlag = "";
		///<summary>Database mapping to column A21IMTransactionDetail.ClearFlag</summary>
		public string ClearFlag
		{
			get { return _clearFlag; }
			set
			{
				if (_clearFlag != value)
				{
					_clearFlag = value;
					OnPropertyChanged("ClearFlag");
				}
			}
		}
			
		private double _returned = 0;
		///<summary>Database mapping to column A21IMTransactionDetail.Returned</summary>
		public double Returned
		{
			get { return _returned; }
			set
			{
				if (_returned != value)
				{
					_returned = value;
					OnPropertyChanged("Returned");
				}
			}
		}
			
		private double _assemblyUnitQty = 0;
		///<summary>Database mapping to column A21IMTransactionDetail.AssemblyUnitQty</summary>
		public double AssemblyUnitQty
		{
			get { return _assemblyUnitQty; }
			set
			{
				if (_assemblyUnitQty != value)
				{
					_assemblyUnitQty = value;
					OnPropertyChanged("AssemblyUnitQty");
				}
			}
		}
			
		private double _mfgCost = 0;
		///<summary>Database mapping to column A21IMTransactionDetail.MfgCost</summary>
		public double MfgCost
		{
			get { return _mfgCost; }
			set
			{
				if (_mfgCost != value)
				{
					_mfgCost = value;
					OnPropertyChanged("MfgCost");
				}
			}
		}
		
		#endregion
		
		///<summary>Initializes a new instance of this class</summary>
		public A21IMTransactionDetail() : base()
		{
			// Default Constructor
		}
		
		#region IObjectHelper
		/// <summary>Indexer to update local member variables</summary>	
		/// <remarks>This indexer is used by the Wilson ORMapper</remarks>
		object IObjectHelper.this[string memberName]
		{
			get {
				switch (memberName) {
					case "_company": return _company;
					case "_trnType": return _trnType;
					case "_trnNo": return _trnNo;
					case "_product": return _product;
					case "_warehouse": return _warehouse;
					case "_issueQuantity": return _issueQuantity;
					case "_cost": return _cost;
					case "_receiptQuantity": return _receiptQuantity;
					case "_rate": return _rate;
					case "_stockUnit": return _stockUnit;
					case "_costWt": return _costWt;
					case "_costFIFO": return _costFIFO;
					case "_costStd": return _costStd;
					case "_costOth": return _costOth;
					case "_issuedOut": return _issuedOut;
					case "_balQty": return _balQty;
					case "_clearFlag": return _clearFlag;
					case "_returned": return _returned;
					case "_assemblyUnitQty": return _assemblyUnitQty;
					case "_mfgCost": return _mfgCost;
									
					default: throw new Exception(string.Format("Mapping: IObjectHelper Get is missing member case {0}", memberName));
				}
			}
			set {
				//handle null values
				if(value == null)
					return;
					
				switch (memberName) {
					case "_company": _company = (string)value; break;
					case "_trnType": _trnType = (string)value; break;
					case "_trnNo": _trnNo = (int)value; break;
					case "_product": _product = (string)value; break;
					case "_warehouse": _warehouse = (string)value; break;
					case "_issueQuantity": _issueQuantity = (double)value; break;
					case "_cost": _cost = (double)value; break;
					case "_receiptQuantity": _receiptQuantity = (double)value; break;
					case "_rate": _rate = (double)value; break;
					case "_stockUnit": _stockUnit = (string)value; break;
					case "_costWt": _costWt = (double)value; break;
					case "_costFIFO": _costFIFO = (double)value; break;
					case "_costStd": _costStd = (double)value; break;
					case "_costOth": _costOth = (double)value; break;
					case "_issuedOut": _issuedOut = (double)value; break;
					case "_balQty": _balQty = (double)value; break;
					case "_clearFlag": _clearFlag = (string)value; break;
					case "_returned": _returned = (double)value; break;
					case "_assemblyUnitQty": _assemblyUnitQty = (double)value; break;
					case "_mfgCost": _mfgCost = (double)value; break;
				
					default: throw new Exception(string.Format("Mapping: IObjectHelper Set is missing member case {0}", memberName));
				}
			}
		}
		#endregion
		
		#region ToString
		///<summary>
		///Overwrites the base ToString method. This is used for AuditTrail purposes.
		///</summary>
		public override string ToString()
		{
			System.Text.StringBuilder stb = new System.Text.StringBuilder(500);
			
			stb.AppendFormat("_company={0}\n,", _company.ToString() );
			stb.AppendFormat("_trnType={0}\n,", _trnType.ToString() );
			stb.AppendFormat("_trnNo={0}\n,", _trnNo.ToString() );
			stb.AppendFormat("_product={0}\n,", _product.ToString() );
			stb.AppendFormat("_warehouse={0}\n,", _warehouse.ToString() );
			stb.AppendFormat("_issueQuantity={0}\n,", _issueQuantity.ToString() );
			stb.AppendFormat("_cost={0}\n,", _cost.ToString() );
			stb.AppendFormat("_receiptQuantity={0}\n,", _receiptQuantity.ToString() );
			stb.AppendFormat("_rate={0}\n,", _rate.ToString() );
			stb.AppendFormat("_stockUnit={0}\n,", _stockUnit.ToString() );
			stb.AppendFormat("_costWt={0}\n,", _costWt.ToString() );
			stb.AppendFormat("_costFIFO={0}\n,", _costFIFO.ToString() );
			stb.AppendFormat("_costStd={0}\n,", _costStd.ToString() );
			stb.AppendFormat("_costOth={0}\n,", _costOth.ToString() );
			stb.AppendFormat("_issuedOut={0}\n,", _issuedOut.ToString() );
			stb.AppendFormat("_balQty={0}\n,", _balQty.ToString() );
			stb.AppendFormat("_clearFlag={0}\n,", _clearFlag.ToString() );
			stb.AppendFormat("_returned={0}\n,", _returned.ToString() );
			stb.AppendFormat("_assemblyUnitQty={0}\n,", _assemblyUnitQty.ToString() );
			stb.AppendFormat("_mfgCost={0}\n,", _mfgCost.ToString() );
							
			
			return stb.ToString();
		}
		#endregion

	}
}
