//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//	   DO NOT MODIFY contents of this file. Changes to this
//	   file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using Wilson.ORMapper;
using eLogixCore;

namespace GMSCore.Entity
{
	///<summary>Database mapping to table A21OPOrderHeader</summary>
	[DataObject(true)]
    public partial class A21OPOrderHeader : PersistBase<A21OPOrderHeader>, IObjectHelper
	{
		#region Properties
	
		private string _company;
		///<summary>Database mapping to column A21OPOrderHeader.Company</summary>
		public string Company
		{
			get { return _company; }
			set
			{
				if (_company != value)
				{
					_company = value;
					OnPropertyChanged("Company");
				}
			}
		}
			
		private string _trnType;
		///<summary>Database mapping to column A21OPOrderHeader.TrnType</summary>
		public string TrnType
		{
			get { return _trnType; }
			set
			{
				if (_trnType != value)
				{
					_trnType = value;
					OnPropertyChanged("TrnType");
				}
			}
		}
			
		private int _trnNo;
		///<summary>Database mapping to column A21OPOrderHeader.TrnNo</summary>
		public int TrnNo
		{
			get { return _trnNo; }
			set
			{
				if (_trnNo != value)
				{
					_trnNo = value;
					OnPropertyChanged("TrnNo");
				}
			}
		}
			
		private string _code = "";
		///<summary>Database mapping to column A21OPOrderHeader.Code</summary>
		public string Code
		{
			get { return _code; }
			set
			{
				if (_code != value)
				{
					_code = value;
					OnPropertyChanged("Code");
				}
			}
		}
			
		private string _status = "";
		///<summary>Database mapping to column A21OPOrderHeader.Status</summary>
		public string Status
		{
			get { return _status; }
			set
			{
				if (_status != value)
				{
					_status = value;
					OnPropertyChanged("Status");
				}
			}
		}
			
		private string _currency = "";
		///<summary>Database mapping to column A21OPOrderHeader.Currency</summary>
		public string Currency
		{
			get { return _currency; }
			set
			{
				if (_currency != value)
				{
					_currency = value;
					OnPropertyChanged("Currency");
				}
			}
		}
			
		private DateTime _trnDate = DateTime.Parse("01/01/1900 00:00:00");
		///<summary>Database mapping to column A21OPOrderHeader.TrnDate</summary>
		public DateTime TrnDate
		{
			get { return _trnDate; }
			set
			{
				if (_trnDate != value)
				{
					_trnDate = value;
					OnPropertyChanged("TrnDate");
				}
			}
		}
			
		private DateTime _trnTime = DateTime.Parse("01/01/1900 00:00:00");
		///<summary>Database mapping to column A21OPOrderHeader.TrnTime</summary>
		public DateTime TrnTime
		{
			get { return _trnTime; }
			set
			{
				if (_trnTime != value)
				{
					_trnTime = value;
					OnPropertyChanged("TrnTime");
				}
			}
		}
			
		private short _year = 0;
		///<summary>Database mapping to column A21OPOrderHeader.Year</summary>
		public short Year
		{
			get { return _year; }
			set
			{
				if (_year != value)
				{
					_year = value;
					OnPropertyChanged("Year");
				}
			}
		}
			
		private byte _month = 0;
		///<summary>Database mapping to column A21OPOrderHeader.Month</summary>
		public byte Month
		{
			get { return _month; }
			set
			{
				if (_month != value)
				{
					_month = value;
					OnPropertyChanged("Month");
				}
			}
		}
			
		private byte _week = 0;
		///<summary>Database mapping to column A21OPOrderHeader.Week</summary>
		public byte Week
		{
			get { return _week; }
			set
			{
				if (_week != value)
				{
					_week = value;
					OnPropertyChanged("Week");
				}
			}
		}
			
		private double _exchangeRate = 0;
		///<summary>Database mapping to column A21OPOrderHeader.ExchangeRate</summary>
		public double ExchangeRate
		{
			get { return _exchangeRate; }
			set
			{
				if (_exchangeRate != value)
				{
					_exchangeRate = value;
					OnPropertyChanged("ExchangeRate");
				}
			}
		}
			
		private string _docNo = "";
		///<summary>Database mapping to column A21OPOrderHeader.DocNo</summary>
		public string DocNo
		{
			get { return _docNo; }
			set
			{
				if (_docNo != value)
				{
					_docNo = value;
					OnPropertyChanged("DocNo");
				}
			}
		}
			
		private string _narration = "";
		///<summary>Database mapping to column A21OPOrderHeader.Narration</summary>
		public string Narration
		{
			get { return _narration; }
			set
			{
				if (_narration != value)
				{
					_narration = value;
					OnPropertyChanged("Narration");
				}
			}
		}
			
		private string _trnScreen = "";
		///<summary>Database mapping to column A21OPOrderHeader.TrnScreen</summary>
		public string TrnScreen
		{
			get { return _trnScreen; }
			set
			{
				if (_trnScreen != value)
				{
					_trnScreen = value;
					OnPropertyChanged("TrnScreen");
				}
			}
		}
			
		private string _location = "";
		///<summary>Database mapping to column A21OPOrderHeader.Location</summary>
		public string Location
		{
			get { return _location; }
			set
			{
				if (_location != value)
				{
					_location = value;
					OnPropertyChanged("Location");
				}
			}
		}
			
		private string _dAdd1 = "";
		///<summary>Database mapping to column A21OPOrderHeader.DAdd1</summary>
		public string DAdd1
		{
			get { return _dAdd1; }
			set
			{
				if (_dAdd1 != value)
				{
					_dAdd1 = value;
					OnPropertyChanged("DAdd1");
				}
			}
		}
			
		private string _dAdd2 = "";
		///<summary>Database mapping to column A21OPOrderHeader.DAdd2</summary>
		public string DAdd2
		{
			get { return _dAdd2; }
			set
			{
				if (_dAdd2 != value)
				{
					_dAdd2 = value;
					OnPropertyChanged("DAdd2");
				}
			}
		}
			
		private string _dAdd3 = "";
		///<summary>Database mapping to column A21OPOrderHeader.DAdd3</summary>
		public string DAdd3
		{
			get { return _dAdd3; }
			set
			{
				if (_dAdd3 != value)
				{
					_dAdd3 = value;
					OnPropertyChanged("DAdd3");
				}
			}
		}
			
		private string _dAdd4 = "";
		///<summary>Database mapping to column A21OPOrderHeader.DAdd4</summary>
		public string DAdd4
		{
			get { return _dAdd4; }
			set
			{
				if (_dAdd4 != value)
				{
					_dAdd4 = value;
					OnPropertyChanged("DAdd4");
				}
			}
		}
			
		private bool _gSTInc;
		///<summary>Database mapping to column A21OPOrderHeader.GSTInc</summary>
		public bool GSTInc
		{
			get { return _gSTInc; }
			set
			{
				if (_gSTInc != value)
				{
					_gSTInc = value;
					OnPropertyChanged("GSTInc");
				}
			}
		}
			
		private string _gSTType = "";
		///<summary>Database mapping to column A21OPOrderHeader.GSTType</summary>
		public string GSTType
		{
			get { return _gSTType; }
			set
			{
				if (_gSTType != value)
				{
					_gSTType = value;
					OnPropertyChanged("GSTType");
				}
			}
		}
			
		private double _gST = 0;
		///<summary>Database mapping to column A21OPOrderHeader.GST</summary>
		public double GST
		{
			get { return _gST; }
			set
			{
				if (_gST != value)
				{
					_gST = value;
					OnPropertyChanged("GST");
				}
			}
		}
			
		private float _discount = 0;
		///<summary>Database mapping to column A21OPOrderHeader.Discount</summary>
		public float Discount
		{
			get { return _discount; }
			set
			{
				if (_discount != value)
				{
					_discount = value;
					OnPropertyChanged("Discount");
				}
			}
		}
			
		private DateTime _delDate = DateTime.Parse("01/01/1900 00:00:00");
		///<summary>Database mapping to column A21OPOrderHeader.DelDate</summary>
		public DateTime DelDate
		{
			get { return _delDate; }
			set
			{
				if (_delDate != value)
				{
					_delDate = value;
					OnPropertyChanged("DelDate");
				}
			}
		}
			
		private string _salesPerson = "";
		///<summary>Database mapping to column A21OPOrderHeader.SalesPerson</summary>
		public string SalesPerson
		{
			get { return _salesPerson; }
			set
			{
				if (_salesPerson != value)
				{
					_salesPerson = value;
					OnPropertyChanged("SalesPerson");
				}
			}
		}
			
		private string _project = "";
		///<summary>Database mapping to column A21OPOrderHeader.Project</summary>
		public string Project
		{
			get { return _project; }
			set
			{
				if (_project != value)
				{
					_project = value;
					OnPropertyChanged("Project");
				}
			}
		}
			
		private string _department = "";
		///<summary>Database mapping to column A21OPOrderHeader.Department</summary>
		public string Department
		{
			get { return _department; }
			set
			{
				if (_department != value)
				{
					_department = value;
					OnPropertyChanged("Department");
				}
			}
		}
			
		private string _section = "";
		///<summary>Database mapping to column A21OPOrderHeader.Section</summary>
		public string Section
		{
			get { return _section; }
			set
			{
				if (_section != value)
				{
					_section = value;
					OnPropertyChanged("Section");
				}
			}
		}
			
		private string _updUser = "";
		///<summary>Database mapping to column A21OPOrderHeader.UpdUser</summary>
		public string UpdUser
		{
			get { return _updUser; }
			set
			{
				if (_updUser != value)
				{
					_updUser = value;
					OnPropertyChanged("UpdUser");
				}
			}
		}
			
		private DateTime _updDate = DateTime.Parse("01/01/1900 00:00:00");
		///<summary>Database mapping to column A21OPOrderHeader.UpdDate</summary>
		public DateTime UpdDate
		{
			get { return _updDate; }
			set
			{
				if (_updDate != value)
				{
					_updDate = value;
					OnPropertyChanged("UpdDate");
				}
			}
		}
			
		private DateTime _updTime = DateTime.Parse("01/01/1900 00:00:00");
		///<summary>Database mapping to column A21OPOrderHeader.UpdTime</summary>
		public DateTime UpdTime
		{
			get { return _updTime; }
			set
			{
				if (_updTime != value)
				{
					_updTime = value;
					OnPropertyChanged("UpdTime");
				}
			}
		}
			
		private string _crtUser = "";
		///<summary>Database mapping to column A21OPOrderHeader.CrtUser</summary>
		public string CrtUser
		{
			get { return _crtUser; }
			set
			{
				if (_crtUser != value)
				{
					_crtUser = value;
					OnPropertyChanged("CrtUser");
				}
			}
		}
			
		private DateTime _crtDate = DateTime.Parse("01/01/1900 00:00:00");
		///<summary>Database mapping to column A21OPOrderHeader.CrtDate</summary>
		public DateTime CrtDate
		{
			get { return _crtDate; }
			set
			{
				if (_crtDate != value)
				{
					_crtDate = value;
					OnPropertyChanged("CrtDate");
				}
			}
		}
			
		private DateTime _crtTime = DateTime.Parse("01/01/1900 00:00:00");
		///<summary>Database mapping to column A21OPOrderHeader.CrtTime</summary>
		public DateTime CrtTime
		{
			get { return _crtTime; }
			set
			{
				if (_crtTime != value)
				{
					_crtTime = value;
					OnPropertyChanged("CrtTime");
				}
			}
		}
			
		private string _custPONumber = "";
		///<summary>Database mapping to column A21OPOrderHeader.CustPONumber</summary>
		public string CustPONumber
		{
			get { return _custPONumber; }
			set
			{
				if (_custPONumber != value)
				{
					_custPONumber = value;
					OnPropertyChanged("CustPONumber");
				}
			}
		}
			
		private double _billAmt = 0;
		///<summary>Database mapping to column A21OPOrderHeader.BillAmt</summary>
		public double BillAmt
		{
			get { return _billAmt; }
			set
			{
				if (_billAmt != value)
				{
					_billAmt = value;
					OnPropertyChanged("BillAmt");
				}
			}
		}
			
		private int _quotNo = 0;
		///<summary>Database mapping to column A21OPOrderHeader.QuotNo</summary>
		public int QuotNo
		{
			get { return _quotNo; }
			set
			{
				if (_quotNo != value)
				{
					_quotNo = value;
					OnPropertyChanged("QuotNo");
				}
			}
		}
			
		private string _orderrefer = "";
		///<summary>Database mapping to column A21OPOrderHeader.orderrefer</summary>
		public string Orderrefer
		{
			get { return _orderrefer; }
			set
			{
				if (_orderrefer != value)
				{
					_orderrefer = value;
					OnPropertyChanged("Orderrefer");
				}
			}
		}
			
		private string _type = "";
		///<summary>Database mapping to column A21OPOrderHeader.type</summary>
		public string Type
		{
			get { return _type; }
			set
			{
				if (_type != value)
				{
					_type = value;
					OnPropertyChanged("Type");
				}
			}
		}
			
		private string _marked = "";
		///<summary>Database mapping to column A21OPOrderHeader.marked</summary>
		public string Marked
		{
			get { return _marked; }
			set
			{
				if (_marked != value)
				{
					_marked = value;
					OnPropertyChanged("Marked");
				}
			}
		}
			
		private string _eMail = "";
		///<summary>Database mapping to column A21OPOrderHeader.EMail</summary>
		public string EMail
		{
			get { return _eMail; }
			set
			{
				if (_eMail != value)
				{
					_eMail = value;
					OnPropertyChanged("EMail");
				}
			}
		}
			
		private string _incoTerms = "";
		///<summary>Database mapping to column A21OPOrderHeader.IncoTerms</summary>
		public string IncoTerms
		{
			get { return _incoTerms; }
			set
			{
				if (_incoTerms != value)
				{
					_incoTerms = value;
					OnPropertyChanged("IncoTerms");
				}
			}
		}
			
		private string _leadTime = "";
		///<summary>Database mapping to column A21OPOrderHeader.LeadTime</summary>
		public string LeadTime
		{
			get { return _leadTime; }
			set
			{
				if (_leadTime != value)
				{
					_leadTime = value;
					OnPropertyChanged("LeadTime");
				}
			}
		}
		
		#endregion
		
		///<summary>Initializes a new instance of this class</summary>
		public A21OPOrderHeader() : base()
		{
			// Default Constructor
		}
		
		#region IObjectHelper
		/// <summary>Indexer to update local member variables</summary>	
		/// <remarks>This indexer is used by the Wilson ORMapper</remarks>
		object IObjectHelper.this[string memberName]
		{
			get {
				switch (memberName) {
					case "_company": return _company;
					case "_trnType": return _trnType;
					case "_trnNo": return _trnNo;
					case "_code": return _code;
					case "_status": return _status;
					case "_currency": return _currency;
					case "_trnDate": return _trnDate;
					case "_trnTime": return _trnTime;
					case "_year": return _year;
					case "_month": return _month;
					case "_week": return _week;
					case "_exchangeRate": return _exchangeRate;
					case "_docNo": return _docNo;
					case "_narration": return _narration;
					case "_trnScreen": return _trnScreen;
					case "_location": return _location;
					case "_dAdd1": return _dAdd1;
					case "_dAdd2": return _dAdd2;
					case "_dAdd3": return _dAdd3;
					case "_dAdd4": return _dAdd4;
					case "_gSTInc": return _gSTInc;
					case "_gSTType": return _gSTType;
					case "_gST": return _gST;
					case "_discount": return _discount;
					case "_delDate": return _delDate;
					case "_salesPerson": return _salesPerson;
					case "_project": return _project;
					case "_department": return _department;
					case "_section": return _section;
					case "_updUser": return _updUser;
					case "_updDate": return _updDate;
					case "_updTime": return _updTime;
					case "_crtUser": return _crtUser;
					case "_crtDate": return _crtDate;
					case "_crtTime": return _crtTime;
					case "_custPONumber": return _custPONumber;
					case "_billAmt": return _billAmt;
					case "_quotNo": return _quotNo;
					case "_orderrefer": return _orderrefer;
					case "_type": return _type;
					case "_marked": return _marked;
					case "_eMail": return _eMail;
					case "_incoTerms": return _incoTerms;
					case "_leadTime": return _leadTime;
									
					default: throw new Exception(string.Format("Mapping: IObjectHelper Get is missing member case {0}", memberName));
				}
			}
			set {
				//handle null values
				if(value == null)
					return;
					
				switch (memberName) {
					case "_company": _company = (string)value; break;
					case "_trnType": _trnType = (string)value; break;
					case "_trnNo": _trnNo = (int)value; break;
					case "_code": _code = (string)value; break;
					case "_status": _status = (string)value; break;
					case "_currency": _currency = (string)value; break;
					case "_trnDate": _trnDate = (DateTime)value; break;
					case "_trnTime": _trnTime = (DateTime)value; break;
					case "_year": _year = (short)value; break;
					case "_month": _month = (byte)value; break;
					case "_week": _week = (byte)value; break;
					case "_exchangeRate": _exchangeRate = (double)value; break;
					case "_docNo": _docNo = (string)value; break;
					case "_narration": _narration = (string)value; break;
					case "_trnScreen": _trnScreen = (string)value; break;
					case "_location": _location = (string)value; break;
					case "_dAdd1": _dAdd1 = (string)value; break;
					case "_dAdd2": _dAdd2 = (string)value; break;
					case "_dAdd3": _dAdd3 = (string)value; break;
					case "_dAdd4": _dAdd4 = (string)value; break;
					case "_gSTInc": _gSTInc = (bool)value; break;
					case "_gSTType": _gSTType = (string)value; break;
					case "_gST": _gST = (double)value; break;
					case "_discount": _discount = (float)value; break;
					case "_delDate": _delDate = (DateTime)value; break;
					case "_salesPerson": _salesPerson = (string)value; break;
					case "_project": _project = (string)value; break;
					case "_department": _department = (string)value; break;
					case "_section": _section = (string)value; break;
					case "_updUser": _updUser = (string)value; break;
					case "_updDate": _updDate = (DateTime)value; break;
					case "_updTime": _updTime = (DateTime)value; break;
					case "_crtUser": _crtUser = (string)value; break;
					case "_crtDate": _crtDate = (DateTime)value; break;
					case "_crtTime": _crtTime = (DateTime)value; break;
					case "_custPONumber": _custPONumber = (string)value; break;
					case "_billAmt": _billAmt = (double)value; break;
					case "_quotNo": _quotNo = (int)value; break;
					case "_orderrefer": _orderrefer = (string)value; break;
					case "_type": _type = (string)value; break;
					case "_marked": _marked = (string)value; break;
					case "_eMail": _eMail = (string)value; break;
					case "_incoTerms": _incoTerms = (string)value; break;
					case "_leadTime": _leadTime = (string)value; break;
				
					default: throw new Exception(string.Format("Mapping: IObjectHelper Set is missing member case {0}", memberName));
				}
			}
		}
		#endregion
		
		#region ToString
		///<summary>
		///Overwrites the base ToString method. This is used for AuditTrail purposes.
		///</summary>
		public override string ToString()
		{
			System.Text.StringBuilder stb = new System.Text.StringBuilder(500);
			
			stb.AppendFormat("_company={0}\n,", _company.ToString() );
			stb.AppendFormat("_trnType={0}\n,", _trnType.ToString() );
			stb.AppendFormat("_trnNo={0}\n,", _trnNo.ToString() );
			stb.AppendFormat("_code={0}\n,", _code.ToString() );
			stb.AppendFormat("_status={0}\n,", _status.ToString() );
			stb.AppendFormat("_currency={0}\n,", _currency.ToString() );
			stb.AppendFormat("_trnDate={0}\n,", _trnDate.ToString() );
			stb.AppendFormat("_trnTime={0}\n,", _trnTime.ToString() );
			stb.AppendFormat("_year={0}\n,", _year.ToString() );
			stb.AppendFormat("_month={0}\n,", _month.ToString() );
			stb.AppendFormat("_week={0}\n,", _week.ToString() );
			stb.AppendFormat("_exchangeRate={0}\n,", _exchangeRate.ToString() );
			stb.AppendFormat("_docNo={0}\n,", _docNo.ToString() );
			stb.AppendFormat("_narration={0}\n,", _narration.ToString() );
			stb.AppendFormat("_trnScreen={0}\n,", _trnScreen.ToString() );
			stb.AppendFormat("_location={0}\n,", _location.ToString() );
			stb.AppendFormat("_dAdd1={0}\n,", _dAdd1.ToString() );
			stb.AppendFormat("_dAdd2={0}\n,", _dAdd2.ToString() );
			stb.AppendFormat("_dAdd3={0}\n,", _dAdd3.ToString() );
			stb.AppendFormat("_dAdd4={0}\n,", _dAdd4.ToString() );
			stb.AppendFormat("_gSTInc={0}\n,", _gSTInc.ToString() );
			stb.AppendFormat("_gSTType={0}\n,", _gSTType.ToString() );
			stb.AppendFormat("_gST={0}\n,", _gST.ToString() );
			stb.AppendFormat("_discount={0}\n,", _discount.ToString() );
			stb.AppendFormat("_delDate={0}\n,", _delDate.ToString() );
			stb.AppendFormat("_salesPerson={0}\n,", _salesPerson.ToString() );
			stb.AppendFormat("_project={0}\n,", _project.ToString() );
			stb.AppendFormat("_department={0}\n,", _department.ToString() );
			stb.AppendFormat("_section={0}\n,", _section.ToString() );
			stb.AppendFormat("_updUser={0}\n,", _updUser.ToString() );
			stb.AppendFormat("_updDate={0}\n,", _updDate.ToString() );
			stb.AppendFormat("_updTime={0}\n,", _updTime.ToString() );
			stb.AppendFormat("_crtUser={0}\n,", _crtUser.ToString() );
			stb.AppendFormat("_crtDate={0}\n,", _crtDate.ToString() );
			stb.AppendFormat("_crtTime={0}\n,", _crtTime.ToString() );
			stb.AppendFormat("_custPONumber={0}\n,", _custPONumber.ToString() );
			stb.AppendFormat("_billAmt={0}\n,", _billAmt.ToString() );
			stb.AppendFormat("_quotNo={0}\n,", _quotNo.ToString() );
			stb.AppendFormat("_orderrefer={0}\n,", _orderrefer.ToString() );
			stb.AppendFormat("_type={0}\n,", _type.ToString() );
			stb.AppendFormat("_marked={0}\n,", _marked.ToString() );
			stb.AppendFormat("_eMail={0}\n,", _eMail.ToString() );
			stb.AppendFormat("_incoTerms={0}\n,", _incoTerms.ToString() );
			stb.AppendFormat("_leadTime={0}\n,", _leadTime.ToString() );
							
			
			return stb.ToString();
		}
		#endregion

	}
}
