//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//	   DO NOT MODIFY contents of this file. Changes to this
//	   file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using Wilson.ORMapper;
using eLogixCore;

namespace GMSCore.Entity
{
	///<summary>Database mapping to table tbAccountCommRecord</summary>
	[DataObject(true)]
    public partial class AccountCommRecord : PersistBase<AccountCommRecord>, IObjectHelper
	{
		#region Properties
	
		private short _coyID;
		///<summary>Database mapping to column tbAccountCommRecord.CoyID</summary>
		[DataObjectField(true, false)]
		public short CoyID
		{
			get { return _coyID; }
			set
			{
				if (_coyID != value)
				{
					_coyID = value;
					OnPropertyChanged("CoyID");
				}
			}
		}
			
		private string _accountCode;
		///<summary>Database mapping to column tbAccountCommRecord.AccountCode</summary>
		public string AccountCode
		{
			get { return _accountCode; }
			set
			{
				if (_accountCode != value)
				{
					_accountCode = value;
					OnPropertyChanged("AccountCode");
				}
			}
		}
			
		private string _commID;
		///<summary>Database mapping to column tbAccountCommRecord.CommID</summary>
		[DataObjectField(true, false)]
		public string CommID
		{
			get { return _commID; }
			set
			{
				if (_commID != value)
				{
					_commID = value;
					OnPropertyChanged("CommID");
				}
			}
		}
			
		private DateTime _fromDateTime = DateTime.Parse("01/01/1900 00:00:00");
		///<summary>Database mapping to column tbAccountCommRecord.FromDateTime</summary>
		public DateTime FromDateTime
		{
			get { return _fromDateTime; }
			set
			{
				if (_fromDateTime != value)
				{
					_fromDateTime = value;
					OnPropertyChanged("FromDateTime");
				}
			}
		}
			
		private DateTime _toDateTime = DateTime.Parse("01/01/1900 00:00:00");
		///<summary>Database mapping to column tbAccountCommRecord.ToDateTime</summary>
		public DateTime ToDateTime
		{
			get { return _toDateTime; }
			set
			{
				if (_toDateTime != value)
				{
					_toDateTime = value;
					OnPropertyChanged("ToDateTime");
				}
			}
		}
			
		private string _description = "";
		///<summary>Database mapping to column tbAccountCommRecord.Description</summary>
		public string Description
		{
			get { return _description; }
			set
			{
				if (_description != value)
				{
					_description = value;
					OnPropertyChanged("Description");
				}
			}
		}
			
		private string _type = "";
		///<summary>Database mapping to column tbAccountCommRecord.Type</summary>
		public string Type
		{
			get { return _type; }
			set
			{
				if (_type != value)
				{
					_type = value;
					OnPropertyChanged("Type");
				}
			}
		}
			
		private string _status = "";
		///<summary>Database mapping to column tbAccountCommRecord.Status</summary>
		public string Status
		{
			get { return _status; }
			set
			{
				if (_status != value)
				{
					_status = value;
					OnPropertyChanged("Status");
				}
			}
		}
			
		private short _createdBy = 0;
		///<summary>Database mapping to column tbAccountCommRecord.CreatedBy</summary>
		public short CreatedBy
		{
			get { return _createdBy; }
			set
			{
				if (_createdBy != value)
				{
					_createdBy = value;
					OnPropertyChanged("CreatedBy");
				}
			}
		}
			
		private DateTime _createdDate = DateTime.Parse("01/01/1900 00:00:00");
		///<summary>Database mapping to column tbAccountCommRecord.CreatedDate</summary>
		public DateTime CreatedDate
		{
			get { return _createdDate; }
			set
			{
				if (_createdDate != value)
				{
					_createdDate = value;
					OnPropertyChanged("CreatedDate");
				}
			}
		}
			
		private short _modifiedBy = 0;
		///<summary>Database mapping to column tbAccountCommRecord.ModifiedBy</summary>
		public short ModifiedBy
		{
			get { return _modifiedBy; }
			set
			{
				if (_modifiedBy != value)
				{
					_modifiedBy = value;
					OnPropertyChanged("ModifiedBy");
				}
			}
		}
			
		private DateTime _modifiedDate = DateTime.Parse("01/01/1900 00:00:00");
		///<summary>Database mapping to column tbAccountCommRecord.ModifiedDate</summary>
		public DateTime ModifiedDate
		{
			get { return _modifiedDate; }
			set
			{
				if (_modifiedDate != value)
				{
					_modifiedDate = value;
					OnPropertyChanged("ModifiedDate");
				}
			}
		}
			
		private IList<AccountCommRecordComment> _tbAccountCommRecordCommentList;
		///<summary>Collection of AccountCommRecordComment objects</summary>
		public IList<AccountCommRecordComment> AccountCommRecordCommentList
		{
			get { return _tbAccountCommRecordCommentList; }
		}
		
		#endregion
		
		///<summary>Initializes a new instance of this class</summary>
		public AccountCommRecord() : base()
		{
			// Default Constructor
		}
		
		///<summary>Retrieve an instance of this class using its ID from the persistence store</summary>
		[DataObjectMethod(DataObjectMethodType.Select)]
        public static AccountCommRecord RetrieveByKey(short coyID, string commID)
		{
			DBManager db = DBManager.GetInstance();
			QueryHelper helper = db.Engine.QueryHelper;
			string where = helper.GetExpression("AccountCommRecord.CoyID", coyID);
			where += " and ";
			where += helper.GetExpression("AccountCommRecord.CommID", commID);

			return RetrieveFirst(where);			
		}
		
		///<summary>Delete instance from the persistence store based on primary key(s)</summary>
		[DataObjectMethod(DataObjectMethodType.Delete)]
        public static int DeleteByKey(short coyID, string commID)
		{			
			DBManager db = DBManager.GetInstance();		
			QueryHelper helper = db.Engine.QueryHelper;
			string where = helper.GetExpression("AccountCommRecord.CoyID", coyID);
			where += " and ";
			where += helper.GetExpression("AccountCommRecord.CommID", commID);
			
			return Delete(where);
		}
		
		///<summary>Delete instance from the persistence store based on primary key(s) using a transaction</summary>
		///<param name="transaction">An instance of a Wilson.ORMapper.Transaction to perform operation with.</param>
		public static int DeleteByKey(Wilson.ORMapper.Transaction transaction, short coyID, string commID)
		{			
			DBManager db = DBManager.GetInstance();
			QueryHelper helper = db.Engine.QueryHelper;
			string where = helper.GetExpression("AccountCommRecord.CoyID", coyID);
			where += " and ";
			where += helper.GetExpression("AccountCommRecord.CommID", commID);
			
			return Delete(transaction, where);
		}		
		#region IObjectHelper
		/// <summary>Indexer to update local member variables</summary>	
		/// <remarks>This indexer is used by the Wilson ORMapper</remarks>
		object IObjectHelper.this[string memberName]
		{
			get {
				switch (memberName) {
					case "_coyID": return _coyID;
					case "_accountCode": return _accountCode;
					case "_commID": return _commID;
					case "_fromDateTime": return _fromDateTime;
					case "_toDateTime": return _toDateTime;
					case "_description": return _description;
					case "_type": return _type;
					case "_status": return _status;
					case "_createdBy": return _createdBy;
					case "_createdDate": return _createdDate;
					case "_modifiedBy": return _modifiedBy;
					case "_modifiedDate": return _modifiedDate;
					case "_tbAccountCommRecordCommentList": return _tbAccountCommRecordCommentList;
									
					default: throw new Exception(string.Format("Mapping: IObjectHelper Get is missing member case {0}", memberName));
				}
			}
			set {
				//handle null values
				if(value == null)
					return;
					
				switch (memberName) {
					case "_coyID": _coyID = (short)value; break;
					case "_accountCode": _accountCode = (string)value; break;
					case "_commID": _commID = (string)value; break;
					case "_fromDateTime": _fromDateTime = (DateTime)value; break;
					case "_toDateTime": _toDateTime = (DateTime)value; break;
					case "_description": _description = (string)value; break;
					case "_type": _type = (string)value; break;
					case "_status": _status = (string)value; break;
					case "_createdBy": _createdBy = (short)value; break;
					case "_createdDate": _createdDate = (DateTime)value; break;
					case "_modifiedBy": _modifiedBy = (short)value; break;
					case "_modifiedDate": _modifiedDate = (DateTime)value; break;
					case "_tbAccountCommRecordCommentList": _tbAccountCommRecordCommentList = (IList<AccountCommRecordComment>)value; break;
				
					default: throw new Exception(string.Format("Mapping: IObjectHelper Set is missing member case {0}", memberName));
				}
			}
		}
		#endregion
		
		#region ToString
		///<summary>
		///Overwrites the base ToString method. This is used for AuditTrail purposes.
		///</summary>
		public override string ToString()
		{
			System.Text.StringBuilder stb = new System.Text.StringBuilder(500);
			
			stb.AppendFormat("_coyID={0}\n,", _coyID.ToString() );
			stb.AppendFormat("_accountCode={0}\n,", _accountCode.ToString() );
			stb.AppendFormat("_commID={0}\n,", _commID.ToString() );
			stb.AppendFormat("_fromDateTime={0}\n,", _fromDateTime.ToString() );
			stb.AppendFormat("_toDateTime={0}\n,", _toDateTime.ToString() );
			stb.AppendFormat("_description={0}\n,", _description.ToString() );
			stb.AppendFormat("_type={0}\n,", _type.ToString() );
			stb.AppendFormat("_status={0}\n,", _status.ToString() );
			stb.AppendFormat("_createdBy={0}\n,", _createdBy.ToString() );
			stb.AppendFormat("_createdDate={0}\n,", _createdDate.ToString() );
			stb.AppendFormat("_modifiedBy={0}\n,", _modifiedBy.ToString() );
			stb.AppendFormat("_modifiedDate={0}\n,", _modifiedDate.ToString() );
							
			
			return stb.ToString();
		}
		#endregion

	}
}
