//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//	   DO NOT MODIFY contents of this file. Changes to this
//	   file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using Wilson.ORMapper;
using eLogixCore;

namespace GMSCore.Entity
{
	///<summary>Database mapping to table tbAuditForReportAccess</summary>
	[DataObject(true)]
    public partial class AuditForReportAccess : PersistBase<AuditForReportAccess>, IObjectHelper
	{
		#region Properties
	
		private short _coyID;
		///<summary>Database mapping to column tbAuditForReportAccess.CoyID</summary>
		[DataObjectField(true, false)]
		public short CoyID
		{
			get { return _coyID; }
			set
			{
				if (_coyID != value)
				{
					_coyID = value;
					OnPropertyChanged("CoyID");
				}
			}
		}
			
		private short _userID;
		///<summary>Database mapping to column tbAuditForReportAccess.UserID</summary>
		[DataObjectField(true, false)]
		public short UserID
		{
			get { return _userID; }
			set
			{
				if (_userID != value)
				{
					_userID = value;
					OnPropertyChanged("UserID");
				}
			}
		}
			
		private short _reportID;
		///<summary>Database mapping to column tbAuditForReportAccess.ReportID</summary>
		[DataObjectField(true, false)]
		public short ReportID
		{
			get { return _reportID; }
			set
			{
				if (_reportID != value)
				{
					_reportID = value;
					OnPropertyChanged("ReportID");
				}
			}
		}
			
		private DateTime _accessDate;
		///<summary>Database mapping to column tbAuditForReportAccess.AccessDate</summary>
		[DataObjectField(true, false)]
		public DateTime AccessDate
		{
			get { return _accessDate; }
			set
			{
				if (_accessDate != value)
				{
					_accessDate = value;
					OnPropertyChanged("AccessDate");
				}
			}
		}
		
		#endregion
		
		///<summary>Initializes a new instance of this class</summary>
		public AuditForReportAccess() : base()
		{
			// Default Constructor
		}
		
		///<summary>Retrieve an instance of this class using its ID from the persistence store</summary>
		[DataObjectMethod(DataObjectMethodType.Select)]
        public static AuditForReportAccess RetrieveByKey(short coyID, short userID, short reportID, DateTime accessDate)
		{
			DBManager db = DBManager.GetInstance();
			QueryHelper helper = db.Engine.QueryHelper;
			string where = helper.GetExpression("AuditForReportAccess.CoyID", coyID);
			where += " and ";
			where += helper.GetExpression("AuditForReportAccess.UserID", userID);
			where += " and ";
			where += helper.GetExpression("AuditForReportAccess.ReportID", reportID);
			where += " and ";
			where += helper.GetExpression("AuditForReportAccess.AccessDate", accessDate);

			return RetrieveFirst(where);			
		}
		
		///<summary>Delete instance from the persistence store based on primary key(s)</summary>
		[DataObjectMethod(DataObjectMethodType.Delete)]
        public static int DeleteByKey(short coyID, short userID, short reportID, DateTime accessDate)
		{			
			DBManager db = DBManager.GetInstance();		
			QueryHelper helper = db.Engine.QueryHelper;
			string where = helper.GetExpression("AuditForReportAccess.CoyID", coyID);
			where += " and ";
			where += helper.GetExpression("AuditForReportAccess.UserID", userID);
			where += " and ";
			where += helper.GetExpression("AuditForReportAccess.ReportID", reportID);
			where += " and ";
			where += helper.GetExpression("AuditForReportAccess.AccessDate", accessDate);
			
			return Delete(where);
		}
		
		///<summary>Delete instance from the persistence store based on primary key(s) using a transaction</summary>
		///<param name="transaction">An instance of a Wilson.ORMapper.Transaction to perform operation with.</param>
		public static int DeleteByKey(Wilson.ORMapper.Transaction transaction, short coyID, short userID, short reportID, DateTime accessDate)
		{			
			DBManager db = DBManager.GetInstance();
			QueryHelper helper = db.Engine.QueryHelper;
			string where = helper.GetExpression("AuditForReportAccess.CoyID", coyID);
			where += " and ";
			where += helper.GetExpression("AuditForReportAccess.UserID", userID);
			where += " and ";
			where += helper.GetExpression("AuditForReportAccess.ReportID", reportID);
			where += " and ";
			where += helper.GetExpression("AuditForReportAccess.AccessDate", accessDate);
			
			return Delete(transaction, where);
		}		
		#region IObjectHelper
		/// <summary>Indexer to update local member variables</summary>	
		/// <remarks>This indexer is used by the Wilson ORMapper</remarks>
		object IObjectHelper.this[string memberName]
		{
			get {
				switch (memberName) {
					case "_coyID": return _coyID;
					case "_userID": return _userID;
					case "_reportID": return _reportID;
					case "_accessDate": return _accessDate;
									
					default: throw new Exception(string.Format("Mapping: IObjectHelper Get is missing member case {0}", memberName));
				}
			}
			set {
				//handle null values
				if(value == null)
					return;
					
				switch (memberName) {
					case "_coyID": _coyID = (short)value; break;
					case "_userID": _userID = (short)value; break;
					case "_reportID": _reportID = (short)value; break;
					case "_accessDate": _accessDate = (DateTime)value; break;
				
					default: throw new Exception(string.Format("Mapping: IObjectHelper Set is missing member case {0}", memberName));
				}
			}
		}
		#endregion
		
		#region ToString
		///<summary>
		///Overwrites the base ToString method. This is used for AuditTrail purposes.
		///</summary>
		public override string ToString()
		{
			System.Text.StringBuilder stb = new System.Text.StringBuilder(500);
			
			stb.AppendFormat("_coyID={0}\n,", _coyID.ToString() );
			stb.AppendFormat("_userID={0}\n,", _userID.ToString() );
			stb.AppendFormat("_reportID={0}\n,", _reportID.ToString() );
			stb.AppendFormat("_accessDate={0}\n,", _accessDate.ToString() );
							
			
			return stb.ToString();
		}
		#endregion

	}
}
