//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//	   DO NOT MODIFY contents of this file. Changes to this
//	   file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using Wilson.ORMapper;
using eLogixCore;

namespace GMSCore.Entity
{
	///<summary>Database mapping to table tbCurrency</summary>
	[DataObject(true)]
    public partial class Currency : PersistBase<Currency>, IObjectHelper
	{
		#region Properties
	
		private string _currencyCode;
		///<summary>Database mapping to column tbCurrency.CurrencyCode</summary>
		[DataObjectField(true, false)]
		public string CurrencyCode
		{
			get { return _currencyCode; }
			set
			{
				if (_currencyCode != value)
				{
					_currencyCode = value;
					OnPropertyChanged("CurrencyCode");
				}
			}
		}
			
		private string _currencyName;
		///<summary>Database mapping to column tbCurrency.CurrencyName</summary>
		public string CurrencyName
		{
			get { return _currencyName; }
			set
			{
				if (_currencyName != value)
				{
					_currencyName = value;
					OnPropertyChanged("CurrencyName");
				}
			}
		}
			
		private short _createdBy = 0;
		///<summary>Database mapping to column tbCurrency.CreatedBy</summary>
		public short CreatedBy
		{
			get { return _createdBy; }
			set
			{
				if (_createdBy != value)
				{
					_createdBy = value;
					OnPropertyChanged("CreatedBy");
				}
			}
		}
			
		private DateTime _createdDate = DateTime.Parse("01/01/1900 00:00:00");
		///<summary>Database mapping to column tbCurrency.CreatedDate</summary>
		public DateTime CreatedDate
		{
			get { return _createdDate; }
			set
			{
				if (_createdDate != value)
				{
					_createdDate = value;
					OnPropertyChanged("CreatedDate");
				}
			}
		}
			
		private short _modifiedBy = 0;
		///<summary>Database mapping to column tbCurrency.ModifiedBy</summary>
		public short ModifiedBy
		{
			get { return _modifiedBy; }
			set
			{
				if (_modifiedBy != value)
				{
					_modifiedBy = value;
					OnPropertyChanged("ModifiedBy");
				}
			}
		}
			
		private DateTime _modifiedDate = DateTime.Parse("01/01/1900 00:00:00");
		///<summary>Database mapping to column tbCurrency.ModifiedDate</summary>
		public DateTime ModifiedDate
		{
			get { return _modifiedDate; }
			set
			{
				if (_modifiedDate != value)
				{
					_modifiedDate = value;
					OnPropertyChanged("ModifiedDate");
				}
			}
		}
			
		private string _currencySign = "";
		///<summary>Database mapping to column tbCurrency.CurrencySign</summary>
		public string CurrencySign
		{
			get { return _currencySign; }
			set
			{
				if (_currencySign != value)
				{
					_currencySign = value;
					OnPropertyChanged("CurrencySign");
				}
			}
		}
			
		private IList<ForeignExchangeRate> _homeForeignExchangeRateList;
		///<summary>Collection of ForeignExchangeRate objects</summary>
		public IList<ForeignExchangeRate> HomeForeignExchangeRateList
		{
			get { return _homeForeignExchangeRateList; }
		}
			
		private IList<ForeignExchangeRate> _foreignForeignExchangeRateList;
		///<summary>Collection of ForeignExchangeRate objects</summary>
		public IList<ForeignExchangeRate> ForeignForeignExchangeRateList
		{
			get { return _foreignForeignExchangeRateList; }
		}
			
		private IList<Company> _defaultCompanyList;
		///<summary>Collection of Company objects</summary>
		public IList<Company> DefaultCompanyList
		{
			get { return _defaultCompanyList; }
		}
		
		#endregion
		
		///<summary>Initializes a new instance of this class</summary>
		public Currency() : base()
		{
			// Default Constructor
		}
		
		///<summary>Retrieve an instance of this class using its ID from the persistence store</summary>
		[DataObjectMethod(DataObjectMethodType.Select)]
        public static Currency RetrieveByKey(string currencyCode)
		{
			DBManager db = DBManager.GetInstance();
			return db.Engine.GetObject<Currency>(currencyCode);
		}
		
		///<summary>Delete instance from the persistence store based on primary key(s)</summary>
		[DataObjectMethod(DataObjectMethodType.Delete)]
        public static int DeleteByKey(string currencyCode)
		{			
			DBManager db = DBManager.GetInstance();		
			QueryHelper helper = db.Engine.QueryHelper;
			string where = helper.GetExpression("Currency.CurrencyCode", currencyCode);
			
			return Delete(where);
		}
		
		///<summary>Delete instance from the persistence store based on primary key(s) using a transaction</summary>
		///<param name="transaction">An instance of a Wilson.ORMapper.Transaction to perform operation with.</param>
		public static int DeleteByKey(Wilson.ORMapper.Transaction transaction, string currencyCode)
		{			
			DBManager db = DBManager.GetInstance();
			QueryHelper helper = db.Engine.QueryHelper;
			string where = helper.GetExpression("Currency.CurrencyCode", currencyCode);
			
			return Delete(transaction, where);
		}		
		#region IObjectHelper
		/// <summary>Indexer to update local member variables</summary>	
		/// <remarks>This indexer is used by the Wilson ORMapper</remarks>
		object IObjectHelper.this[string memberName]
		{
			get {
				switch (memberName) {
					case "_currencyCode": return _currencyCode;
					case "_currencyName": return _currencyName;
					case "_createdBy": return _createdBy;
					case "_createdDate": return _createdDate;
					case "_modifiedBy": return _modifiedBy;
					case "_modifiedDate": return _modifiedDate;
					case "_currencySign": return _currencySign;
					case "_homeForeignExchangeRateList": return _homeForeignExchangeRateList;
					case "_foreignForeignExchangeRateList": return _foreignForeignExchangeRateList;
					case "_defaultCompanyList": return _defaultCompanyList;
									
					default: throw new Exception(string.Format("Mapping: IObjectHelper Get is missing member case {0}", memberName));
				}
			}
			set {
				//handle null values
				if(value == null)
					return;
					
				switch (memberName) {
					case "_currencyCode": _currencyCode = (string)value; break;
					case "_currencyName": _currencyName = (string)value; break;
					case "_createdBy": _createdBy = (short)value; break;
					case "_createdDate": _createdDate = (DateTime)value; break;
					case "_modifiedBy": _modifiedBy = (short)value; break;
					case "_modifiedDate": _modifiedDate = (DateTime)value; break;
					case "_currencySign": _currencySign = (string)value; break;
					case "_homeForeignExchangeRateList": _homeForeignExchangeRateList = (IList<ForeignExchangeRate>)value; break;
					case "_foreignForeignExchangeRateList": _foreignForeignExchangeRateList = (IList<ForeignExchangeRate>)value; break;
					case "_defaultCompanyList": _defaultCompanyList = (IList<Company>)value; break;
				
					default: throw new Exception(string.Format("Mapping: IObjectHelper Set is missing member case {0}", memberName));
				}
			}
		}
		#endregion
		
		#region ToString
		///<summary>
		///Overwrites the base ToString method. This is used for AuditTrail purposes.
		///</summary>
		public override string ToString()
		{
			System.Text.StringBuilder stb = new System.Text.StringBuilder(500);
			
			stb.AppendFormat("_currencyCode={0}\n,", _currencyCode.ToString() );
			stb.AppendFormat("_currencyName={0}\n,", _currencyName.ToString() );
			stb.AppendFormat("_createdBy={0}\n,", _createdBy.ToString() );
			stb.AppendFormat("_createdDate={0}\n,", _createdDate.ToString() );
			stb.AppendFormat("_modifiedBy={0}\n,", _modifiedBy.ToString() );
			stb.AppendFormat("_modifiedDate={0}\n,", _modifiedDate.ToString() );
			stb.AppendFormat("_currencySign={0}\n,", _currencySign.ToString() );
							
			
			return stb.ToString();
		}
		#endregion

	}
}
