//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//	   DO NOT MODIFY contents of this file. Changes to this
//	   file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using Wilson.ORMapper;
using eLogixCore;

namespace GMSCore.Entity
{
	///<summary>Database mapping to table tbFinanceItem</summary>
	[DataObject(true)]
    public partial class FinanceItem : PersistBase<FinanceItem>, IObjectHelper
	{
		#region Properties
	
		private short _itemID;
		///<summary>Database mapping to column tbFinanceItem.ItemID</summary>
		public short ItemID
		{
			get { return _itemID; }
		}
			
		private string _itemName = "";
		///<summary>Database mapping to column tbFinanceItem.ItemName</summary>
		public string ItemName
		{
			get { return _itemName; }
			set
			{
				if (_itemName != value)
				{
					_itemName = value;
					OnPropertyChanged("ItemName");
				}
			}
		}
		
		#endregion
		
		///<summary>Initializes a new instance of this class</summary>
		public FinanceItem() : base()
		{
			// Default Constructor
		}
		
		#region IObjectHelper
		/// <summary>Indexer to update local member variables</summary>	
		/// <remarks>This indexer is used by the Wilson ORMapper</remarks>
		object IObjectHelper.this[string memberName]
		{
			get {
				switch (memberName) {
					case "_itemID": return _itemID;
					case "_itemName": return _itemName;
									
					default: throw new Exception(string.Format("Mapping: IObjectHelper Get is missing member case {0}", memberName));
				}
			}
			set {
				//handle null values
				if(value == null)
					return;
					
				switch (memberName) {
					case "_itemID": _itemID = (short)value; break;
					case "_itemName": _itemName = (string)value; break;
				
					default: throw new Exception(string.Format("Mapping: IObjectHelper Set is missing member case {0}", memberName));
				}
			}
		}
		#endregion
		
		#region ToString
		///<summary>
		///Overwrites the base ToString method. This is used for AuditTrail purposes.
		///</summary>
		public override string ToString()
		{
			System.Text.StringBuilder stb = new System.Text.StringBuilder(500);
			
			stb.AppendFormat("_itemID={0}\n,", _itemID.ToString() );
			stb.AppendFormat("_itemName={0}\n,", _itemName.ToString() );
							
			
			return stb.ToString();
		}
		#endregion

	}
}
