//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//	   DO NOT MODIFY contents of this file. Changes to this
//	   file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using Wilson.ORMapper;
using eLogixCore;

namespace GMSCore.Entity
{
	///<summary>Database mapping to table tbGroupManagementUser</summary>
	[DataObject(true)]
    public partial class GroupManagementUser : PersistBase<GroupManagementUser>, IObjectHelper
	{
		#region Properties
	
		private short _mGUserID;
		///<summary>Database mapping to column tbGroupManagementUser.MGUserID</summary>
		[DataObjectField(true, false)]
		public short MGUserID
		{
			get { return _mGUserID; }
			set
			{
				if (_mGUserID != value)
				{
					_mGUserID = value;
					OnPropertyChanged("MGUserID");
				}
			}
		}
		
		#endregion
		
		///<summary>Initializes a new instance of this class</summary>
		public GroupManagementUser() : base()
		{
			// Default Constructor
		}
		
		///<summary>Retrieve an instance of this class using its ID from the persistence store</summary>
		[DataObjectMethod(DataObjectMethodType.Select)]
        public static GroupManagementUser RetrieveByKey(short mGUserID)
		{
			DBManager db = DBManager.GetInstance();
			return db.Engine.GetObject<GroupManagementUser>(mGUserID);
		}
		
		///<summary>Delete instance from the persistence store based on primary key(s)</summary>
		[DataObjectMethod(DataObjectMethodType.Delete)]
        public static int DeleteByKey(short mGUserID)
		{			
			DBManager db = DBManager.GetInstance();		
			QueryHelper helper = db.Engine.QueryHelper;
			string where = helper.GetExpression("GroupManagementUser.MGUserID", mGUserID);
			
			return Delete(where);
		}
		
		///<summary>Delete instance from the persistence store based on primary key(s) using a transaction</summary>
		///<param name="transaction">An instance of a Wilson.ORMapper.Transaction to perform operation with.</param>
		public static int DeleteByKey(Wilson.ORMapper.Transaction transaction, short mGUserID)
		{			
			DBManager db = DBManager.GetInstance();
			QueryHelper helper = db.Engine.QueryHelper;
			string where = helper.GetExpression("GroupManagementUser.MGUserID", mGUserID);
			
			return Delete(transaction, where);
		}		
		#region IObjectHelper
		/// <summary>Indexer to update local member variables</summary>	
		/// <remarks>This indexer is used by the Wilson ORMapper</remarks>
		object IObjectHelper.this[string memberName]
		{
			get {
				switch (memberName) {
					case "_mGUserID": return _mGUserID;
									
					default: throw new Exception(string.Format("Mapping: IObjectHelper Get is missing member case {0}", memberName));
				}
			}
			set {
				//handle null values
				if(value == null)
					return;
					
				switch (memberName) {
					case "_mGUserID": _mGUserID = (short)value; break;
				
					default: throw new Exception(string.Format("Mapping: IObjectHelper Set is missing member case {0}", memberName));
				}
			}
		}
		#endregion
		
		#region ToString
		///<summary>
		///Overwrites the base ToString method. This is used for AuditTrail purposes.
		///</summary>
		public override string ToString()
		{
			System.Text.StringBuilder stb = new System.Text.StringBuilder(500);
			
			stb.AppendFormat("_mGUserID={0}\n,", _mGUserID.ToString() );
							
			
			return stb.ToString();
		}
		#endregion

	}
}
