//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//	   DO NOT MODIFY contents of this file. Changes to this
//	   file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using Wilson.ORMapper;
using eLogixCore;

namespace GMSCore.Entity
{
	///<summary>Database mapping to table tbItemPurpose</summary>
	[DataObject(true)]
    public partial class ItemPurpose : PersistBase<ItemPurpose>, IObjectHelper
	{
		#region Properties
	
		private short _itemPurposeID;
		///<summary>Database mapping to column tbItemPurpose.ItemPurposeID</summary>
		[DataObjectField(true, false)]
		public short ItemPurposeID
		{
			get { return _itemPurposeID; }
			set
			{
				if (_itemPurposeID != value)
				{
					_itemPurposeID = value;
					OnPropertyChanged("ItemPurposeID");
				}
			}
		}
			
		private string _itemPurposeName = "";
		///<summary>Database mapping to column tbItemPurpose.ItemPurposeName</summary>
		public string ItemPurposeName
		{
			get { return _itemPurposeName; }
			set
			{
				if (_itemPurposeName != value)
				{
					_itemPurposeName = value;
					OnPropertyChanged("ItemPurposeName");
				}
			}
		}
			
		private short _createdBy = 0;
		///<summary>Database mapping to column tbItemPurpose.CreatedBy</summary>
		public short CreatedBy
		{
			get { return _createdBy; }
			set
			{
				if (_createdBy != value)
				{
					_createdBy = value;
					OnPropertyChanged("CreatedBy");
				}
			}
		}
			
		private DateTime _createdDate = DateTime.Parse("01/01/1900 00:00:00");
		///<summary>Database mapping to column tbItemPurpose.CreatedDate</summary>
		public DateTime CreatedDate
		{
			get { return _createdDate; }
			set
			{
				if (_createdDate != value)
				{
					_createdDate = value;
					OnPropertyChanged("CreatedDate");
				}
			}
		}
			
		private short _modifiedBy = 0;
		///<summary>Database mapping to column tbItemPurpose.ModifiedBy</summary>
		public short ModifiedBy
		{
			get { return _modifiedBy; }
			set
			{
				if (_modifiedBy != value)
				{
					_modifiedBy = value;
					OnPropertyChanged("ModifiedBy");
				}
			}
		}
			
		private DateTime _modifiedDate = DateTime.Parse("01/01/1900 00:00:00");
		///<summary>Database mapping to column tbItemPurpose.ModifiedDate</summary>
		public DateTime ModifiedDate
		{
			get { return _modifiedDate; }
			set
			{
				if (_modifiedDate != value)
				{
					_modifiedDate = value;
					OnPropertyChanged("ModifiedDate");
				}
			}
		}
			
		private IList<ItemStructure> _ItemStructureList;
		///<summary>Collection of ItemStructure objects</summary>
		public IList<ItemStructure> ItemStructureList
		{
			get { return _ItemStructureList; }
		}
		
		#endregion
		
		///<summary>Initializes a new instance of this class</summary>
		public ItemPurpose() : base()
		{
			// Default Constructor
		}
		
		///<summary>Retrieve an instance of this class using its ID from the persistence store</summary>
		[DataObjectMethod(DataObjectMethodType.Select)]
        public static ItemPurpose RetrieveByKey(short itemPurposeID)
		{
			DBManager db = DBManager.GetInstance();
			return db.Engine.GetObject<ItemPurpose>(itemPurposeID);
		}
		
		///<summary>Delete instance from the persistence store based on primary key(s)</summary>
		[DataObjectMethod(DataObjectMethodType.Delete)]
        public static int DeleteByKey(short itemPurposeID)
		{			
			DBManager db = DBManager.GetInstance();		
			QueryHelper helper = db.Engine.QueryHelper;
			string where = helper.GetExpression("ItemPurpose.ItemPurposeID", itemPurposeID);
			
			return Delete(where);
		}
		
		///<summary>Delete instance from the persistence store based on primary key(s) using a transaction</summary>
		///<param name="transaction">An instance of a Wilson.ORMapper.Transaction to perform operation with.</param>
		public static int DeleteByKey(Wilson.ORMapper.Transaction transaction, short itemPurposeID)
		{			
			DBManager db = DBManager.GetInstance();
			QueryHelper helper = db.Engine.QueryHelper;
			string where = helper.GetExpression("ItemPurpose.ItemPurposeID", itemPurposeID);
			
			return Delete(transaction, where);
		}		
		#region IObjectHelper
		/// <summary>Indexer to update local member variables</summary>	
		/// <remarks>This indexer is used by the Wilson ORMapper</remarks>
		object IObjectHelper.this[string memberName]
		{
			get {
				switch (memberName) {
					case "_itemPurposeID": return _itemPurposeID;
					case "_itemPurposeName": return _itemPurposeName;
					case "_createdBy": return _createdBy;
					case "_createdDate": return _createdDate;
					case "_modifiedBy": return _modifiedBy;
					case "_modifiedDate": return _modifiedDate;
					case "_ItemStructureList": return _ItemStructureList;
									
					default: throw new Exception(string.Format("Mapping: IObjectHelper Get is missing member case {0}", memberName));
				}
			}
			set {
				//handle null values
				if(value == null)
					return;
					
				switch (memberName) {
					case "_itemPurposeID": _itemPurposeID = (short)value; break;
					case "_itemPurposeName": _itemPurposeName = (string)value; break;
					case "_createdBy": _createdBy = (short)value; break;
					case "_createdDate": _createdDate = (DateTime)value; break;
					case "_modifiedBy": _modifiedBy = (short)value; break;
					case "_modifiedDate": _modifiedDate = (DateTime)value; break;
					case "_ItemStructureList": _ItemStructureList = (IList<ItemStructure>)value; break;
				
					default: throw new Exception(string.Format("Mapping: IObjectHelper Set is missing member case {0}", memberName));
				}
			}
		}
		#endregion
		
		#region ToString
		///<summary>
		///Overwrites the base ToString method. This is used for AuditTrail purposes.
		///</summary>
		public override string ToString()
		{
			System.Text.StringBuilder stb = new System.Text.StringBuilder(500);
			
			stb.AppendFormat("_itemPurposeID={0}\n,", _itemPurposeID.ToString() );
			stb.AppendFormat("_itemPurposeName={0}\n,", _itemPurposeName.ToString() );
			stb.AppendFormat("_createdBy={0}\n,", _createdBy.ToString() );
			stb.AppendFormat("_createdDate={0}\n,", _createdDate.ToString() );
			stb.AppendFormat("_modifiedBy={0}\n,", _modifiedBy.ToString() );
			stb.AppendFormat("_modifiedDate={0}\n,", _modifiedDate.ToString() );
							
			
			return stb.ToString();
		}
		#endregion

	}
}
