//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//	   DO NOT MODIFY contents of this file. Changes to this
//	   file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using Wilson.ORMapper;
using eLogixCore;

namespace GMSCore.Entity
{
	///<summary>Database mapping to table tbMRAttachment</summary>
	[DataObject(true)]
    public partial class MRAttachment : PersistBase<MRAttachment>, IObjectHelper
	{
		#region Properties
	
		private short _coyID;
		///<summary>Database mapping to column tbMRAttachment.CoyID</summary>
		public short CoyID
		{
			get { return _coyID; }
			set
			{
				if (_coyID != value)
				{
					_coyID = value;
					OnPropertyChanged("CoyID");
				}
			}
		}
			
		private string _mRNo;
		///<summary>Database mapping to column tbMRAttachment.MRNo</summary>
		public string MRNo
		{
			get { return _mRNo; }
			set
			{
				if (_mRNo != value)
				{
					_mRNo = value;
					OnPropertyChanged("MRNo");
				}
			}
		}
			
		private string _customerAccountCode;
		///<summary>Database mapping to column tbMRAttachment.CustomerAccountCode</summary>
		public string CustomerAccountCode
		{
			get { return _customerAccountCode; }
			set
			{
				if (_customerAccountCode != value)
				{
					_customerAccountCode = value;
					OnPropertyChanged("CustomerAccountCode");
				}
			}
		}
			
		private string _customerName;
		///<summary>Database mapping to column tbMRAttachment.CustomerName</summary>
		public string CustomerName
		{
			get { return _customerName; }
			set
			{
				if (_customerName != value)
				{
					_customerName = value;
					OnPropertyChanged("CustomerName");
				}
			}
		}
			
		private string _sONo;
		///<summary>Database mapping to column tbMRAttachment.SONo</summary>
		public string SONo
		{
			get { return _sONo; }
			set
			{
				if (_sONo != value)
				{
					_sONo = value;
					OnPropertyChanged("SONo");
				}
			}
		}
			
		private DateTime _sODate;
		///<summary>Database mapping to column tbMRAttachment.SODate</summary>
		public DateTime SODate
		{
			get { return _sODate; }
			set
			{
				if (_sODate != value)
				{
					_sODate = value;
					OnPropertyChanged("SODate");
				}
			}
		}
			
		private DateTime _requiredDate;
		///<summary>Database mapping to column tbMRAttachment.RequiredDate</summary>
		public DateTime RequiredDate
		{
			get { return _requiredDate; }
			set
			{
				if (_requiredDate != value)
				{
					_requiredDate = value;
					OnPropertyChanged("RequiredDate");
				}
			}
		}
			
		private short _fileID;
		///<summary>Database mapping to column tbMRAttachment.FileID</summary>
		[DataObjectField(true, true)]
		public short FileID
		{
			get { return _fileID; }
			set
			{
				if (_fileID != value)
				{
					_fileID = value;
					OnPropertyChanged("FileID");
				}
			}
		}
			
		private string _fileName;
		///<summary>Database mapping to column tbMRAttachment.FileName</summary>
		public string FileName
		{
			get { return _fileName; }
			set
			{
				if (_fileName != value)
				{
					_fileName = value;
					OnPropertyChanged("FileName");
				}
			}
		}
			
		private string _fileNameEncrypted;
		///<summary>Database mapping to column tbMRAttachment.FileNameEncrypted</summary>
		public string FileNameEncrypted
		{
			get { return _fileNameEncrypted; }
			set
			{
				if (_fileNameEncrypted != value)
				{
					_fileNameEncrypted = value;
					OnPropertyChanged("FileNameEncrypted");
				}
			}
		}
			
		private short _createdBy;
		///<summary>Database mapping to column tbMRAttachment.CreatedBy</summary>
		public short CreatedBy
		{
			get { return _createdBy; }
			set
			{
				if (_createdBy != value)
				{
					_createdBy = value;
					OnPropertyChanged("CreatedBy");
				}
			}
		}
			
		private DateTime _createdDate;
		///<summary>Database mapping to column tbMRAttachment.CreatedDate</summary>
		public DateTime CreatedDate
		{
			get { return _createdDate; }
			set
			{
				if (_createdDate != value)
				{
					_createdDate = value;
					OnPropertyChanged("CreatedDate");
				}
			}
		}
			
		private Nullable<short> _modifiedBy;
		///<summary>Database mapping to column tbMRAttachment.ModifiedBy</summary>
		public Nullable<short> ModifiedBy
		{
			get { return _modifiedBy; }
			set
			{
				if (_modifiedBy != value)
				{
					_modifiedBy = value;
					OnPropertyChanged("ModifiedBy");
				}
			}
		}
			
		private Nullable<DateTime> _modifiedDate;
		///<summary>Database mapping to column tbMRAttachment.ModifiedDate</summary>
		public Nullable<DateTime> ModifiedDate
		{
			get { return _modifiedDate; }
			set
			{
				if (_modifiedDate != value)
				{
					_modifiedDate = value;
					OnPropertyChanged("ModifiedDate");
				}
			}
		}
		
		#endregion
		
		///<summary>Initializes a new instance of this class</summary>
		public MRAttachment() : base()
		{
			// Default Constructor
		}
		///<summary>Initializes a new instance of this class</summary>
		///<param name="startTracking">Set to true to begin ORMapper tracking on this instance</param>
		public MRAttachment(bool startTracking) : base(startTracking)
		{
			
		}
		
		///<summary>Retrieve an instance of this class using its ID from the persistence store</summary>
		[DataObjectMethod(DataObjectMethodType.Select)]
        public static MRAttachment RetrieveByKey(short fileID)
		{
			DBManager db = DBManager.GetInstance();
			return db.Engine.GetObject<MRAttachment>(fileID);
		}
		
		///<summary>Delete instance from the persistence store based on primary key(s)</summary>
		[DataObjectMethod(DataObjectMethodType.Delete)]
        public static int DeleteByKey(short fileID)
		{			
			DBManager db = DBManager.GetInstance();		
			QueryHelper helper = db.Engine.QueryHelper;
			string where = helper.GetExpression("MRAttachment.FileID", fileID);
			
			return Delete(where);
		}
		
		///<summary>Delete instance from the persistence store based on primary key(s) using a transaction</summary>
		///<param name="transaction">An instance of a Wilson.ORMapper.Transaction to perform operation with.</param>
		public static int DeleteByKey(Wilson.ORMapper.Transaction transaction, short fileID)
		{			
			DBManager db = DBManager.GetInstance();
			QueryHelper helper = db.Engine.QueryHelper;
			string where = helper.GetExpression("MRAttachment.FileID", fileID);
			
			return Delete(transaction, where);
		}		
		#region IObjectHelper
		/// <summary>Indexer to update local member variables</summary>	
		/// <remarks>This indexer is used by the Wilson ORMapper</remarks>
		object IObjectHelper.this[string memberName]
		{
			get {
				switch (memberName) {
					case "_coyID": return _coyID;
					case "_mRNo": return _mRNo;
					case "_customerAccountCode": return _customerAccountCode;
					case "_customerName": return _customerName;
					case "_sONo": return _sONo;
					case "_sODate": return _sODate;
					case "_requiredDate": return _requiredDate;
					case "_fileID": return _fileID;
					case "_fileName": return _fileName;
					case "_fileNameEncrypted": return _fileNameEncrypted;
					case "_createdBy": return _createdBy;
					case "_createdDate": return _createdDate;
					case "_modifiedBy": return _modifiedBy;
					case "_modifiedDate": return _modifiedDate;
									
					default: throw new Exception(string.Format("Mapping: IObjectHelper Get is missing member case {0}", memberName));
				}
			}
			set {
				//handle null values
				if(value == null)
					return;
					
				switch (memberName) {
					case "_coyID": _coyID = (short)value; break;
					case "_mRNo": _mRNo = (string)value; break;
					case "_customerAccountCode": _customerAccountCode = (string)value; break;
					case "_customerName": _customerName = (string)value; break;
					case "_sONo": _sONo = (string)value; break;
					case "_sODate": _sODate = (DateTime)value; break;
					case "_requiredDate": _requiredDate = (DateTime)value; break;
					case "_fileID": _fileID = (short)value; break;
					case "_fileName": _fileName = (string)value; break;
					case "_fileNameEncrypted": _fileNameEncrypted = (string)value; break;
					case "_createdBy": _createdBy = (short)value; break;
					case "_createdDate": _createdDate = (DateTime)value; break;
					case "_modifiedBy": _modifiedBy = (Nullable<short>)value; break;
					case "_modifiedDate": _modifiedDate = (Nullable<DateTime>)value; break;
				
					default: throw new Exception(string.Format("Mapping: IObjectHelper Set is missing member case {0}", memberName));
				}
			}
		}
		#endregion
		
		#region ToString
		///<summary>
		///Overwrites the base ToString method. This is used for AuditTrail purposes.
		///</summary>
		public override string ToString()
		{
			System.Text.StringBuilder stb = new System.Text.StringBuilder(500);
			
			stb.AppendFormat("_coyID={0}\n,", _coyID.ToString() );
			stb.AppendFormat("_mRNo={0}\n,", _mRNo.ToString() );
			stb.AppendFormat("_customerAccountCode={0}\n,", _customerAccountCode.ToString() );
			stb.AppendFormat("_customerName={0}\n,", _customerName.ToString() );
			stb.AppendFormat("_sONo={0}\n,", _sONo.ToString() );
			stb.AppendFormat("_sODate={0}\n,", _sODate.ToString() );
			stb.AppendFormat("_requiredDate={0}\n,", _requiredDate.ToString() );
			stb.AppendFormat("_fileID={0}\n,", _fileID.ToString() );
			stb.AppendFormat("_fileName={0}\n,", _fileName.ToString() );
			stb.AppendFormat("_fileNameEncrypted={0}\n,", _fileNameEncrypted.ToString() );
			stb.AppendFormat("_createdBy={0}\n,", _createdBy.ToString() );
			stb.AppendFormat("_createdDate={0}\n,", _createdDate.ToString() );
			stb.AppendFormat("_modifiedBy={0}\n,", _modifiedBy.ToString() );
			stb.AppendFormat("_modifiedDate={0}\n,", _modifiedDate.ToString() );
							
			
			return stb.ToString();
		}
		#endregion

	}
}
