//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//	   DO NOT MODIFY contents of this file. Changes to this
//	   file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using Wilson.ORMapper;
using eLogixCore;

namespace GMSCore.Entity
{
	///<summary>Database mapping to table MSTCompany</summary>
	[DataObject(true)]
    public partial class MSTCompany : PersistBase<MSTCompany>, IObjectHelper
	{
		#region Properties
	
		private string _code;
		///<summary>Database mapping to column MSTCompany.Code</summary>
		public string Code
		{
			get { return _code; }
			set
			{
				if (_code != value)
				{
					_code = value;
					OnPropertyChanged("Code");
				}
			}
		}
			
		private string _cName = "";
		///<summary>Database mapping to column MSTCompany.CName</summary>
		public string CName
		{
			get { return _cName; }
			set
			{
				if (_cName != value)
				{
					_cName = value;
					OnPropertyChanged("CName");
				}
			}
		}
			
		private string _type = "";
		///<summary>Database mapping to column MSTCompany.Type</summary>
		public string Type
		{
			get { return _type; }
			set
			{
				if (_type != value)
				{
					_type = value;
					OnPropertyChanged("Type");
				}
			}
		}
			
		private string _add1 = "";
		///<summary>Database mapping to column MSTCompany.Add1</summary>
		public string Add1
		{
			get { return _add1; }
			set
			{
				if (_add1 != value)
				{
					_add1 = value;
					OnPropertyChanged("Add1");
				}
			}
		}
			
		private string _add2 = "";
		///<summary>Database mapping to column MSTCompany.Add2</summary>
		public string Add2
		{
			get { return _add2; }
			set
			{
				if (_add2 != value)
				{
					_add2 = value;
					OnPropertyChanged("Add2");
				}
			}
		}
			
		private string _add3 = "";
		///<summary>Database mapping to column MSTCompany.Add3</summary>
		public string Add3
		{
			get { return _add3; }
			set
			{
				if (_add3 != value)
				{
					_add3 = value;
					OnPropertyChanged("Add3");
				}
			}
		}
			
		private string _add4 = "";
		///<summary>Database mapping to column MSTCompany.Add4</summary>
		public string Add4
		{
			get { return _add4; }
			set
			{
				if (_add4 != value)
				{
					_add4 = value;
					OnPropertyChanged("Add4");
				}
			}
		}
			
		private string _pin = "";
		///<summary>Database mapping to column MSTCompany.Pin</summary>
		public string Pin
		{
			get { return _pin; }
			set
			{
				if (_pin != value)
				{
					_pin = value;
					OnPropertyChanged("Pin");
				}
			}
		}
			
		private string _contact = "";
		///<summary>Database mapping to column MSTCompany.Contact</summary>
		public string Contact
		{
			get { return _contact; }
			set
			{
				if (_contact != value)
				{
					_contact = value;
					OnPropertyChanged("Contact");
				}
			}
		}
			
		private double _perCons = 0;
		///<summary>Database mapping to column MSTCompany.PerCons</summary>
		public double PerCons
		{
			get { return _perCons; }
			set
			{
				if (_perCons != value)
				{
					_perCons = value;
					OnPropertyChanged("PerCons");
				}
			}
		}
			
		private string _gSTRegNo = "";
		///<summary>Database mapping to column MSTCompany.GSTRegNo</summary>
		public string GSTRegNo
		{
			get { return _gSTRegNo; }
			set
			{
				if (_gSTRegNo != value)
				{
					_gSTRegNo = value;
					OnPropertyChanged("GSTRegNo");
				}
			}
		}
			
		private string _telephone = "";
		///<summary>Database mapping to column MSTCompany.Telephone</summary>
		public string Telephone
		{
			get { return _telephone; }
			set
			{
				if (_telephone != value)
				{
					_telephone = value;
					OnPropertyChanged("Telephone");
				}
			}
		}
			
		private string _fax = "";
		///<summary>Database mapping to column MSTCompany.Fax</summary>
		public string Fax
		{
			get { return _fax; }
			set
			{
				if (_fax != value)
				{
					_fax = value;
					OnPropertyChanged("Fax");
				}
			}
		}
			
		private string _email = "";
		///<summary>Database mapping to column MSTCompany.Email</summary>
		public string Email
		{
			get { return _email; }
			set
			{
				if (_email != value)
				{
					_email = value;
					OnPropertyChanged("Email");
				}
			}
		}
			
		private string _uRL = "";
		///<summary>Database mapping to column MSTCompany.URL</summary>
		public string URL
		{
			get { return _uRL; }
			set
			{
				if (_uRL != value)
				{
					_uRL = value;
					OnPropertyChanged("URL");
				}
			}
		}
			
		private string _a21DBName = "";
		///<summary>Database mapping to column MSTCompany.A21DBName</summary>
		public string A21DBName
		{
			get { return _a21DBName; }
			set
			{
				if (_a21DBName != value)
				{
					_a21DBName = value;
					OnPropertyChanged("A21DBName");
				}
			}
		}
			
		private string _1195A1No = "";
		///<summary>Database mapping to column MSTCompany.1195A1No</summary>
		public string 1195A1No
		{
			get { return _1195A1No; }
			set
			{
				if (_1195A1No != value)
				{
					_1195A1No = value;
					OnPropertyChanged("1195A1No");
				}
			}
		}
		
		#endregion
		
		///<summary>Initializes a new instance of this class</summary>
		public MSTCompany() : base()
		{
			// Default Constructor
		}
		
		#region IObjectHelper
		/// <summary>Indexer to update local member variables</summary>	
		/// <remarks>This indexer is used by the Wilson ORMapper</remarks>
		object IObjectHelper.this[string memberName]
		{
			get {
				switch (memberName) {
					case "_code": return _code;
					case "_cName": return _cName;
					case "_type": return _type;
					case "_add1": return _add1;
					case "_add2": return _add2;
					case "_add3": return _add3;
					case "_add4": return _add4;
					case "_pin": return _pin;
					case "_contact": return _contact;
					case "_perCons": return _perCons;
					case "_gSTRegNo": return _gSTRegNo;
					case "_telephone": return _telephone;
					case "_fax": return _fax;
					case "_email": return _email;
					case "_uRL": return _uRL;
					case "_a21DBName": return _a21DBName;
					case "_1195A1No": return _1195A1No;
									
					default: throw new Exception(string.Format("Mapping: IObjectHelper Get is missing member case {0}", memberName));
				}
			}
			set {
				//handle null values
				if(value == null)
					return;
					
				switch (memberName) {
					case "_code": _code = (string)value; break;
					case "_cName": _cName = (string)value; break;
					case "_type": _type = (string)value; break;
					case "_add1": _add1 = (string)value; break;
					case "_add2": _add2 = (string)value; break;
					case "_add3": _add3 = (string)value; break;
					case "_add4": _add4 = (string)value; break;
					case "_pin": _pin = (string)value; break;
					case "_contact": _contact = (string)value; break;
					case "_perCons": _perCons = (double)value; break;
					case "_gSTRegNo": _gSTRegNo = (string)value; break;
					case "_telephone": _telephone = (string)value; break;
					case "_fax": _fax = (string)value; break;
					case "_email": _email = (string)value; break;
					case "_uRL": _uRL = (string)value; break;
					case "_a21DBName": _a21DBName = (string)value; break;
					case "_1195A1No": _1195A1No = (string)value; break;
				
					default: throw new Exception(string.Format("Mapping: IObjectHelper Set is missing member case {0}", memberName));
				}
			}
		}
		#endregion
		
		#region ToString
		///<summary>
		///Overwrites the base ToString method. This is used for AuditTrail purposes.
		///</summary>
		public override string ToString()
		{
			System.Text.StringBuilder stb = new System.Text.StringBuilder(500);
			
			stb.AppendFormat("_code={0}\n,", _code.ToString() );
			stb.AppendFormat("_cName={0}\n,", _cName.ToString() );
			stb.AppendFormat("_type={0}\n,", _type.ToString() );
			stb.AppendFormat("_add1={0}\n,", _add1.ToString() );
			stb.AppendFormat("_add2={0}\n,", _add2.ToString() );
			stb.AppendFormat("_add3={0}\n,", _add3.ToString() );
			stb.AppendFormat("_add4={0}\n,", _add4.ToString() );
			stb.AppendFormat("_pin={0}\n,", _pin.ToString() );
			stb.AppendFormat("_contact={0}\n,", _contact.ToString() );
			stb.AppendFormat("_perCons={0}\n,", _perCons.ToString() );
			stb.AppendFormat("_gSTRegNo={0}\n,", _gSTRegNo.ToString() );
			stb.AppendFormat("_telephone={0}\n,", _telephone.ToString() );
			stb.AppendFormat("_fax={0}\n,", _fax.ToString() );
			stb.AppendFormat("_email={0}\n,", _email.ToString() );
			stb.AppendFormat("_uRL={0}\n,", _uRL.ToString() );
			stb.AppendFormat("_a21DBName={0}\n,", _a21DBName.ToString() );
			stb.AppendFormat("_1195A1No={0}\n,", _1195A1No.ToString() );
							
			
			return stb.ToString();
		}
		#endregion

	}
}
