//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//	   DO NOT MODIFY contents of this file. Changes to this
//	   file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using Wilson.ORMapper;
using eLogixCore;

namespace GMSCore.Entity
{
	///<summary>Database mapping to table tbQuotationDetailDescription</summary>
	[DataObject(true)]
    public partial class QuotationDetailDescription : PersistBase<QuotationDetailDescription>, IObjectHelper
	{
		#region Properties
	
		private short _coyID;
		///<summary>Database mapping to column tbQuotationDetailDescription.CoyID</summary>
		[DataObjectField(true, false)]
		public short CoyID
		{
			get { return _coyID; }
			set
			{
				if (_coyID != value)
				{
					_coyID = value;
					OnPropertyChanged("CoyID");
				}
			}
		}
			
		private string _quotationNo;
		///<summary>Database mapping to column tbQuotationDetailDescription.QuotationNo</summary>
		[DataObjectField(true, false)]
		public string QuotationNo
		{
			get { return _quotationNo; }
			set
			{
				if (_quotationNo != value)
				{
					_quotationNo = value;
					OnPropertyChanged("QuotationNo");
				}
			}
		}
			
		private byte _sNNo;
		///<summary>Database mapping to column tbQuotationDetailDescription.SNNo</summary>
		[DataObjectField(true, false)]
		public byte SNNo
		{
			get { return _sNNo; }
			set
			{
				if (_sNNo != value)
				{
					_sNNo = value;
					OnPropertyChanged("SNNo");
				}
			}
		}
			
		private byte _descNo;
		///<summary>Database mapping to column tbQuotationDetailDescription.DescNo</summary>
		[DataObjectField(true, false)]
		public byte DescNo
		{
			get { return _descNo; }
			set
			{
				if (_descNo != value)
				{
					_descNo = value;
					OnPropertyChanged("DescNo");
				}
			}
		}
			
		private string _description = "";
		///<summary>Database mapping to column tbQuotationDetailDescription.Description</summary>
		public string Description
		{
			get { return _description; }
			set
			{
				if (_description != value)
				{
					_description = value;
					OnPropertyChanged("Description");
				}
			}
		}
			
		private byte _revisionNo;
		///<summary>Database mapping to column tbQuotationDetailDescription.RevisionNo</summary>
		[DataObjectField(true, false)]
		public byte RevisionNo
		{
			get { return _revisionNo; }
			set
			{
				if (_revisionNo != value)
				{
					_revisionNo = value;
					OnPropertyChanged("RevisionNo");
				}
			}
		}
			
		private Nullable<byte> _seqID;
		///<summary>Database mapping to column tbQuotationDetailDescription.SeqID</summary>
		public Nullable<byte> SeqID
		{
			get { return _seqID; }
			set
			{
				if (_seqID != value)
				{
					_seqID = value;
					OnPropertyChanged("SeqID");
				}
			}
		}
		
		#endregion
		
		///<summary>Initializes a new instance of this class</summary>
		public QuotationDetailDescription() : base()
		{
			// Default Constructor
		}
		
		///<summary>Retrieve an instance of this class using its ID from the persistence store</summary>
		[DataObjectMethod(DataObjectMethodType.Select)]
        public static QuotationDetailDescription RetrieveByKey(short coyID, string quotationNo, byte sNNo, byte descNo, byte revisionNo)
		{
			DBManager db = DBManager.GetInstance();
			QueryHelper helper = db.Engine.QueryHelper;
			string where = helper.GetExpression("QuotationDetailDescription.CoyID", coyID);
			where += " and ";
			where += helper.GetExpression("QuotationDetailDescription.QuotationNo", quotationNo);
			where += " and ";
			where += helper.GetExpression("QuotationDetailDescription.SNNo", sNNo);
			where += " and ";
			where += helper.GetExpression("QuotationDetailDescription.DescNo", descNo);
			where += " and ";
			where += helper.GetExpression("QuotationDetailDescription.RevisionNo", revisionNo);

			return RetrieveFirst(where);			
		}
		
		///<summary>Delete instance from the persistence store based on primary key(s)</summary>
		[DataObjectMethod(DataObjectMethodType.Delete)]
        public static int DeleteByKey(short coyID, string quotationNo, byte sNNo, byte descNo, byte revisionNo)
		{			
			DBManager db = DBManager.GetInstance();		
			QueryHelper helper = db.Engine.QueryHelper;
			string where = helper.GetExpression("QuotationDetailDescription.CoyID", coyID);
			where += " and ";
			where += helper.GetExpression("QuotationDetailDescription.QuotationNo", quotationNo);
			where += " and ";
			where += helper.GetExpression("QuotationDetailDescription.SNNo", sNNo);
			where += " and ";
			where += helper.GetExpression("QuotationDetailDescription.DescNo", descNo);
			where += " and ";
			where += helper.GetExpression("QuotationDetailDescription.RevisionNo", revisionNo);
			
			return Delete(where);
		}
		
		///<summary>Delete instance from the persistence store based on primary key(s) using a transaction</summary>
		///<param name="transaction">An instance of a Wilson.ORMapper.Transaction to perform operation with.</param>
		public static int DeleteByKey(Wilson.ORMapper.Transaction transaction, short coyID, string quotationNo, byte sNNo, byte descNo, byte revisionNo)
		{			
			DBManager db = DBManager.GetInstance();
			QueryHelper helper = db.Engine.QueryHelper;
			string where = helper.GetExpression("QuotationDetailDescription.CoyID", coyID);
			where += " and ";
			where += helper.GetExpression("QuotationDetailDescription.QuotationNo", quotationNo);
			where += " and ";
			where += helper.GetExpression("QuotationDetailDescription.SNNo", sNNo);
			where += " and ";
			where += helper.GetExpression("QuotationDetailDescription.DescNo", descNo);
			where += " and ";
			where += helper.GetExpression("QuotationDetailDescription.RevisionNo", revisionNo);
			
			return Delete(transaction, where);
		}		
		#region IObjectHelper
		/// <summary>Indexer to update local member variables</summary>	
		/// <remarks>This indexer is used by the Wilson ORMapper</remarks>
		object IObjectHelper.this[string memberName]
		{
			get {
				switch (memberName) {
					case "_coyID": return _coyID;
					case "_quotationNo": return _quotationNo;
					case "_sNNo": return _sNNo;
					case "_descNo": return _descNo;
					case "_description": return _description;
					case "_revisionNo": return _revisionNo;
					case "_seqID": return _seqID;
									
					default: throw new Exception(string.Format("Mapping: IObjectHelper Get is missing member case {0}", memberName));
				}
			}
			set {
				//handle null values
				if(value == null)
					return;
					
				switch (memberName) {
					case "_coyID": _coyID = (short)value; break;
					case "_quotationNo": _quotationNo = (string)value; break;
					case "_sNNo": _sNNo = (byte)value; break;
					case "_descNo": _descNo = (byte)value; break;
					case "_description": _description = (string)value; break;
					case "_revisionNo": _revisionNo = (byte)value; break;
					case "_seqID": _seqID = (Nullable<byte>)value; break;
				
					default: throw new Exception(string.Format("Mapping: IObjectHelper Set is missing member case {0}", memberName));
				}
			}
		}
		#endregion
		
		#region ToString
		///<summary>
		///Overwrites the base ToString method. This is used for AuditTrail purposes.
		///</summary>
		public override string ToString()
		{
			System.Text.StringBuilder stb = new System.Text.StringBuilder(500);
			
			stb.AppendFormat("_coyID={0}\n,", _coyID.ToString() );
			stb.AppendFormat("_quotationNo={0}\n,", _quotationNo.ToString() );
			stb.AppendFormat("_sNNo={0}\n,", _sNNo.ToString() );
			stb.AppendFormat("_descNo={0}\n,", _descNo.ToString() );
			stb.AppendFormat("_description={0}\n,", _description.ToString() );
			stb.AppendFormat("_revisionNo={0}\n,", _revisionNo.ToString() );
			stb.AppendFormat("_seqID={0}\n,", _seqID.ToString() );
							
			
			return stb.ToString();
		}
		#endregion

	}
}
