//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//	   DO NOT MODIFY contents of this file. Changes to this
//	   file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using Wilson.ORMapper;
using eLogixCore;

namespace GMSCore.Entity
{
	///<summary>Database mapping to table tbAccountNOX</summary>
	[DataObject(true)]
    public partial class TbAccountNOX : PersistBase<TbAccountNOX>, IObjectHelper
	{
		#region Properties
	
		private string _accountCode = "";
		///<summary>Database mapping to column tbAccountNOX.AccountCode</summary>
		public string AccountCode
		{
			get { return _accountCode; }
			set
			{
				if (_accountCode != value)
				{
					_accountCode = value;
					OnPropertyChanged("AccountCode");
				}
			}
		}
		
		#endregion
		
		///<summary>Initializes a new instance of this class</summary>
		public TbAccountNOX() : base()
		{
			// Default Constructor
		}
		
		#region IObjectHelper
		/// <summary>Indexer to update local member variables</summary>	
		/// <remarks>This indexer is used by the Wilson ORMapper</remarks>
		object IObjectHelper.this[string memberName]
		{
			get {
				switch (memberName) {
					case "_accountCode": return _accountCode;
									
					default: throw new Exception(string.Format("Mapping: IObjectHelper Get is missing member case {0}", memberName));
				}
			}
			set {
				//handle null values
				if(value == null)
					return;
					
				switch (memberName) {
					case "_accountCode": _accountCode = (string)value; break;
				
					default: throw new Exception(string.Format("Mapping: IObjectHelper Set is missing member case {0}", memberName));
				}
			}
		}
		#endregion
		
		#region ToString
		///<summary>
		///Overwrites the base ToString method. This is used for AuditTrail purposes.
		///</summary>
		public override string ToString()
		{
			System.Text.StringBuilder stb = new System.Text.StringBuilder(500);
			
			stb.AppendFormat("_accountCode={0}\n,", _accountCode.ToString() );
							
			
			return stb.ToString();
		}
		#endregion

	}
}
