//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//	   DO NOT MODIFY contents of this file. Changes to this
//	   file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using Wilson.ORMapper;
using eLogixCore;

namespace GMSCore.Entity
{
	///<summary>Database mapping to table tbChartOfAccounts</summary>
	[DataObject(true)]
    public partial class TbChartOfAccounts : PersistBase<TbChartOfAccounts>, IObjectHelper
	{
		#region Properties
	
		private string _cOAID = "";
		///<summary>Database mapping to column tbChartOfAccounts.COAID</summary>
		public string COAID
		{
			get { return _cOAID; }
			set
			{
				if (_cOAID != value)
				{
					_cOAID = value;
					OnPropertyChanged("COAID");
				}
			}
		}
			
		private double _cOASN = 0;
		///<summary>Database mapping to column tbChartOfAccounts.COASN</summary>
		public double COASN
		{
			get { return _cOASN; }
			set
			{
				if (_cOASN != value)
				{
					_cOASN = value;
					OnPropertyChanged("COASN");
				}
			}
		}
		
		#endregion
		
		///<summary>Initializes a new instance of this class</summary>
		public TbChartOfAccounts() : base()
		{
			// Default Constructor
		}
		
		#region IObjectHelper
		/// <summary>Indexer to update local member variables</summary>	
		/// <remarks>This indexer is used by the Wilson ORMapper</remarks>
		object IObjectHelper.this[string memberName]
		{
			get {
				switch (memberName) {
					case "_cOAID": return _cOAID;
					case "_cOASN": return _cOASN;
									
					default: throw new Exception(string.Format("Mapping: IObjectHelper Get is missing member case {0}", memberName));
				}
			}
			set {
				//handle null values
				if(value == null)
					return;
					
				switch (memberName) {
					case "_cOAID": _cOAID = (string)value; break;
					case "_cOASN": _cOASN = (double)value; break;
				
					default: throw new Exception(string.Format("Mapping: IObjectHelper Set is missing member case {0}", memberName));
				}
			}
		}
		#endregion
		
		#region ToString
		///<summary>
		///Overwrites the base ToString method. This is used for AuditTrail purposes.
		///</summary>
		public override string ToString()
		{
			System.Text.StringBuilder stb = new System.Text.StringBuilder(500);
			
			stb.AppendFormat("_cOAID={0}\n,", _cOAID.ToString() );
			stb.AppendFormat("_cOASN={0}\n,", _cOASN.ToString() );
							
			
			return stb.ToString();
		}
		#endregion

	}
}
