//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//	   DO NOT MODIFY contents of this file. Changes to this
//	   file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using Wilson.ORMapper;
using eLogixCore;

namespace GMSCore.Entity
{
	///<summary>Database mapping to table tbCourse</summary>
	[DataObject(true)]
    public partial class TbCourse : PersistBase<TbCourse>, IObjectHelper
	{
		#region Properties
	
		private int _courseID;
		///<summary>Database mapping to column tbCourse.CourseID</summary>
		[DataObjectField(true, true)]
		public int CourseID
		{
			get { return _courseID; }
			set
			{
				if (_courseID != value)
				{
					_courseID = value;
					OnPropertyChanged("CourseID");
				}
			}
		}
			
		private string _courseCode;
		///<summary>Database mapping to column tbCourse.CourseCode</summary>
		public string CourseCode
		{
			get { return _courseCode; }
			set
			{
				if (_courseCode != value)
				{
					_courseCode = value;
					OnPropertyChanged("CourseCode");
				}
			}
		}
			
		private string _courseTitle;
		///<summary>Database mapping to column tbCourse.CourseTitle</summary>
		public string CourseTitle
		{
			get { return _courseTitle; }
			set
			{
				if (_courseTitle != value)
				{
					_courseTitle = value;
					OnPropertyChanged("CourseTitle");
				}
			}
		}
			
		private short _courseOrganizerID;
		///<summary>Database mapping to column tbCourse.CourseOrganizerID</summary>
		public short CourseOrganizerID
		{
			get { return _courseOrganizerID; }
			set
			{
				if (_courseOrganizerID != value)
				{
					_courseOrganizerID = value;
					OnPropertyChanged("CourseOrganizerID");
				}
			}
		}
			
		private string _courseType;
		///<summary>Database mapping to column tbCourse.CourseType</summary>
		public string CourseType
		{
			get { return _courseType; }
			set
			{
				if (_courseType != value)
				{
					_courseType = value;
					OnPropertyChanged("CourseType");
				}
			}
		}
			
		private bool _requirePTJNPTEF = false;
		///<summary>Database mapping to column tbCourse.RequirePTJNPTEF</summary>
		public bool RequirePTJNPTEF
		{
			get { return _requirePTJNPTEF; }
			set
			{
				if (_requirePTJNPTEF != value)
				{
					_requirePTJNPTEF = value;
					OnPropertyChanged("RequirePTJNPTEF");
				}
			}
		}
			
		private bool _isBonded = false;
		///<summary>Database mapping to column tbCourse.IsBonded</summary>
		public bool IsBonded
		{
			get { return _isBonded; }
			set
			{
				if (_isBonded != value)
				{
					_isBonded = value;
					OnPropertyChanged("IsBonded");
				}
			}
		}
			
		private byte _noOfMonthsBonded = 0;
		///<summary>Database mapping to column tbCourse.NoOfMonthsBonded</summary>
		public byte NoOfMonthsBonded
		{
			get { return _noOfMonthsBonded; }
			set
			{
				if (_noOfMonthsBonded != value)
				{
					_noOfMonthsBonded = value;
					OnPropertyChanged("NoOfMonthsBonded");
				}
			}
		}
			
		private decimal _totalTrainingHours = 0;
		///<summary>Database mapping to column tbCourse.TotalTrainingHours</summary>
		public decimal TotalTrainingHours
		{
			get { return _totalTrainingHours; }
			set
			{
				if (_totalTrainingHours != value)
				{
					_totalTrainingHours = value;
					OnPropertyChanged("TotalTrainingHours");
				}
			}
		}
			
		private string _targetAudience = "";
		///<summary>Database mapping to column tbCourse.TargetAudience</summary>
		public string TargetAudience
		{
			get { return _targetAudience; }
			set
			{
				if (_targetAudience != value)
				{
					_targetAudience = value;
					OnPropertyChanged("TargetAudience");
				}
			}
		}
			
		private string _courseObjective = "";
		///<summary>Database mapping to column tbCourse.CourseObjective</summary>
		public string CourseObjective
		{
			get { return _courseObjective; }
			set
			{
				if (_courseObjective != value)
				{
					_courseObjective = value;
					OnPropertyChanged("CourseObjective");
				}
			}
		}
			
		private string _courseDescription = "";
		///<summary>Database mapping to column tbCourse.CourseDescription</summary>
		public string CourseDescription
		{
			get { return _courseDescription; }
			set
			{
				if (_courseDescription != value)
				{
					_courseDescription = value;
					OnPropertyChanged("CourseDescription");
				}
			}
		}
			
		private string _prerequisite = "";
		///<summary>Database mapping to column tbCourse.Prerequisite</summary>
		public string Prerequisite
		{
			get { return _prerequisite; }
			set
			{
				if (_prerequisite != value)
				{
					_prerequisite = value;
					OnPropertyChanged("Prerequisite");
				}
			}
		}
			
		private decimal _localCourseFee = 0;
		///<summary>Database mapping to column tbCourse.LocalCourseFee</summary>
		public decimal LocalCourseFee
		{
			get { return _localCourseFee; }
			set
			{
				if (_localCourseFee != value)
				{
					_localCourseFee = value;
					OnPropertyChanged("LocalCourseFee");
				}
			}
		}
			
		private decimal _localRegistrationFee = 0;
		///<summary>Database mapping to column tbCourse.LocalRegistrationFee</summary>
		public decimal LocalRegistrationFee
		{
			get { return _localRegistrationFee; }
			set
			{
				if (_localRegistrationFee != value)
				{
					_localRegistrationFee = value;
					OnPropertyChanged("LocalRegistrationFee");
				}
			}
		}
			
		private decimal _localExaminationFee = 0;
		///<summary>Database mapping to column tbCourse.LocalExaminationFee</summary>
		public decimal LocalExaminationFee
		{
			get { return _localExaminationFee; }
			set
			{
				if (_localExaminationFee != value)
				{
					_localExaminationFee = value;
					OnPropertyChanged("LocalExaminationFee");
				}
			}
		}
			
		private decimal _localMembershipFee = 0;
		///<summary>Database mapping to column tbCourse.LocalMembershipFee</summary>
		public decimal LocalMembershipFee
		{
			get { return _localMembershipFee; }
			set
			{
				if (_localMembershipFee != value)
				{
					_localMembershipFee = value;
					OnPropertyChanged("LocalMembershipFee");
				}
			}
		}
			
		private decimal _localGST = 0;
		///<summary>Database mapping to column tbCourse.LocalGST</summary>
		public decimal LocalGST
		{
			get { return _localGST; }
			set
			{
				if (_localGST != value)
				{
					_localGST = value;
					OnPropertyChanged("LocalGST");
				}
			}
		}
			
		private decimal _overseasFlightCost = 0;
		///<summary>Database mapping to column tbCourse.OverseasFlightCost</summary>
		public decimal OverseasFlightCost
		{
			get { return _overseasFlightCost; }
			set
			{
				if (_overseasFlightCost != value)
				{
					_overseasFlightCost = value;
					OnPropertyChanged("OverseasFlightCost");
				}
			}
		}
			
		private decimal _overseasHotelCost = 0;
		///<summary>Database mapping to column tbCourse.OverseasHotelCost</summary>
		public decimal OverseasHotelCost
		{
			get { return _overseasHotelCost; }
			set
			{
				if (_overseasHotelCost != value)
				{
					_overseasHotelCost = value;
					OnPropertyChanged("OverseasHotelCost");
				}
			}
		}
			
		private decimal _overseasTransportCost = 0;
		///<summary>Database mapping to column tbCourse.OverseasTransportCost</summary>
		public decimal OverseasTransportCost
		{
			get { return _overseasTransportCost; }
			set
			{
				if (_overseasTransportCost != value)
				{
					_overseasTransportCost = value;
					OnPropertyChanged("OverseasTransportCost");
				}
			}
		}
			
		private decimal _overseasMealCost = 0;
		///<summary>Database mapping to column tbCourse.OverseasMealCost</summary>
		public decimal OverseasMealCost
		{
			get { return _overseasMealCost; }
			set
			{
				if (_overseasMealCost != value)
				{
					_overseasMealCost = value;
					OnPropertyChanged("OverseasMealCost");
				}
			}
		}
			
		private decimal _overseasOthers = 0;
		///<summary>Database mapping to column tbCourse.OverseasOthers</summary>
		public decimal OverseasOthers
		{
			get { return _overseasOthers; }
			set
			{
				if (_overseasOthers != value)
				{
					_overseasOthers = value;
					OnPropertyChanged("OverseasOthers");
				}
			}
		}
			
		private decimal _overseasSDF = 0;
		///<summary>Database mapping to column tbCourse.OverseasSDF</summary>
		public decimal OverseasSDF
		{
			get { return _overseasSDF; }
			set
			{
				if (_overseasSDF != value)
				{
					_overseasSDF = value;
					OnPropertyChanged("OverseasSDF");
				}
			}
		}
			
		private decimal _sDF = 0;
		///<summary>Database mapping to column tbCourse.SDF</summary>
		public decimal SDF
		{
			get { return _sDF; }
			set
			{
				if (_sDF != value)
				{
					_sDF = value;
					OnPropertyChanged("SDF");
				}
			}
		}
			
		private decimal _sRP = 0;
		///<summary>Database mapping to column tbCourse.SRP</summary>
		public decimal SRP
		{
			get { return _sRP; }
			set
			{
				if (_sRP != value)
				{
					_sRP = value;
					OnPropertyChanged("SRP");
				}
			}
		}
			
		private decimal _otherFunding1 = 0;
		///<summary>Database mapping to column tbCourse.OtherFunding1</summary>
		public decimal OtherFunding1
		{
			get { return _otherFunding1; }
			set
			{
				if (_otherFunding1 != value)
				{
					_otherFunding1 = value;
					OnPropertyChanged("OtherFunding1");
				}
			}
		}
			
		private decimal _otherFunding2 = 0;
		///<summary>Database mapping to column tbCourse.OtherFunding2</summary>
		public decimal OtherFunding2
		{
			get { return _otherFunding2; }
			set
			{
				if (_otherFunding2 != value)
				{
					_otherFunding2 = value;
					OnPropertyChanged("OtherFunding2");
				}
			}
		}
			
		private decimal _otherFunding3 = 0;
		///<summary>Database mapping to column tbCourse.OtherFunding3</summary>
		public decimal OtherFunding3
		{
			get { return _otherFunding3; }
			set
			{
				if (_otherFunding3 != value)
				{
					_otherFunding3 = value;
					OnPropertyChanged("OtherFunding3");
				}
			}
		}
			
		private IList<TbCourseSession> _tbCourseSessionList;
		///<summary>Collection of TbCourseSession objects</summary>
		public IList<TbCourseSession> TbCourseSessionList
		{
			get { return _tbCourseSessionList; }
		}
		
		#endregion
		
		///<summary>Initializes a new instance of this class</summary>
		public TbCourse() : base()
		{
			// Default Constructor
		}
		///<summary>Initializes a new instance of this class</summary>
		///<param name="startTracking">Set to true to begin ORMapper tracking on this instance</param>
		public TbCourse(bool startTracking) : base(startTracking)
		{
			
		}
		
		///<summary>Retrieve an instance of this class using its ID from the persistence store</summary>
		[DataObjectMethod(DataObjectMethodType.Select)]
        public static TbCourse RetrieveByKey(int courseID)
		{
			DBManager db = DBManager.GetInstance();
			return db.Engine.GetObject<TbCourse>(courseID);
		}
		
		///<summary>Delete instance from the persistence store based on primary key(s)</summary>
		[DataObjectMethod(DataObjectMethodType.Delete)]
        public static int DeleteByKey(int courseID)
		{			
			DBManager db = DBManager.GetInstance();		
			QueryHelper helper = db.Engine.QueryHelper;
			string where = helper.GetExpression("TbCourse.CourseID", courseID);
			
			return Delete(where);
		}
		
		///<summary>Delete instance from the persistence store based on primary key(s) using a transaction</summary>
		///<param name="transaction">An instance of a Wilson.ORMapper.Transaction to perform operation with.</param>
		public static int DeleteByKey(Wilson.ORMapper.Transaction transaction, int courseID)
		{			
			DBManager db = DBManager.GetInstance();
			QueryHelper helper = db.Engine.QueryHelper;
			string where = helper.GetExpression("TbCourse.CourseID", courseID);
			
			return Delete(transaction, where);
		}		
		#region IObjectHelper
		/// <summary>Indexer to update local member variables</summary>	
		/// <remarks>This indexer is used by the Wilson ORMapper</remarks>
		object IObjectHelper.this[string memberName]
		{
			get {
				switch (memberName) {
					case "_courseID": return _courseID;
					case "_courseCode": return _courseCode;
					case "_courseTitle": return _courseTitle;
					case "_courseOrganizerID": return _courseOrganizerID;
					case "_courseType": return _courseType;
					case "_requirePTJNPTEF": return _requirePTJNPTEF;
					case "_isBonded": return _isBonded;
					case "_noOfMonthsBonded": return _noOfMonthsBonded;
					case "_totalTrainingHours": return _totalTrainingHours;
					case "_targetAudience": return _targetAudience;
					case "_courseObjective": return _courseObjective;
					case "_courseDescription": return _courseDescription;
					case "_prerequisite": return _prerequisite;
					case "_localCourseFee": return _localCourseFee;
					case "_localRegistrationFee": return _localRegistrationFee;
					case "_localExaminationFee": return _localExaminationFee;
					case "_localMembershipFee": return _localMembershipFee;
					case "_localGST": return _localGST;
					case "_overseasFlightCost": return _overseasFlightCost;
					case "_overseasHotelCost": return _overseasHotelCost;
					case "_overseasTransportCost": return _overseasTransportCost;
					case "_overseasMealCost": return _overseasMealCost;
					case "_overseasOthers": return _overseasOthers;
					case "_overseasSDF": return _overseasSDF;
					case "_sDF": return _sDF;
					case "_sRP": return _sRP;
					case "_otherFunding1": return _otherFunding1;
					case "_otherFunding2": return _otherFunding2;
					case "_otherFunding3": return _otherFunding3;
					case "_tbCourseSessionList": return _tbCourseSessionList;
									
					default: throw new Exception(string.Format("Mapping: IObjectHelper Get is missing member case {0}", memberName));
				}
			}
			set {
				//handle null values
				if(value == null)
					return;
					
				switch (memberName) {
					case "_courseID": _courseID = (int)value; break;
					case "_courseCode": _courseCode = (string)value; break;
					case "_courseTitle": _courseTitle = (string)value; break;
					case "_courseOrganizerID": _courseOrganizerID = (short)value; break;
					case "_courseType": _courseType = (string)value; break;
					case "_requirePTJNPTEF": _requirePTJNPTEF = (bool)value; break;
					case "_isBonded": _isBonded = (bool)value; break;
					case "_noOfMonthsBonded": _noOfMonthsBonded = (byte)value; break;
					case "_totalTrainingHours": _totalTrainingHours = (decimal)value; break;
					case "_targetAudience": _targetAudience = (string)value; break;
					case "_courseObjective": _courseObjective = (string)value; break;
					case "_courseDescription": _courseDescription = (string)value; break;
					case "_prerequisite": _prerequisite = (string)value; break;
					case "_localCourseFee": _localCourseFee = (decimal)value; break;
					case "_localRegistrationFee": _localRegistrationFee = (decimal)value; break;
					case "_localExaminationFee": _localExaminationFee = (decimal)value; break;
					case "_localMembershipFee": _localMembershipFee = (decimal)value; break;
					case "_localGST": _localGST = (decimal)value; break;
					case "_overseasFlightCost": _overseasFlightCost = (decimal)value; break;
					case "_overseasHotelCost": _overseasHotelCost = (decimal)value; break;
					case "_overseasTransportCost": _overseasTransportCost = (decimal)value; break;
					case "_overseasMealCost": _overseasMealCost = (decimal)value; break;
					case "_overseasOthers": _overseasOthers = (decimal)value; break;
					case "_overseasSDF": _overseasSDF = (decimal)value; break;
					case "_sDF": _sDF = (decimal)value; break;
					case "_sRP": _sRP = (decimal)value; break;
					case "_otherFunding1": _otherFunding1 = (decimal)value; break;
					case "_otherFunding2": _otherFunding2 = (decimal)value; break;
					case "_otherFunding3": _otherFunding3 = (decimal)value; break;
					case "_tbCourseSessionList": _tbCourseSessionList = (IList<TbCourseSession>)value; break;
				
					default: throw new Exception(string.Format("Mapping: IObjectHelper Set is missing member case {0}", memberName));
				}
			}
		}
		#endregion
		
		#region ToString
		///<summary>
		///Overwrites the base ToString method. This is used for AuditTrail purposes.
		///</summary>
		public override string ToString()
		{
			System.Text.StringBuilder stb = new System.Text.StringBuilder(500);
			
			stb.AppendFormat("_courseID={0}\n,", _courseID.ToString() );
			stb.AppendFormat("_courseCode={0}\n,", _courseCode.ToString() );
			stb.AppendFormat("_courseTitle={0}\n,", _courseTitle.ToString() );
			stb.AppendFormat("_courseOrganizerID={0}\n,", _courseOrganizerID.ToString() );
			stb.AppendFormat("_courseType={0}\n,", _courseType.ToString() );
			stb.AppendFormat("_requirePTJNPTEF={0}\n,", _requirePTJNPTEF.ToString() );
			stb.AppendFormat("_isBonded={0}\n,", _isBonded.ToString() );
			stb.AppendFormat("_noOfMonthsBonded={0}\n,", _noOfMonthsBonded.ToString() );
			stb.AppendFormat("_totalTrainingHours={0}\n,", _totalTrainingHours.ToString() );
			stb.AppendFormat("_targetAudience={0}\n,", _targetAudience.ToString() );
			stb.AppendFormat("_courseObjective={0}\n,", _courseObjective.ToString() );
			stb.AppendFormat("_courseDescription={0}\n,", _courseDescription.ToString() );
			stb.AppendFormat("_prerequisite={0}\n,", _prerequisite.ToString() );
			stb.AppendFormat("_localCourseFee={0}\n,", _localCourseFee.ToString() );
			stb.AppendFormat("_localRegistrationFee={0}\n,", _localRegistrationFee.ToString() );
			stb.AppendFormat("_localExaminationFee={0}\n,", _localExaminationFee.ToString() );
			stb.AppendFormat("_localMembershipFee={0}\n,", _localMembershipFee.ToString() );
			stb.AppendFormat("_localGST={0}\n,", _localGST.ToString() );
			stb.AppendFormat("_overseasFlightCost={0}\n,", _overseasFlightCost.ToString() );
			stb.AppendFormat("_overseasHotelCost={0}\n,", _overseasHotelCost.ToString() );
			stb.AppendFormat("_overseasTransportCost={0}\n,", _overseasTransportCost.ToString() );
			stb.AppendFormat("_overseasMealCost={0}\n,", _overseasMealCost.ToString() );
			stb.AppendFormat("_overseasOthers={0}\n,", _overseasOthers.ToString() );
			stb.AppendFormat("_overseasSDF={0}\n,", _overseasSDF.ToString() );
			stb.AppendFormat("_sDF={0}\n,", _sDF.ToString() );
			stb.AppendFormat("_sRP={0}\n,", _sRP.ToString() );
			stb.AppendFormat("_otherFunding1={0}\n,", _otherFunding1.ToString() );
			stb.AppendFormat("_otherFunding2={0}\n,", _otherFunding2.ToString() );
			stb.AppendFormat("_otherFunding3={0}\n,", _otherFunding3.ToString() );
							
			
			return stb.ToString();
		}
		#endregion

	}
}
