//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//	   DO NOT MODIFY contents of this file. Changes to this
//	   file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using Wilson.ORMapper;
using eLogixCore;

namespace GMSCore.Entity
{
	///<summary>Database mapping to table tbForeignExchangeRate</summary>
	[DataObject(true)]
    public partial class TbForeignExchangeRate : PersistBase<TbForeignExchangeRate>, IObjectHelper
	{
		#region Properties
	
		private string _homeCurrencyCode;
		///<summary>Database mapping to column tbForeignExchangeRate.HomeCurrencyCode</summary>
		[DataObjectField(true, false)]
		public string HomeCurrencyCode
		{
			get { return _homeCurrencyCode; }
			set
			{
				if (_homeCurrencyCode != value)
				{
					_homeCurrencyCode = value;
					OnPropertyChanged("HomeCurrencyCode");
				}
			}
		}
			
		private string _foreignCurrencyCode;
		///<summary>Database mapping to column tbForeignExchangeRate.ForeignCurrencyCode</summary>
		[DataObjectField(true, false)]
		public string ForeignCurrencyCode
		{
			get { return _foreignCurrencyCode; }
			set
			{
				if (_foreignCurrencyCode != value)
				{
					_foreignCurrencyCode = value;
					OnPropertyChanged("ForeignCurrencyCode");
				}
			}
		}
			
		private decimal _buyRate = 0;
		///<summary>Database mapping to column tbForeignExchangeRate.BuyRate</summary>
		public decimal BuyRate
		{
			get { return _buyRate; }
			set
			{
				if (_buyRate != value)
				{
					_buyRate = value;
					OnPropertyChanged("BuyRate");
				}
			}
		}
			
		private decimal _sellRate = 0;
		///<summary>Database mapping to column tbForeignExchangeRate.SellRate</summary>
		public decimal SellRate
		{
			get { return _sellRate; }
			set
			{
				if (_sellRate != value)
				{
					_sellRate = value;
					OnPropertyChanged("SellRate");
				}
			}
		}
			
		private decimal _monthEndRate = 0;
		///<summary>Database mapping to column tbForeignExchangeRate.MonthEndRate</summary>
		public decimal MonthEndRate
		{
			get { return _monthEndRate; }
			set
			{
				if (_monthEndRate != value)
				{
					_monthEndRate = value;
					OnPropertyChanged("MonthEndRate");
				}
			}
		}
			
		private decimal _averageRate = 0;
		///<summary>Database mapping to column tbForeignExchangeRate.AverageRate</summary>
		public decimal AverageRate
		{
			get { return _averageRate; }
			set
			{
				if (_averageRate != value)
				{
					_averageRate = value;
					OnPropertyChanged("AverageRate");
				}
			}
		}
			
		private bool _isInEffect = false;
		///<summary>Database mapping to column tbForeignExchangeRate.IsInEffect</summary>
		public bool IsInEffect
		{
			get { return _isInEffect; }
			set
			{
				if (_isInEffect != value)
				{
					_isInEffect = value;
					OnPropertyChanged("IsInEffect");
				}
			}
		}
			
		private short _createdBy = 0;
		///<summary>Database mapping to column tbForeignExchangeRate.CreatedBy</summary>
		public short CreatedBy
		{
			get { return _createdBy; }
			set
			{
				if (_createdBy != value)
				{
					_createdBy = value;
					OnPropertyChanged("CreatedBy");
				}
			}
		}
			
		private DateTime _createdDate;
		///<summary>Database mapping to column tbForeignExchangeRate.CreatedDate</summary>
		[DataObjectField(true, false)]
		public DateTime CreatedDate
		{
			get { return _createdDate; }
			set
			{
				if (_createdDate != value)
				{
					_createdDate = value;
					OnPropertyChanged("CreatedDate");
				}
			}
		}
			
		private short _modifiedBy = 0;
		///<summary>Database mapping to column tbForeignExchangeRate.ModifiedBy</summary>
		public short ModifiedBy
		{
			get { return _modifiedBy; }
			set
			{
				if (_modifiedBy != value)
				{
					_modifiedBy = value;
					OnPropertyChanged("ModifiedBy");
				}
			}
		}
			
		private DateTime _modifiedDate = DateTime.Parse("01/01/1900 00:00:00");
		///<summary>Database mapping to column tbForeignExchangeRate.ModifiedDate</summary>
		public DateTime ModifiedDate
		{
			get { return _modifiedDate; }
			set
			{
				if (_modifiedDate != value)
				{
					_modifiedDate = value;
					OnPropertyChanged("ModifiedDate");
				}
			}
		}
		
		#endregion
		
		///<summary>Initializes a new instance of this class</summary>
		public TbForeignExchangeRate() : base()
		{
			// Default Constructor
		}
		
		///<summary>Retrieve an instance of this class using its ID from the persistence store</summary>
		[DataObjectMethod(DataObjectMethodType.Select)]
        public static TbForeignExchangeRate RetrieveByKey(string homeCurrencyCode, string foreignCurrencyCode, DateTime createdDate)
		{
			DBManager db = DBManager.GetInstance();
			QueryHelper helper = db.Engine.QueryHelper;
			string where = helper.GetExpression("TbForeignExchangeRate.HomeCurrencyCode", homeCurrencyCode);
			where += " and ";
			where += helper.GetExpression("TbForeignExchangeRate.ForeignCurrencyCode", foreignCurrencyCode);
			where += " and ";
			where += helper.GetExpression("TbForeignExchangeRate.CreatedDate", createdDate);

			return RetrieveFirst(where);			
		}
		
		///<summary>Delete instance from the persistence store based on primary key(s)</summary>
		[DataObjectMethod(DataObjectMethodType.Delete)]
        public static int DeleteByKey(string homeCurrencyCode, string foreignCurrencyCode, DateTime createdDate)
		{			
			DBManager db = DBManager.GetInstance();		
			QueryHelper helper = db.Engine.QueryHelper;
			string where = helper.GetExpression("TbForeignExchangeRate.HomeCurrencyCode", homeCurrencyCode);
			where += " and ";
			where += helper.GetExpression("TbForeignExchangeRate.ForeignCurrencyCode", foreignCurrencyCode);
			where += " and ";
			where += helper.GetExpression("TbForeignExchangeRate.CreatedDate", createdDate);
			
			return Delete(where);
		}
		
		///<summary>Delete instance from the persistence store based on primary key(s) using a transaction</summary>
		///<param name="transaction">An instance of a Wilson.ORMapper.Transaction to perform operation with.</param>
		public static int DeleteByKey(Wilson.ORMapper.Transaction transaction, string homeCurrencyCode, string foreignCurrencyCode, DateTime createdDate)
		{			
			DBManager db = DBManager.GetInstance();
			QueryHelper helper = db.Engine.QueryHelper;
			string where = helper.GetExpression("TbForeignExchangeRate.HomeCurrencyCode", homeCurrencyCode);
			where += " and ";
			where += helper.GetExpression("TbForeignExchangeRate.ForeignCurrencyCode", foreignCurrencyCode);
			where += " and ";
			where += helper.GetExpression("TbForeignExchangeRate.CreatedDate", createdDate);
			
			return Delete(transaction, where);
		}		
		#region IObjectHelper
		/// <summary>Indexer to update local member variables</summary>	
		/// <remarks>This indexer is used by the Wilson ORMapper</remarks>
		object IObjectHelper.this[string memberName]
		{
			get {
				switch (memberName) {
					case "_homeCurrencyCode": return _homeCurrencyCode;
					case "_foreignCurrencyCode": return _foreignCurrencyCode;
					case "_buyRate": return _buyRate;
					case "_sellRate": return _sellRate;
					case "_monthEndRate": return _monthEndRate;
					case "_averageRate": return _averageRate;
					case "_isInEffect": return _isInEffect;
					case "_createdBy": return _createdBy;
					case "_createdDate": return _createdDate;
					case "_modifiedBy": return _modifiedBy;
					case "_modifiedDate": return _modifiedDate;
									
					default: throw new Exception(string.Format("Mapping: IObjectHelper Get is missing member case {0}", memberName));
				}
			}
			set {
				//handle null values
				if(value == null)
					return;
					
				switch (memberName) {
					case "_homeCurrencyCode": _homeCurrencyCode = (string)value; break;
					case "_foreignCurrencyCode": _foreignCurrencyCode = (string)value; break;
					case "_buyRate": _buyRate = (decimal)value; break;
					case "_sellRate": _sellRate = (decimal)value; break;
					case "_monthEndRate": _monthEndRate = (decimal)value; break;
					case "_averageRate": _averageRate = (decimal)value; break;
					case "_isInEffect": _isInEffect = (bool)value; break;
					case "_createdBy": _createdBy = (short)value; break;
					case "_createdDate": _createdDate = (DateTime)value; break;
					case "_modifiedBy": _modifiedBy = (short)value; break;
					case "_modifiedDate": _modifiedDate = (DateTime)value; break;
				
					default: throw new Exception(string.Format("Mapping: IObjectHelper Set is missing member case {0}", memberName));
				}
			}
		}
		#endregion
		
		#region ToString
		///<summary>
		///Overwrites the base ToString method. This is used for AuditTrail purposes.
		///</summary>
		public override string ToString()
		{
			System.Text.StringBuilder stb = new System.Text.StringBuilder(500);
			
			stb.AppendFormat("_homeCurrencyCode={0}\n,", _homeCurrencyCode.ToString() );
			stb.AppendFormat("_foreignCurrencyCode={0}\n,", _foreignCurrencyCode.ToString() );
			stb.AppendFormat("_buyRate={0}\n,", _buyRate.ToString() );
			stb.AppendFormat("_sellRate={0}\n,", _sellRate.ToString() );
			stb.AppendFormat("_monthEndRate={0}\n,", _monthEndRate.ToString() );
			stb.AppendFormat("_averageRate={0}\n,", _averageRate.ToString() );
			stb.AppendFormat("_isInEffect={0}\n,", _isInEffect.ToString() );
			stb.AppendFormat("_createdBy={0}\n,", _createdBy.ToString() );
			stb.AppendFormat("_createdDate={0}\n,", _createdDate.ToString() );
			stb.AppendFormat("_modifiedBy={0}\n,", _modifiedBy.ToString() );
			stb.AppendFormat("_modifiedDate={0}\n,", _modifiedDate.ToString() );
							
			
			return stb.ToString();
		}
		#endregion

	}
}
