//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//	   DO NOT MODIFY contents of this file. Changes to this
//	   file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using Wilson.ORMapper;
using eLogixCore;

namespace GMSCore.Entity
{
	///<summary>Database mapping to table tbMapUser</summary>
	[DataObject(true)]
    public partial class TbMapUser : PersistBase<TbMapUser>, IObjectHelper
	{
		#region Properties
	
		private string _username = "";
		///<summary>Database mapping to column tbMapUser.Username</summary>
		public string Username
		{
			get { return _username; }
			set
			{
				if (_username != value)
				{
					_username = value;
					OnPropertyChanged("Username");
				}
			}
		}
			
		private int _gMSUserId = 0;
		///<summary>Database mapping to column tbMapUser.GMSUserId</summary>
		public int GMSUserId
		{
			get { return _gMSUserId; }
			set
			{
				if (_gMSUserId != value)
				{
					_gMSUserId = value;
					OnPropertyChanged("GMSUserId");
				}
			}
		}
			
		private int _gMSNGGUserId = 0;
		///<summary>Database mapping to column tbMapUser.GMSNGGUserId</summary>
		public int GMSNGGUserId
		{
			get { return _gMSNGGUserId; }
			set
			{
				if (_gMSNGGUserId != value)
				{
					_gMSNGGUserId = value;
					OnPropertyChanged("GMSNGGUserId");
				}
			}
		}
		
		#endregion
		
		///<summary>Initializes a new instance of this class</summary>
		public TbMapUser() : base()
		{
			// Default Constructor
		}
		
		#region IObjectHelper
		/// <summary>Indexer to update local member variables</summary>	
		/// <remarks>This indexer is used by the Wilson ORMapper</remarks>
		object IObjectHelper.this[string memberName]
		{
			get {
				switch (memberName) {
					case "_username": return _username;
					case "_gMSUserId": return _gMSUserId;
					case "_gMSNGGUserId": return _gMSNGGUserId;
									
					default: throw new Exception(string.Format("Mapping: IObjectHelper Get is missing member case {0}", memberName));
				}
			}
			set {
				//handle null values
				if(value == null)
					return;
					
				switch (memberName) {
					case "_username": _username = (string)value; break;
					case "_gMSUserId": _gMSUserId = (int)value; break;
					case "_gMSNGGUserId": _gMSNGGUserId = (int)value; break;
				
					default: throw new Exception(string.Format("Mapping: IObjectHelper Set is missing member case {0}", memberName));
				}
			}
		}
		#endregion
		
		#region ToString
		///<summary>
		///Overwrites the base ToString method. This is used for AuditTrail purposes.
		///</summary>
		public override string ToString()
		{
			System.Text.StringBuilder stb = new System.Text.StringBuilder(500);
			
			stb.AppendFormat("_username={0}\n,", _username.ToString() );
			stb.AppendFormat("_gMSUserId={0}\n,", _gMSUserId.ToString() );
			stb.AppendFormat("_gMSNGGUserId={0}\n,", _gMSNGGUserId.ToString() );
							
			
			return stb.ToString();
		}
		#endregion

	}
}
