//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//	   DO NOT MODIFY contents of this file. Changes to this
//	   file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using Wilson.ORMapper;
using eLogixCore;

namespace GMSCore.Entity
{
	///<summary>Database mapping to table tbProspective</summary>
	[DataObject(true)]
    public partial class TbProspective : PersistBase<TbProspective>, IObjectHelper
	{
		#region Properties
	
		private string _prospectiveName = "";
		///<summary>Database mapping to column tbProspective.ProspectiveName</summary>
		public string ProspectiveName
		{
			get { return _prospectiveName; }
			set
			{
				if (_prospectiveName != value)
				{
					_prospectiveName = value;
					OnPropertyChanged("ProspectiveName");
				}
			}
		}
			
		private string _productInterested = "";
		///<summary>Database mapping to column tbProspective.ProductInterested</summary>
		public string ProductInterested
		{
			get { return _productInterested; }
			set
			{
				if (_productInterested != value)
				{
					_productInterested = value;
					OnPropertyChanged("ProductInterested");
				}
			}
		}
		
		#endregion
		
		///<summary>Initializes a new instance of this class</summary>
		public TbProspective() : base()
		{
			// Default Constructor
		}
		
		#region IObjectHelper
		/// <summary>Indexer to update local member variables</summary>	
		/// <remarks>This indexer is used by the Wilson ORMapper</remarks>
		object IObjectHelper.this[string memberName]
		{
			get {
				switch (memberName) {
					case "_prospectiveName": return _prospectiveName;
					case "_productInterested": return _productInterested;
									
					default: throw new Exception(string.Format("Mapping: IObjectHelper Get is missing member case {0}", memberName));
				}
			}
			set {
				//handle null values
				if(value == null)
					return;
					
				switch (memberName) {
					case "_prospectiveName": _prospectiveName = (string)value; break;
					case "_productInterested": _productInterested = (string)value; break;
				
					default: throw new Exception(string.Format("Mapping: IObjectHelper Set is missing member case {0}", memberName));
				}
			}
		}
		#endregion
		
		#region ToString
		///<summary>
		///Overwrites the base ToString method. This is used for AuditTrail purposes.
		///</summary>
		public override string ToString()
		{
			System.Text.StringBuilder stb = new System.Text.StringBuilder(500);
			
			stb.AppendFormat("_prospectiveName={0}\n,", _prospectiveName.ToString() );
			stb.AppendFormat("_productInterested={0}\n,", _productInterested.ToString() );
							
			
			return stb.ToString();
		}
		#endregion

	}
}
