//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//	   DO NOT MODIFY contents of this file. Changes to this
//	   file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using Wilson.ORMapper;
using eLogixCore;

namespace GMSCore.Entity
{
	///<summary>Database mapping to table tbSalesPersonMaster</summary>
	[DataObject(true)]
    public partial class TbSalesPersonMaster : PersistBase<TbSalesPersonMaster>, IObjectHelper
	{
		#region Properties
	
		private short _coyID;
		///<summary>Database mapping to column tbSalesPersonMaster.CoyID</summary>
		public short CoyID
		{
			get { return _coyID; }
			set
			{
				if (_coyID != value)
				{
					_coyID = value;
					OnPropertyChanged("CoyID");
				}
			}
		}
			
		private short _salesPersonMasterID;
		///<summary>Database mapping to column tbSalesPersonMaster.SalesPersonMasterID</summary>
		[DataObjectField(true, true)]
		public short SalesPersonMasterID
		{
			get { return _salesPersonMasterID; }
			set
			{
				if (_salesPersonMasterID != value)
				{
					_salesPersonMasterID = value;
					OnPropertyChanged("SalesPersonMasterID");
				}
			}
		}
			
		private string _salesPersonMasterName;
		///<summary>Database mapping to column tbSalesPersonMaster.SalesPersonMasterName</summary>
		public string SalesPersonMasterName
		{
			get { return _salesPersonMasterName; }
			set
			{
				if (_salesPersonMasterName != value)
				{
					_salesPersonMasterName = value;
					OnPropertyChanged("SalesPersonMasterName");
				}
			}
		}
			
		private double _gPQ = 0;
		///<summary>Database mapping to column tbSalesPersonMaster.GPQ</summary>
		public double GPQ
		{
			get { return _gPQ; }
			set
			{
				if (_gPQ != value)
				{
					_gPQ = value;
					OnPropertyChanged("GPQ");
				}
			}
		}
			
		private double _commissionRate = 0;
		///<summary>Database mapping to column tbSalesPersonMaster.CommissionRate</summary>
		public double CommissionRate
		{
			get { return _commissionRate; }
			set
			{
				if (_commissionRate != value)
				{
					_commissionRate = value;
					OnPropertyChanged("CommissionRate");
				}
			}
		}
			
		private short _createdBy = 0;
		///<summary>Database mapping to column tbSalesPersonMaster.CreatedBy</summary>
		public short CreatedBy
		{
			get { return _createdBy; }
			set
			{
				if (_createdBy != value)
				{
					_createdBy = value;
					OnPropertyChanged("CreatedBy");
				}
			}
		}
			
		private DateTime _createdDate = DateTime.Parse("01/01/1900 00:00:00");
		///<summary>Database mapping to column tbSalesPersonMaster.CreatedDate</summary>
		public DateTime CreatedDate
		{
			get { return _createdDate; }
			set
			{
				if (_createdDate != value)
				{
					_createdDate = value;
					OnPropertyChanged("CreatedDate");
				}
			}
		}
			
		private short _modifiedBY = 0;
		///<summary>Database mapping to column tbSalesPersonMaster.ModifiedBY</summary>
		public short ModifiedBY
		{
			get { return _modifiedBY; }
			set
			{
				if (_modifiedBY != value)
				{
					_modifiedBY = value;
					OnPropertyChanged("ModifiedBY");
				}
			}
		}
			
		private DateTime _modifiedDate = DateTime.Parse("01/01/1900 00:00:00");
		///<summary>Database mapping to column tbSalesPersonMaster.ModifiedDate</summary>
		public DateTime ModifiedDate
		{
			get { return _modifiedDate; }
			set
			{
				if (_modifiedDate != value)
				{
					_modifiedDate = value;
					OnPropertyChanged("ModifiedDate");
				}
			}
		}
			
		private IList<TbSalesPersonMapping> _tbSalesPersonMappingList;
		///<summary>Collection of TbSalesPersonMapping objects</summary>
		public IList<TbSalesPersonMapping> TbSalesPersonMappingList
		{
			get { return _tbSalesPersonMappingList; }
		}
			
		private IList<TbEntertainmentExpense> _tbEntertainmentExpenseList;
		///<summary>Collection of TbEntertainmentExpense objects</summary>
		public IList<TbEntertainmentExpense> TbEntertainmentExpenseList
		{
			get { return _tbEntertainmentExpenseList; }
		}
			
		private IList<TbSalesPersonRecord> _tbSalesPersonRecordList;
		///<summary>Collection of TbSalesPersonRecord objects</summary>
		public IList<TbSalesPersonRecord> TbSalesPersonRecordList
		{
			get { return _tbSalesPersonRecordList; }
		}
		
		#endregion
		
		///<summary>Initializes a new instance of this class</summary>
		public TbSalesPersonMaster() : base()
		{
			// Default Constructor
		}
		///<summary>Initializes a new instance of this class</summary>
		///<param name="startTracking">Set to true to begin ORMapper tracking on this instance</param>
		public TbSalesPersonMaster(bool startTracking) : base(startTracking)
		{
			
		}
		
		///<summary>Retrieve an instance of this class using its ID from the persistence store</summary>
		[DataObjectMethod(DataObjectMethodType.Select)]
        public static TbSalesPersonMaster RetrieveByKey(short salesPersonMasterID)
		{
			DBManager db = DBManager.GetInstance();
			return db.Engine.GetObject<TbSalesPersonMaster>(salesPersonMasterID);
		}
		
		///<summary>Delete instance from the persistence store based on primary key(s)</summary>
		[DataObjectMethod(DataObjectMethodType.Delete)]
        public static int DeleteByKey(short salesPersonMasterID)
		{			
			DBManager db = DBManager.GetInstance();		
			QueryHelper helper = db.Engine.QueryHelper;
			string where = helper.GetExpression("TbSalesPersonMaster.SalesPersonMasterID", salesPersonMasterID);
			
			return Delete(where);
		}
		
		///<summary>Delete instance from the persistence store based on primary key(s) using a transaction</summary>
		///<param name="transaction">An instance of a Wilson.ORMapper.Transaction to perform operation with.</param>
		public static int DeleteByKey(Wilson.ORMapper.Transaction transaction, short salesPersonMasterID)
		{			
			DBManager db = DBManager.GetInstance();
			QueryHelper helper = db.Engine.QueryHelper;
			string where = helper.GetExpression("TbSalesPersonMaster.SalesPersonMasterID", salesPersonMasterID);
			
			return Delete(transaction, where);
		}		
		#region IObjectHelper
		/// <summary>Indexer to update local member variables</summary>	
		/// <remarks>This indexer is used by the Wilson ORMapper</remarks>
		object IObjectHelper.this[string memberName]
		{
			get {
				switch (memberName) {
					case "_coyID": return _coyID;
					case "_salesPersonMasterID": return _salesPersonMasterID;
					case "_salesPersonMasterName": return _salesPersonMasterName;
					case "_gPQ": return _gPQ;
					case "_commissionRate": return _commissionRate;
					case "_createdBy": return _createdBy;
					case "_createdDate": return _createdDate;
					case "_modifiedBY": return _modifiedBY;
					case "_modifiedDate": return _modifiedDate;
					case "_tbSalesPersonMappingList": return _tbSalesPersonMappingList;
					case "_tbEntertainmentExpenseList": return _tbEntertainmentExpenseList;
					case "_tbSalesPersonRecordList": return _tbSalesPersonRecordList;
									
					default: throw new Exception(string.Format("Mapping: IObjectHelper Get is missing member case {0}", memberName));
				}
			}
			set {
				//handle null values
				if(value == null)
					return;
					
				switch (memberName) {
					case "_coyID": _coyID = (short)value; break;
					case "_salesPersonMasterID": _salesPersonMasterID = (short)value; break;
					case "_salesPersonMasterName": _salesPersonMasterName = (string)value; break;
					case "_gPQ": _gPQ = (double)value; break;
					case "_commissionRate": _commissionRate = (double)value; break;
					case "_createdBy": _createdBy = (short)value; break;
					case "_createdDate": _createdDate = (DateTime)value; break;
					case "_modifiedBY": _modifiedBY = (short)value; break;
					case "_modifiedDate": _modifiedDate = (DateTime)value; break;
					case "_tbSalesPersonMappingList": _tbSalesPersonMappingList = (IList<TbSalesPersonMapping>)value; break;
					case "_tbEntertainmentExpenseList": _tbEntertainmentExpenseList = (IList<TbEntertainmentExpense>)value; break;
					case "_tbSalesPersonRecordList": _tbSalesPersonRecordList = (IList<TbSalesPersonRecord>)value; break;
				
					default: throw new Exception(string.Format("Mapping: IObjectHelper Set is missing member case {0}", memberName));
				}
			}
		}
		#endregion
		
		#region ToString
		///<summary>
		///Overwrites the base ToString method. This is used for AuditTrail purposes.
		///</summary>
		public override string ToString()
		{
			System.Text.StringBuilder stb = new System.Text.StringBuilder(500);
			
			stb.AppendFormat("_coyID={0}\n,", _coyID.ToString() );
			stb.AppendFormat("_salesPersonMasterID={0}\n,", _salesPersonMasterID.ToString() );
			stb.AppendFormat("_salesPersonMasterName={0}\n,", _salesPersonMasterName.ToString() );
			stb.AppendFormat("_gPQ={0}\n,", _gPQ.ToString() );
			stb.AppendFormat("_commissionRate={0}\n,", _commissionRate.ToString() );
			stb.AppendFormat("_createdBy={0}\n,", _createdBy.ToString() );
			stb.AppendFormat("_createdDate={0}\n,", _createdDate.ToString() );
			stb.AppendFormat("_modifiedBY={0}\n,", _modifiedBY.ToString() );
			stb.AppendFormat("_modifiedDate={0}\n,", _modifiedDate.ToString() );
							
			
			return stb.ToString();
		}
		#endregion

	}
}
