//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//	   DO NOT MODIFY contents of this file. Changes to this
//	   file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using Wilson.ORMapper;
using eLogixCore;

namespace GMSCore.Entity
{
	///<summary>Database mapping to table tbTransactionApproval</summary>
	[DataObject(true)]
    public partial class TbTransactionApproval : PersistBase<TbTransactionApproval>, IObjectHelper
	{
		#region Properties
	
		private short _coyID;
		///<summary>Database mapping to column tbTransactionApproval.CoyID</summary>
		[DataObjectField(true, false)]
		public short CoyID
		{
			get { return _coyID; }
			set
			{
				if (_coyID != value)
				{
					_coyID = value;
					OnPropertyChanged("CoyID");
				}
			}
		}
			
		private string _trnType;
		///<summary>Database mapping to column tbTransactionApproval.TrnType</summary>
		[DataObjectField(true, false)]
		public string TrnType
		{
			get { return _trnType; }
			set
			{
				if (_trnType != value)
				{
					_trnType = value;
					OnPropertyChanged("TrnType");
				}
			}
		}
			
		private string _approvalType;
		///<summary>Database mapping to column tbTransactionApproval.ApprovalType</summary>
		[DataObjectField(true, false)]
		public string ApprovalType
		{
			get { return _approvalType; }
			set
			{
				if (_approvalType != value)
				{
					_approvalType = value;
					OnPropertyChanged("ApprovalType");
				}
			}
		}
			
		private string _trnNo;
		///<summary>Database mapping to column tbTransactionApproval.TrnNo</summary>
		[DataObjectField(true, false)]
		public string TrnNo
		{
			get { return _trnNo; }
			set
			{
				if (_trnNo != value)
				{
					_trnNo = value;
					OnPropertyChanged("TrnNo");
				}
			}
		}
			
		private string _approvalStatus = "";
		///<summary>Database mapping to column tbTransactionApproval.ApprovalStatus</summary>
		public string ApprovalStatus
		{
			get { return _approvalStatus; }
			set
			{
				if (_approvalStatus != value)
				{
					_approvalStatus = value;
					OnPropertyChanged("ApprovalStatus");
				}
			}
		}
			
		private DateTime _approvalCreatedDate = DateTime.Parse("01/01/1900 00:00:00");
		///<summary>Database mapping to column tbTransactionApproval.ApprovalCreatedDate</summary>
		public DateTime ApprovalCreatedDate
		{
			get { return _approvalCreatedDate; }
			set
			{
				if (_approvalCreatedDate != value)
				{
					_approvalCreatedDate = value;
					OnPropertyChanged("ApprovalCreatedDate");
				}
			}
		}
			
		private DateTime _approvalModifiedDate = DateTime.Parse("01/01/1900 00:00:00");
		///<summary>Database mapping to column tbTransactionApproval.ApprovalModifiedDate</summary>
		public DateTime ApprovalModifiedDate
		{
			get { return _approvalModifiedDate; }
			set
			{
				if (_approvalModifiedDate != value)
				{
					_approvalModifiedDate = value;
					OnPropertyChanged("ApprovalModifiedDate");
				}
			}
		}
			
		private short _approvedUserID;
		///<summary>Database mapping to column tbTransactionApproval.ApprovedUserID</summary>
		[DataObjectField(true, false)]
		public short ApprovedUserID
		{
			get { return _approvedUserID; }
			set
			{
				if (_approvedUserID != value)
				{
					_approvedUserID = value;
					OnPropertyChanged("ApprovedUserID");
				}
			}
		}
			
		private short _approvedAlternateUserID = 0;
		///<summary>Database mapping to column tbTransactionApproval.ApprovedAlternateUserID</summary>
		public short ApprovedAlternateUserID
		{
			get { return _approvedAlternateUserID; }
			set
			{
				if (_approvedAlternateUserID != value)
				{
					_approvedAlternateUserID = value;
					OnPropertyChanged("ApprovedAlternateUserID");
				}
			}
		}
			
		private short _approvedByUserID = 0;
		///<summary>Database mapping to column tbTransactionApproval.ApprovedByUserID</summary>
		public short ApprovedByUserID
		{
			get { return _approvedByUserID; }
			set
			{
				if (_approvedByUserID != value)
				{
					_approvedByUserID = value;
					OnPropertyChanged("ApprovedByUserID");
				}
			}
		}
			
		private string _approvalRandomID = "";
		///<summary>Database mapping to column tbTransactionApproval.ApprovalRandomID</summary>
		public string ApprovalRandomID
		{
			get { return _approvalRandomID; }
			set
			{
				if (_approvalRandomID != value)
				{
					_approvalRandomID = value;
					OnPropertyChanged("ApprovalRandomID");
				}
			}
		}
		
		#endregion
		
		///<summary>Initializes a new instance of this class</summary>
		public TbTransactionApproval() : base()
		{
			// Default Constructor
		}
		
		///<summary>Retrieve an instance of this class using its ID from the persistence store</summary>
		[DataObjectMethod(DataObjectMethodType.Select)]
        public static TbTransactionApproval RetrieveByKey(short coyID, string trnType, string approvalType, string trnNo, short approvedUserID)
		{
			DBManager db = DBManager.GetInstance();
			QueryHelper helper = db.Engine.QueryHelper;
			string where = helper.GetExpression("TbTransactionApproval.CoyID", coyID);
			where += " and ";
			where += helper.GetExpression("TbTransactionApproval.TrnType", trnType);
			where += " and ";
			where += helper.GetExpression("TbTransactionApproval.ApprovalType", approvalType);
			where += " and ";
			where += helper.GetExpression("TbTransactionApproval.TrnNo", trnNo);
			where += " and ";
			where += helper.GetExpression("TbTransactionApproval.ApprovedUserID", approvedUserID);

			return RetrieveFirst(where);			
		}
		
		///<summary>Delete instance from the persistence store based on primary key(s)</summary>
		[DataObjectMethod(DataObjectMethodType.Delete)]
        public static int DeleteByKey(short coyID, string trnType, string approvalType, string trnNo, short approvedUserID)
		{			
			DBManager db = DBManager.GetInstance();		
			QueryHelper helper = db.Engine.QueryHelper;
			string where = helper.GetExpression("TbTransactionApproval.CoyID", coyID);
			where += " and ";
			where += helper.GetExpression("TbTransactionApproval.TrnType", trnType);
			where += " and ";
			where += helper.GetExpression("TbTransactionApproval.ApprovalType", approvalType);
			where += " and ";
			where += helper.GetExpression("TbTransactionApproval.TrnNo", trnNo);
			where += " and ";
			where += helper.GetExpression("TbTransactionApproval.ApprovedUserID", approvedUserID);
			
			return Delete(where);
		}
		
		///<summary>Delete instance from the persistence store based on primary key(s) using a transaction</summary>
		///<param name="transaction">An instance of a Wilson.ORMapper.Transaction to perform operation with.</param>
		public static int DeleteByKey(Wilson.ORMapper.Transaction transaction, short coyID, string trnType, string approvalType, string trnNo, short approvedUserID)
		{			
			DBManager db = DBManager.GetInstance();
			QueryHelper helper = db.Engine.QueryHelper;
			string where = helper.GetExpression("TbTransactionApproval.CoyID", coyID);
			where += " and ";
			where += helper.GetExpression("TbTransactionApproval.TrnType", trnType);
			where += " and ";
			where += helper.GetExpression("TbTransactionApproval.ApprovalType", approvalType);
			where += " and ";
			where += helper.GetExpression("TbTransactionApproval.TrnNo", trnNo);
			where += " and ";
			where += helper.GetExpression("TbTransactionApproval.ApprovedUserID", approvedUserID);
			
			return Delete(transaction, where);
		}		
		#region IObjectHelper
		/// <summary>Indexer to update local member variables</summary>	
		/// <remarks>This indexer is used by the Wilson ORMapper</remarks>
		object IObjectHelper.this[string memberName]
		{
			get {
				switch (memberName) {
					case "_coyID": return _coyID;
					case "_trnType": return _trnType;
					case "_approvalType": return _approvalType;
					case "_trnNo": return _trnNo;
					case "_approvalStatus": return _approvalStatus;
					case "_approvalCreatedDate": return _approvalCreatedDate;
					case "_approvalModifiedDate": return _approvalModifiedDate;
					case "_approvedUserID": return _approvedUserID;
					case "_approvedAlternateUserID": return _approvedAlternateUserID;
					case "_approvedByUserID": return _approvedByUserID;
					case "_approvalRandomID": return _approvalRandomID;
									
					default: throw new Exception(string.Format("Mapping: IObjectHelper Get is missing member case {0}", memberName));
				}
			}
			set {
				//handle null values
				if(value == null)
					return;
					
				switch (memberName) {
					case "_coyID": _coyID = (short)value; break;
					case "_trnType": _trnType = (string)value; break;
					case "_approvalType": _approvalType = (string)value; break;
					case "_trnNo": _trnNo = (string)value; break;
					case "_approvalStatus": _approvalStatus = (string)value; break;
					case "_approvalCreatedDate": _approvalCreatedDate = (DateTime)value; break;
					case "_approvalModifiedDate": _approvalModifiedDate = (DateTime)value; break;
					case "_approvedUserID": _approvedUserID = (short)value; break;
					case "_approvedAlternateUserID": _approvedAlternateUserID = (short)value; break;
					case "_approvedByUserID": _approvedByUserID = (short)value; break;
					case "_approvalRandomID": _approvalRandomID = (string)value; break;
				
					default: throw new Exception(string.Format("Mapping: IObjectHelper Set is missing member case {0}", memberName));
				}
			}
		}
		#endregion
		
		#region ToString
		///<summary>
		///Overwrites the base ToString method. This is used for AuditTrail purposes.
		///</summary>
		public override string ToString()
		{
			System.Text.StringBuilder stb = new System.Text.StringBuilder(500);
			
			stb.AppendFormat("_coyID={0}\n,", _coyID.ToString() );
			stb.AppendFormat("_trnType={0}\n,", _trnType.ToString() );
			stb.AppendFormat("_approvalType={0}\n,", _approvalType.ToString() );
			stb.AppendFormat("_trnNo={0}\n,", _trnNo.ToString() );
			stb.AppendFormat("_approvalStatus={0}\n,", _approvalStatus.ToString() );
			stb.AppendFormat("_approvalCreatedDate={0}\n,", _approvalCreatedDate.ToString() );
			stb.AppendFormat("_approvalModifiedDate={0}\n,", _approvalModifiedDate.ToString() );
			stb.AppendFormat("_approvedUserID={0}\n,", _approvedUserID.ToString() );
			stb.AppendFormat("_approvedAlternateUserID={0}\n,", _approvedAlternateUserID.ToString() );
			stb.AppendFormat("_approvedByUserID={0}\n,", _approvedByUserID.ToString() );
			stb.AppendFormat("_approvalRandomID={0}\n,", _approvalRandomID.ToString() );
							
			
			return stb.ToString();
		}
		#endregion

	}
}
