//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//	   DO NOT MODIFY contents of this file. Changes to this
//	   file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using Wilson.ORMapper;
using eLogixCore;

namespace GMSCore.Entity
{
	///<summary>Database mapping to table tbTempTransfer_Testing</summary>
	[DataObject(true)]
    public partial class Testing : PersistBase<Testing>, IObjectHelper
	{
		#region Properties
	
		private short _coyID;
		///<summary>Database mapping to column tbTempTransfer_Testing.CoyID</summary>
		public short CoyID
		{
			get { return _coyID; }
			set
			{
				if (_coyID != value)
				{
					_coyID = value;
					OnPropertyChanged("CoyID");
				}
			}
		}
			
		private int _projectID;
		///<summary>Database mapping to column tbTempTransfer_Testing.ProjectID</summary>
		public int ProjectID
		{
			get { return _projectID; }
			set
			{
				if (_projectID != value)
				{
					_projectID = value;
					OnPropertyChanged("ProjectID");
				}
			}
		}
			
		private int _departmentID;
		///<summary>Database mapping to column tbTempTransfer_Testing.DepartmentID</summary>
		public int DepartmentID
		{
			get { return _departmentID; }
			set
			{
				if (_departmentID != value)
				{
					_departmentID = value;
					OnPropertyChanged("DepartmentID");
				}
			}
		}
			
		private int _sectionID;
		///<summary>Database mapping to column tbTempTransfer_Testing.SectionID</summary>
		public int SectionID
		{
			get { return _sectionID; }
			set
			{
				if (_sectionID != value)
				{
					_sectionID = value;
					OnPropertyChanged("SectionID");
				}
			}
		}
			
		private double _tbYear = 0;
		///<summary>Database mapping to column tbTempTransfer_Testing.tbYear</summary>
		public double TbYear
		{
			get { return _tbYear; }
			set
			{
				if (_tbYear != value)
				{
					_tbYear = value;
					OnPropertyChanged("TbYear");
				}
			}
		}
			
		private double _tbMonth = 0;
		///<summary>Database mapping to column tbTempTransfer_Testing.tbMonth</summary>
		public double TbMonth
		{
			get { return _tbMonth; }
			set
			{
				if (_tbMonth != value)
				{
					_tbMonth = value;
					OnPropertyChanged("TbMonth");
				}
			}
		}
			
		private string _cOAID = "";
		///<summary>Database mapping to column tbTempTransfer_Testing.COAID</summary>
		public string COAID
		{
			get { return _cOAID; }
			set
			{
				if (_cOAID != value)
				{
					_cOAID = value;
					OnPropertyChanged("COAID");
				}
			}
		}
			
		private double _mTDTotal = 0;
		///<summary>Database mapping to column tbTempTransfer_Testing.MTDTotal</summary>
		public double MTDTotal
		{
			get { return _mTDTotal; }
			set
			{
				if (_mTDTotal != value)
				{
					_mTDTotal = value;
					OnPropertyChanged("MTDTotal");
				}
			}
		}
			
		private double _yTDTotal = 0;
		///<summary>Database mapping to column tbTempTransfer_Testing.YTDTotal</summary>
		public double YTDTotal
		{
			get { return _yTDTotal; }
			set
			{
				if (_yTDTotal != value)
				{
					_yTDTotal = value;
					OnPropertyChanged("YTDTotal");
				}
			}
		}
			
		private int _createdBy;
		///<summary>Database mapping to column tbTempTransfer_Testing.CreatedBy</summary>
		public int CreatedBy
		{
			get { return _createdBy; }
			set
			{
				if (_createdBy != value)
				{
					_createdBy = value;
					OnPropertyChanged("CreatedBy");
				}
			}
		}
			
		private DateTime _createdDate;
		///<summary>Database mapping to column tbTempTransfer_Testing.CreatedDate</summary>
		public DateTime CreatedDate
		{
			get { return _createdDate; }
			set
			{
				if (_createdDate != value)
				{
					_createdDate = value;
					OnPropertyChanged("CreatedDate");
				}
			}
		}
		
		#endregion
		
		///<summary>Initializes a new instance of this class</summary>
		public Testing() : base()
		{
			// Default Constructor
		}
		
		#region IObjectHelper
		/// <summary>Indexer to update local member variables</summary>	
		/// <remarks>This indexer is used by the Wilson ORMapper</remarks>
		object IObjectHelper.this[string memberName]
		{
			get {
				switch (memberName) {
					case "_coyID": return _coyID;
					case "_projectID": return _projectID;
					case "_departmentID": return _departmentID;
					case "_sectionID": return _sectionID;
					case "_tbYear": return _tbYear;
					case "_tbMonth": return _tbMonth;
					case "_cOAID": return _cOAID;
					case "_mTDTotal": return _mTDTotal;
					case "_yTDTotal": return _yTDTotal;
					case "_createdBy": return _createdBy;
					case "_createdDate": return _createdDate;
									
					default: throw new Exception(string.Format("Mapping: IObjectHelper Get is missing member case {0}", memberName));
				}
			}
			set {
				//handle null values
				if(value == null)
					return;
					
				switch (memberName) {
					case "_coyID": _coyID = (short)value; break;
					case "_projectID": _projectID = (int)value; break;
					case "_departmentID": _departmentID = (int)value; break;
					case "_sectionID": _sectionID = (int)value; break;
					case "_tbYear": _tbYear = (double)value; break;
					case "_tbMonth": _tbMonth = (double)value; break;
					case "_cOAID": _cOAID = (string)value; break;
					case "_mTDTotal": _mTDTotal = (double)value; break;
					case "_yTDTotal": _yTDTotal = (double)value; break;
					case "_createdBy": _createdBy = (int)value; break;
					case "_createdDate": _createdDate = (DateTime)value; break;
				
					default: throw new Exception(string.Format("Mapping: IObjectHelper Set is missing member case {0}", memberName));
				}
			}
		}
		#endregion
		
		#region ToString
		///<summary>
		///Overwrites the base ToString method. This is used for AuditTrail purposes.
		///</summary>
		public override string ToString()
		{
			System.Text.StringBuilder stb = new System.Text.StringBuilder(500);
			
			stb.AppendFormat("_coyID={0}\n,", _coyID.ToString() );
			stb.AppendFormat("_projectID={0}\n,", _projectID.ToString() );
			stb.AppendFormat("_departmentID={0}\n,", _departmentID.ToString() );
			stb.AppendFormat("_sectionID={0}\n,", _sectionID.ToString() );
			stb.AppendFormat("_tbYear={0}\n,", _tbYear.ToString() );
			stb.AppendFormat("_tbMonth={0}\n,", _tbMonth.ToString() );
			stb.AppendFormat("_cOAID={0}\n,", _cOAID.ToString() );
			stb.AppendFormat("_mTDTotal={0}\n,", _mTDTotal.ToString() );
			stb.AppendFormat("_yTDTotal={0}\n,", _yTDTotal.ToString() );
			stb.AppendFormat("_createdBy={0}\n,", _createdBy.ToString() );
			stb.AppendFormat("_createdDate={0}\n,", _createdDate.ToString() );
							
			
			return stb.ToString();
		}
		#endregion

	}
}
